// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (
    country_code, region, city, postal_code, street_line,
    building_number, unit_number, directions
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, country_code, region, city, postal_code, street_line, building_number, unit_number, directions, created_at
`

type CreateAddressParams struct {
	CountryCode    string  `json:"country_code"`
	Region         *string `json:"region"`
	City           string  `json:"city"`
	PostalCode     string  `json:"postal_code"`
	StreetLine     string  `json:"street_line"`
	BuildingNumber string  `json:"building_number"`
	UnitNumber     *string `json:"unit_number"`
	Directions     *string `json:"directions"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.CountryCode,
		arg.Region,
		arg.City,
		arg.PostalCode,
		arg.StreetLine,
		arg.BuildingNumber,
		arg.UnitNumber,
		arg.Directions,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.Region,
		&i.City,
		&i.PostalCode,
		&i.StreetLine,
		&i.BuildingNumber,
		&i.UnitNumber,
		&i.Directions,
		&i.CreatedAt,
	)
	return i, err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, country_code, region, city, postal_code, street_line, building_number, unit_number, directions, created_at FROM addresses WHERE id = $1
`

func (q *Queries) GetAddressByID(ctx context.Context, id uuid.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.Region,
		&i.City,
		&i.PostalCode,
		&i.StreetLine,
		&i.BuildingNumber,
		&i.UnitNumber,
		&i.Directions,
		&i.CreatedAt,
	)
	return i, err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses SET
    country_code    = COALESCE($1, country_code),
    region          = COALESCE($2, region),
    city            = COALESCE($3, city),
    postal_code     = COALESCE($4, postal_code),
    street_line     = COALESCE($5, street_line),
    building_number = COALESCE($6, building_number),
    unit_number     = COALESCE($7, unit_number),
    directions      = COALESCE($8, directions)
WHERE id = $9
RETURNING id, country_code, region, city, postal_code, street_line, building_number, unit_number, directions, created_at
`

type UpdateAddressParams struct {
	CountryCode    *string   `json:"country_code"`
	Region         *string   `json:"region"`
	City           *string   `json:"city"`
	PostalCode     *string   `json:"postal_code"`
	StreetLine     *string   `json:"street_line"`
	BuildingNumber *string   `json:"building_number"`
	UnitNumber     *string   `json:"unit_number"`
	Directions     *string   `json:"directions"`
	ID             uuid.UUID `json:"id"`
}

// Selective update — pass NULL on any narg to keep the existing value.
func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.CountryCode,
		arg.Region,
		arg.City,
		arg.PostalCode,
		arg.StreetLine,
		arg.BuildingNumber,
		arg.UnitNumber,
		arg.Directions,
		arg.ID,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.Region,
		&i.City,
		&i.PostalCode,
		&i.StreetLine,
		&i.BuildingNumber,
		&i.UnitNumber,
		&i.Directions,
		&i.CreatedAt,
	)
	return i, err
}
