// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTherapistsInOrg = `-- name: CountTherapistsInOrg :one
SELECT COUNT(*)::int AS therapists_count
FROM users
WHERE organization_id = $1
  AND role IN ('THERAPIST', 'ORG_ADMIN')
  AND deleted_at IS NULL
`

func (q *Queries) CountTherapistsInOrg(ctx context.Context, organizationID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countTherapistsInOrg, organizationID)
	var therapists_count int32
	err := row.Scan(&therapists_count)
	return therapists_count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (legal_name, tax_id, vat_id_eu, type, headquarters_address_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, legal_name, tax_id, vat_id_eu, headquarters_address_id, primary_admin_user_id, type, created_at, deleted_at
`

type CreateOrganizationParams struct {
	LegalName             string           `json:"legal_name"`
	TaxID                 *string          `json:"tax_id"`
	VatIDEu               *string          `json:"vat_id_eu"`
	Type                  OrganizationType `json:"type"`
	HeadquartersAddressID pgtype.UUID      `json:"headquarters_address_id"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.LegalName,
		arg.TaxID,
		arg.VatIDEu,
		arg.Type,
		arg.HeadquartersAddressID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TaxID,
		&i.VatIDEu,
		&i.HeadquartersAddressID,
		&i.PrimaryAdminUserID,
		&i.Type,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, legal_name, tax_id, vat_id_eu, headquarters_address_id, primary_admin_user_id, type, created_at, deleted_at FROM organizations
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TaxID,
		&i.VatIDEu,
		&i.HeadquartersAddressID,
		&i.PrimaryAdminUserID,
		&i.Type,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, legal_name, tax_id, vat_id_eu, headquarters_address_id, primary_admin_user_id, type, created_at, deleted_at FROM organizations
WHERE deleted_at IS NULL
  AND (
      $1::text IS NULL
      OR legal_name ILIKE '%' || $1::text || '%'
  )
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListOrganizationsParams struct {
	SearchTerm     *string            `json:"search_term"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

// Cursor pagination keyed on (created_at, id). Pass an empty cursor for the
// first page; for subsequent pages pass the last row's (created_at, id).
func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations,
		arg.SearchTerm,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.LegalName,
			&i.TaxID,
			&i.VatIDEu,
			&i.HeadquartersAddressID,
			&i.PrimaryAdminUserID,
			&i.Type,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganizationPrimaryAdmin = `-- name: SetOrganizationPrimaryAdmin :exec
UPDATE organizations
SET primary_admin_user_id = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SetOrganizationPrimaryAdminParams struct {
	ID                 uuid.UUID   `json:"id"`
	PrimaryAdminUserID pgtype.UUID `json:"primary_admin_user_id"`
}

func (q *Queries) SetOrganizationPrimaryAdmin(ctx context.Context, arg SetOrganizationPrimaryAdminParams) error {
	_, err := q.db.Exec(ctx, setOrganizationPrimaryAdmin, arg.ID, arg.PrimaryAdminUserID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations SET
    legal_name              = COALESCE($1, legal_name),
    tax_id                  = COALESCE($2, tax_id),
    vat_id_eu               = COALESCE($3, vat_id_eu),
    type                    = COALESCE($4, type),
    headquarters_address_id = COALESCE($5, headquarters_address_id),
    primary_admin_user_id   = COALESCE($6, primary_admin_user_id)
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, legal_name, tax_id, vat_id_eu, headquarters_address_id, primary_admin_user_id, type, created_at, deleted_at
`

type UpdateOrganizationParams struct {
	LegalName             *string           `json:"legal_name"`
	TaxID                 *string           `json:"tax_id"`
	VatIDEu               *string           `json:"vat_id_eu"`
	Type                  *OrganizationType `json:"type"`
	HeadquartersAddressID pgtype.UUID       `json:"headquarters_address_id"`
	PrimaryAdminUserID    pgtype.UUID       `json:"primary_admin_user_id"`
	ID                    uuid.UUID         `json:"id"`
}

// Selective UPDATE — every column uses COALESCE(sqlc.narg, current). Pass
// NULL on any narg you don't want to touch. legal_name and type collapse
// to their existing value when NULL is passed, so they're effectively
// partial too.
func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.LegalName,
		arg.TaxID,
		arg.VatIDEu,
		arg.Type,
		arg.HeadquartersAddressID,
		arg.PrimaryAdminUserID,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TaxID,
		&i.VatIDEu,
		&i.HeadquartersAddressID,
		&i.PrimaryAdminUserID,
		&i.Type,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
