// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    role, firebase_uid, email,
    first_name, last_name, ui_language, timezone, has_accepted_tos
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, role, organization_id, default_modality_id, billing_address_id, firebase_uid, email, phone_number, is_email_verified, first_name, last_name, professional_title, credentials_number, biography, avatar_url, ui_language, timezone, has_accepted_tos, has_marketing_consent, created_at, deleted_at, report_preferences
`

type CreateUserParams struct {
	Role           UserRole `json:"role"`
	FirebaseUid    *string  `json:"firebase_uid"`
	Email          *string  `json:"email"`
	FirstName      string   `json:"first_name"`
	LastName       string   `json:"last_name"`
	UiLanguage     string   `json:"ui_language"`
	Timezone       string   `json:"timezone"`
	HasAcceptedTos bool     `json:"has_accepted_tos"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Role,
		arg.FirebaseUid,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.UiLanguage,
		arg.Timezone,
		arg.HasAcceptedTos,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.OrganizationID,
		&i.DefaultModalityID,
		&i.BillingAddressID,
		&i.FirebaseUid,
		&i.Email,
		&i.PhoneNumber,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.ProfessionalTitle,
		&i.CredentialsNumber,
		&i.Biography,
		&i.AvatarUrl,
		&i.UiLanguage,
		&i.Timezone,
		&i.HasAcceptedTos,
		&i.HasMarketingConsent,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.ReportPreferences,
	)
	return i, err
}

const getReportPreferences = `-- name: GetReportPreferences :one
SELECT report_preferences
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

// Returns the raw JSONB. Empty object {} when the user has never
// customized; Go layer turns that into the default ReportPreferences.
func (q *Queries) GetReportPreferences(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getReportPreferences, id)
	var report_preferences []byte
	err := row.Scan(&report_preferences)
	return report_preferences, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, role, organization_id, default_modality_id, billing_address_id, firebase_uid, email, phone_number, is_email_verified, first_name, last_name, professional_title, credentials_number, biography, avatar_url, ui_language, timezone, has_accepted_tos, has_marketing_consent, created_at, deleted_at, report_preferences FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.OrganizationID,
		&i.DefaultModalityID,
		&i.BillingAddressID,
		&i.FirebaseUid,
		&i.Email,
		&i.PhoneNumber,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.ProfessionalTitle,
		&i.CredentialsNumber,
		&i.Biography,
		&i.AvatarUrl,
		&i.UiLanguage,
		&i.Timezone,
		&i.HasAcceptedTos,
		&i.HasMarketingConsent,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.ReportPreferences,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, role, organization_id, default_modality_id, billing_address_id, firebase_uid, email, phone_number, is_email_verified, first_name, last_name, professional_title, credentials_number, biography, avatar_url, ui_language, timezone, has_accepted_tos, has_marketing_consent, created_at, deleted_at, report_preferences FROM users WHERE firebase_uid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.OrganizationID,
		&i.DefaultModalityID,
		&i.BillingAddressID,
		&i.FirebaseUid,
		&i.Email,
		&i.PhoneNumber,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.ProfessionalTitle,
		&i.CredentialsNumber,
		&i.Biography,
		&i.AvatarUrl,
		&i.UiLanguage,
		&i.Timezone,
		&i.HasAcceptedTos,
		&i.HasMarketingConsent,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.ReportPreferences,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role, organization_id, default_modality_id, billing_address_id, firebase_uid, email, phone_number, is_email_verified, first_name, last_name, professional_title, credentials_number, biography, avatar_url, ui_language, timezone, has_accepted_tos, has_marketing_consent, created_at, deleted_at, report_preferences FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.OrganizationID,
		&i.DefaultModalityID,
		&i.BillingAddressID,
		&i.FirebaseUid,
		&i.Email,
		&i.PhoneNumber,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.ProfessionalTitle,
		&i.CredentialsNumber,
		&i.Biography,
		&i.AvatarUrl,
		&i.UiLanguage,
		&i.Timezone,
		&i.HasAcceptedTos,
		&i.HasMarketingConsent,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.ReportPreferences,
	)
	return i, err
}

const listTherapistsByOrganization = `-- name: ListTherapistsByOrganization :many
SELECT id, role, organization_id, default_modality_id, billing_address_id, firebase_uid, email, phone_number, is_email_verified, first_name, last_name, professional_title, credentials_number, biography, avatar_url, ui_language, timezone, has_accepted_tos, has_marketing_consent, created_at, deleted_at, report_preferences FROM users
WHERE organization_id = $1
  AND role = 'THERAPIST'
  AND deleted_at IS NULL
ORDER BY last_name, first_name
`

func (q *Queries) ListTherapistsByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listTherapistsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.OrganizationID,
			&i.DefaultModalityID,
			&i.BillingAddressID,
			&i.FirebaseUid,
			&i.Email,
			&i.PhoneNumber,
			&i.IsEmailVerified,
			&i.FirstName,
			&i.LastName,
			&i.ProfessionalTitle,
			&i.CredentialsNumber,
			&i.Biography,
			&i.AvatarUrl,
			&i.UiLanguage,
			&i.Timezone,
			&i.HasAcceptedTos,
			&i.HasMarketingConsent,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ReportPreferences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE users SET
    first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    professional_title = $3,
    credentials_number = $4,
    biography = $5,
    phone_number = $6
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, role, organization_id, default_modality_id, billing_address_id, firebase_uid, email, phone_number, is_email_verified, first_name, last_name, professional_title, credentials_number, biography, avatar_url, ui_language, timezone, has_accepted_tos, has_marketing_consent, created_at, deleted_at, report_preferences
`

type UpdateProfileParams struct {
	FirstName         *string   `json:"first_name"`
	LastName          *string   `json:"last_name"`
	ProfessionalTitle *string   `json:"professional_title"`
	CredentialsNumber *string   `json:"credentials_number"`
	Biography         *string   `json:"biography"`
	PhoneNumber       *string   `json:"phone_number"`
	ID                uuid.UUID `json:"id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.FirstName,
		arg.LastName,
		arg.ProfessionalTitle,
		arg.CredentialsNumber,
		arg.Biography,
		arg.PhoneNumber,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.OrganizationID,
		&i.DefaultModalityID,
		&i.BillingAddressID,
		&i.FirebaseUid,
		&i.Email,
		&i.PhoneNumber,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.ProfessionalTitle,
		&i.CredentialsNumber,
		&i.Biography,
		&i.AvatarUrl,
		&i.UiLanguage,
		&i.Timezone,
		&i.HasAcceptedTos,
		&i.HasMarketingConsent,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.ReportPreferences,
	)
	return i, err
}

const updateReportPreferences = `-- name: UpdateReportPreferences :one
UPDATE users
SET report_preferences = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING report_preferences
`

type UpdateReportPreferencesParams struct {
	ID                uuid.UUID `json:"id"`
	ReportPreferences []byte    `json:"report_preferences"`
}

// Replaces the entire preferences blob. The Go handler sanitizes
// and validates the blob shape before calling this; sqlc just
// writes whatever JSONB it gets. Returns the post-update value so
// the gRPC handler can echo it back without a second SELECT.
func (q *Queries) UpdateReportPreferences(ctx context.Context, arg UpdateReportPreferencesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, updateReportPreferences, arg.ID, arg.ReportPreferences)
	var report_preferences []byte
	err := row.Scan(&report_preferences)
	return report_preferences, err
}
