// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audio_uploads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAudioUpload = `-- name: CompleteAudioUpload :one
UPDATE audio_uploads SET
    status = 'UPLOADED',
    upload_completed_at = now(),
    duration_seconds = $2,
    file_size_bytes = $3,
    chunk_count = $4
WHERE id = $1
RETURNING id, therapist_id, patient_file_id, session_id, bucket_name, object_path, content_type, file_size_bytes, duration_seconds, sample_rate_hz, chunk_count, status, upload_started_at, upload_completed_at, expires_at, idempotency_key, client_app_version, client_platform, error_message, created_at, resumable_session_uri, resumable_session_expires_at, processed_generation
`

type CompleteAudioUploadParams struct {
	ID              pgtype.UUID
	DurationSeconds *int32
	FileSizeBytes   *int64
	ChunkCount      int32
}

func (q *Queries) CompleteAudioUpload(ctx context.Context, arg CompleteAudioUploadParams) (AudioUpload, error) {
	row := q.db.QueryRow(ctx, completeAudioUpload,
		arg.ID,
		arg.DurationSeconds,
		arg.FileSizeBytes,
		arg.ChunkCount,
	)
	var i AudioUpload
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.SessionID,
		&i.BucketName,
		&i.ObjectPath,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.DurationSeconds,
		&i.SampleRateHz,
		&i.ChunkCount,
		&i.Status,
		&i.UploadStartedAt,
		&i.UploadCompletedAt,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.ClientAppVersion,
		&i.ClientPlatform,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ResumableSessionUri,
		&i.ResumableSessionExpiresAt,
		&i.ProcessedGeneration,
	)
	return i, err
}

const countAudioChunksByUpload = `-- name: CountAudioChunksByUpload :one
SELECT COUNT(*) FROM audio_chunks WHERE audio_upload_id = $1
`

// Stage 2 of feat/stt-long_audio_support: stt-submit + ConvertAudio
// both use this to detect "this upload was already chunked" — the
// COUNT must equal expected_chunk_count for the second call to
// short-circuit. See chunker.go.
func (q *Queries) CountAudioChunksByUpload(ctx context.Context, audioUploadID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAudioChunksByUpload, audioUploadID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAudioChunk = `-- name: CreateAudioChunk :exec
INSERT INTO audio_chunks (
    audio_upload_id, chunk_index,
    bucket_name, object_path,
    start_offset_ms, seam_offset_ms, end_offset_ms,
    overlap_ms, cut_on_silence
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAudioChunkParams struct {
	AudioUploadID pgtype.UUID
	ChunkIndex    int32
	BucketName    string
	ObjectPath    string
	StartOffsetMs int64
	SeamOffsetMs  int64
	EndOffsetMs   int64
	OverlapMs     int32
	CutOnSilence  bool
}

// One audio_chunks row. Wrapped in a single tx by the
// ConvertAudio handler so partial inserts don't survive a crash.
// UNIQUE on (audio_upload_id, chunk_index) prevents the
// concurrent-ConvertAudio race (the pg_advisory_xact_lock in the
// handler is the primary serialization mechanism).
func (q *Queries) CreateAudioChunk(ctx context.Context, arg CreateAudioChunkParams) error {
	_, err := q.db.Exec(ctx, createAudioChunk,
		arg.AudioUploadID,
		arg.ChunkIndex,
		arg.BucketName,
		arg.ObjectPath,
		arg.StartOffsetMs,
		arg.SeamOffsetMs,
		arg.EndOffsetMs,
		arg.OverlapMs,
		arg.CutOnSilence,
	)
	return err
}

const createAudioUpload = `-- name: CreateAudioUpload :one
INSERT INTO audio_uploads (
    therapist_id, patient_file_id, session_id, bucket_name, object_path,
    content_type, idempotency_key, client_app_version, client_platform
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, therapist_id, patient_file_id, session_id, bucket_name, object_path, content_type, file_size_bytes, duration_seconds, sample_rate_hz, chunk_count, status, upload_started_at, upload_completed_at, expires_at, idempotency_key, client_app_version, client_platform, error_message, created_at, resumable_session_uri, resumable_session_expires_at, processed_generation
`

type CreateAudioUploadParams struct {
	TherapistID      pgtype.UUID
	PatientFileID    pgtype.UUID
	SessionID        pgtype.UUID
	BucketName       string
	ObjectPath       string
	ContentType      string
	IdempotencyKey   *string
	ClientAppVersion *string
	ClientPlatform   *string
}

// Option E (2026-05-25): session_id is set at upload-creation
// time. The session row in PENDING_UPLOAD status is created by
// the same gRPC handler in the same transaction, so the
// audio_uploads row never exists without a linked session. The
// partial UNIQUE INDEX from migration 000024
// (ux_sessions_audio_upload_id) enforces 1:1 on the session side.
func (q *Queries) CreateAudioUpload(ctx context.Context, arg CreateAudioUploadParams) (AudioUpload, error) {
	row := q.db.QueryRow(ctx, createAudioUpload,
		arg.TherapistID,
		arg.PatientFileID,
		arg.SessionID,
		arg.BucketName,
		arg.ObjectPath,
		arg.ContentType,
		arg.IdempotencyKey,
		arg.ClientAppVersion,
		arg.ClientPlatform,
	)
	var i AudioUpload
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.SessionID,
		&i.BucketName,
		&i.ObjectPath,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.DurationSeconds,
		&i.SampleRateHz,
		&i.ChunkCount,
		&i.Status,
		&i.UploadStartedAt,
		&i.UploadCompletedAt,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.ClientAppVersion,
		&i.ClientPlatform,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ResumableSessionUri,
		&i.ResumableSessionExpiresAt,
		&i.ProcessedGeneration,
	)
	return i, err
}

const deleteAudioChunksByUpload = `-- name: DeleteAudioChunksByUpload :exec
DELETE FROM audio_chunks WHERE audio_upload_id = $1
`

// Used by the recovery path: if a prior ConvertAudio crashed mid-
// chunking (some rows landed, some didn't), the retry detects
// partial state, deletes everything, and redoes the split. GCS
// objects from the partial run are left to OLM 48h.
func (q *Queries) DeleteAudioChunksByUpload(ctx context.Context, audioUploadID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAudioChunksByUpload, audioUploadID)
	return err
}

const getAudioUpload = `-- name: GetAudioUpload :one
SELECT id, therapist_id, patient_file_id, session_id, bucket_name, object_path, content_type, file_size_bytes, duration_seconds, sample_rate_hz, chunk_count, status, upload_started_at, upload_completed_at, expires_at, idempotency_key, client_app_version, client_platform, error_message, created_at, resumable_session_uri, resumable_session_expires_at, processed_generation FROM audio_uploads WHERE id = $1
`

func (q *Queries) GetAudioUpload(ctx context.Context, id pgtype.UUID) (AudioUpload, error) {
	row := q.db.QueryRow(ctx, getAudioUpload, id)
	var i AudioUpload
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.SessionID,
		&i.BucketName,
		&i.ObjectPath,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.DurationSeconds,
		&i.SampleRateHz,
		&i.ChunkCount,
		&i.Status,
		&i.UploadStartedAt,
		&i.UploadCompletedAt,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.ClientAppVersion,
		&i.ClientPlatform,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ResumableSessionUri,
		&i.ResumableSessionExpiresAt,
		&i.ProcessedGeneration,
	)
	return i, err
}

const getAudioUploadByIdempotency = `-- name: GetAudioUploadByIdempotency :one
SELECT id, therapist_id, patient_file_id, session_id, bucket_name, object_path, content_type, file_size_bytes, duration_seconds, sample_rate_hz, chunk_count, status, upload_started_at, upload_completed_at, expires_at, idempotency_key, client_app_version, client_platform, error_message, created_at, resumable_session_uri, resumable_session_expires_at, processed_generation FROM audio_uploads
WHERE idempotency_key = $1 AND therapist_id = $2
`

type GetAudioUploadByIdempotencyParams struct {
	IdempotencyKey *string
	TherapistID    pgtype.UUID
}

func (q *Queries) GetAudioUploadByIdempotency(ctx context.Context, arg GetAudioUploadByIdempotencyParams) (AudioUpload, error) {
	row := q.db.QueryRow(ctx, getAudioUploadByIdempotency, arg.IdempotencyKey, arg.TherapistID)
	var i AudioUpload
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.SessionID,
		&i.BucketName,
		&i.ObjectPath,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.DurationSeconds,
		&i.SampleRateHz,
		&i.ChunkCount,
		&i.Status,
		&i.UploadStartedAt,
		&i.UploadCompletedAt,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.ClientAppVersion,
		&i.ClientPlatform,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ResumableSessionUri,
		&i.ResumableSessionExpiresAt,
		&i.ProcessedGeneration,
	)
	return i, err
}

const markAudioUploadFailed = `-- name: MarkAudioUploadFailed :exec
UPDATE audio_uploads SET status = 'FAILED', error_message = $2 WHERE id = $1
`

type MarkAudioUploadFailedParams struct {
	ID           pgtype.UUID
	ErrorMessage *string
}

func (q *Queries) MarkAudioUploadFailed(ctx context.Context, arg MarkAudioUploadFailedParams) error {
	_, err := q.db.Exec(ctx, markAudioUploadFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markGenerationProcessed = `-- name: MarkGenerationProcessed :exec
UPDATE audio_uploads SET processed_generation = $2 WHERE id = $1
`

type MarkGenerationProcessedParams struct {
	ID                  pgtype.UUID
	ProcessedGeneration *int64
}

// docs/26 PR3: record the GCS object generation we've finalized so a
// redelivered (at-least-once) OBJECT_FINALIZE for the same generation is a no-op.
func (q *Queries) MarkGenerationProcessed(ctx context.Context, arg MarkGenerationProcessedParams) error {
	_, err := q.db.Exec(ctx, markGenerationProcessed, arg.ID, arg.ProcessedGeneration)
	return err
}

const setResumableSession = `-- name: SetResumableSession :exec
UPDATE audio_uploads
SET resumable_session_uri = $2, resumable_session_expires_at = $3
WHERE id = $1
`

type SetResumableSessionParams struct {
	ID                        pgtype.UUID
	ResumableSessionUri       *string
	ResumableSessionExpiresAt pgtype.Timestamptz
}

// docs/26 PR1: persist the GCS resumable session URI + expiry on the
// audio_uploads row at CreateAudioUpload time so retries reuse it.
func (q *Queries) SetResumableSession(ctx context.Context, arg SetResumableSessionParams) error {
	_, err := q.db.Exec(ctx, setResumableSession, arg.ID, arg.ResumableSessionUri, arg.ResumableSessionExpiresAt)
	return err
}

const updateAudioUploadAfterConversion = `-- name: UpdateAudioUploadAfterConversion :one
UPDATE audio_uploads SET
    object_path  = $2,
    content_type = $3,
    bucket_name  = $4
WHERE id = $1
RETURNING id, therapist_id, patient_file_id, session_id, bucket_name, object_path, content_type, file_size_bytes, duration_seconds, sample_rate_hz, chunk_count, status, upload_started_at, upload_completed_at, expires_at, idempotency_key, client_app_version, client_platform, error_message, created_at, resumable_session_uri, resumable_session_expires_at, processed_generation
`

type UpdateAudioUploadAfterConversionParams struct {
	ID          pgtype.UUID
	ObjectPath  string
	ContentType string
	BucketName  string
}

// Rewrites object_path + content_type after the new ConvertAudio RPC
// transcoded the GCS object (e.g. M4A → FLAC). Touched columns are
// bucket_name (defensively, in case we ever cross buckets — for now
// always the same) plus object_path + content_type. status stays at
// PENDING because conversion happens BEFORE CompleteAudioUpload.
// See services/ingestion-svc/internal/adapters/grpc/server.go::ConvertAudio.
func (q *Queries) UpdateAudioUploadAfterConversion(ctx context.Context, arg UpdateAudioUploadAfterConversionParams) (AudioUpload, error) {
	row := q.db.QueryRow(ctx, updateAudioUploadAfterConversion,
		arg.ID,
		arg.ObjectPath,
		arg.ContentType,
		arg.BucketName,
	)
	var i AudioUpload
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.SessionID,
		&i.BucketName,
		&i.ObjectPath,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.DurationSeconds,
		&i.SampleRateHz,
		&i.ChunkCount,
		&i.Status,
		&i.UploadStartedAt,
		&i.UploadCompletedAt,
		&i.ExpiresAt,
		&i.IdempotencyKey,
		&i.ClientAppVersion,
		&i.ClientPlatform,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ResumableSessionUri,
		&i.ResumableSessionExpiresAt,
		&i.ProcessedGeneration,
	)
	return i, err
}

const updateAudioUploadStatus = `-- name: UpdateAudioUploadStatus :exec
UPDATE audio_uploads
SET status = $2, error_message = $3, upload_completed_at = now()
WHERE id = $1
`

type UpdateAudioUploadStatusParams struct {
	ID           pgtype.UUID
	Status       UploadStatus
	ErrorMessage *string
}

func (q *Queries) UpdateAudioUploadStatus(ctx context.Context, arg UpdateAudioUploadStatusParams) error {
	_, err := q.db.Exec(ctx, updateAudioUploadStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
