// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type BillingCycle string

const (
	BillingCycleMONTHLY    BillingCycle = "MONTHLY"
	BillingCycleSEMIANNUAL BillingCycle = "SEMI_ANNUAL"
	BillingCycleANNUAL     BillingCycle = "ANNUAL"
)

func (e *BillingCycle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingCycle(s)
	case string:
		*e = BillingCycle(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingCycle: %T", src)
	}
	return nil
}

type NullBillingCycle struct {
	BillingCycle BillingCycle
	Valid        bool // Valid is true if BillingCycle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingCycle) Scan(value interface{}) error {
	if value == nil {
		ns.BillingCycle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingCycle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingCycle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingCycle), nil
}

type ContactForm string

const (
	ContactFormOFFICE ContactForm = "OFFICE"
	ContactFormONLINE ContactForm = "ONLINE"
	ContactFormFIELD  ContactForm = "FIELD"
	ContactFormPHONE  ContactForm = "PHONE"
)

func (e *ContactForm) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContactForm(s)
	case string:
		*e = ContactForm(s)
	default:
		return fmt.Errorf("unsupported scan type for ContactForm: %T", src)
	}
	return nil
}

type NullContactForm struct {
	ContactForm ContactForm
	Valid       bool // Valid is true if ContactForm is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContactForm) Scan(value interface{}) error {
	if value == nil {
		ns.ContactForm, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContactForm.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContactForm) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContactForm), nil
}

type OrganizationType string

const (
	OrganizationTypeSOLO       OrganizationType = "SOLO"
	OrganizationTypeCLINIC     OrganizationType = "CLINIC"
	OrganizationTypeENTERPRISE OrganizationType = "ENTERPRISE"
)

func (e *OrganizationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganizationType(s)
	case string:
		*e = OrganizationType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganizationType: %T", src)
	}
	return nil
}

type NullOrganizationType struct {
	OrganizationType OrganizationType
	Valid            bool // Valid is true if OrganizationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganizationType) Scan(value interface{}) error {
	if value == nil {
		ns.OrganizationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganizationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganizationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganizationType), nil
}

type OutboxStatus string

const (
	OutboxStatusPENDING   OutboxStatus = "PENDING"
	OutboxStatusPUBLISHED OutboxStatus = "PUBLISHED"
	OutboxStatusFAILED    OutboxStatus = "FAILED"
	OutboxStatusEXPIRED   OutboxStatus = "EXPIRED"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus
	Valid        bool // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type PaymentProvider string

const (
	PaymentProviderSTRIPE    PaymentProvider = "STRIPE"
	PaymentProviderP24       PaymentProvider = "P24"
	PaymentProviderAPPLEIAP  PaymentProvider = "APPLE_IAP"
	PaymentProviderGOOGLEIAP PaymentProvider = "GOOGLE_IAP"
	PaymentProviderMANUAL    PaymentProvider = "MANUAL"
)

func (e *PaymentProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProvider(s)
	case string:
		*e = PaymentProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProvider: %T", src)
	}
	return nil
}

type NullPaymentProvider struct {
	PaymentProvider PaymentProvider
	Valid           bool // Valid is true if PaymentProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProvider) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProvider), nil
}

type PlanTier string

const (
	PlanTierSOLO    PlanTier = "SOLO"
	PlanTierPRO     PlanTier = "PRO"
	PlanTierCLINIC  PlanTier = "CLINIC"
	PlanTierPATIENT PlanTier = "PATIENT"
)

func (e *PlanTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanTier(s)
	case string:
		*e = PlanTier(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanTier: %T", src)
	}
	return nil
}

type NullPlanTier struct {
	PlanTier PlanTier
	Valid    bool // Valid is true if PlanTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanTier) Scan(value interface{}) error {
	if value == nil {
		ns.PlanTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanTier), nil
}

type ProcessType string

const (
	ProcessTypeINDIVIDUAL ProcessType = "INDIVIDUAL"
	ProcessTypeCOUPLE     ProcessType = "COUPLE"
	ProcessTypeFAMILY     ProcessType = "FAMILY"
	ProcessTypeGROUP      ProcessType = "GROUP"
)

func (e *ProcessType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessType(s)
	case string:
		*e = ProcessType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessType: %T", src)
	}
	return nil
}

type NullProcessType struct {
	ProcessType ProcessType
	Valid       bool // Valid is true if ProcessType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessType) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessType), nil
}

type RelationStatus string

const (
	RelationStatusINVITED    RelationStatus = "INVITED"
	RelationStatusACTIVE     RelationStatus = "ACTIVE"
	RelationStatusPAUSED     RelationStatus = "PAUSED"
	RelationStatusTERMINATED RelationStatus = "TERMINATED"
)

func (e *RelationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RelationStatus(s)
	case string:
		*e = RelationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RelationStatus: %T", src)
	}
	return nil
}

type NullRelationStatus struct {
	RelationStatus RelationStatus
	Valid          bool // Valid is true if RelationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRelationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RelationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RelationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRelationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RelationStatus), nil
}

type SessionStatus string

const (
	SessionStatusCREATED      SessionStatus = "CREATED"
	SessionStatusRECORDING    SessionStatus = "RECORDING"
	SessionStatusUPLOADING    SessionStatus = "UPLOADING"
	SessionStatusTRANSCRIBING SessionStatus = "TRANSCRIBING"
	SessionStatusANALYZING    SessionStatus = "ANALYZING"
	SessionStatusCOMPLETED    SessionStatus = "COMPLETED"
	SessionStatusFAILED       SessionStatus = "FAILED"
	SessionStatusCANCELED     SessionStatus = "CANCELED"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus
	Valid         bool // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusTRIALING   SubscriptionStatus = "TRIALING"
	SubscriptionStatusACTIVE     SubscriptionStatus = "ACTIVE"
	SubscriptionStatusPASTDUE    SubscriptionStatus = "PAST_DUE"
	SubscriptionStatusCANCELED   SubscriptionStatus = "CANCELED"
	SubscriptionStatusINCOMPLETE SubscriptionStatus = "INCOMPLETE"
	SubscriptionStatusPAUSED     SubscriptionStatus = "PAUSED"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus
	Valid              bool // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type UploadStatus string

const (
	UploadStatusPENDING    UploadStatus = "PENDING"
	UploadStatusUPLOADED   UploadStatus = "UPLOADED"
	UploadStatusPROCESSING UploadStatus = "PROCESSING"
	UploadStatusFAILED     UploadStatus = "FAILED"
	UploadStatusEXPIRED    UploadStatus = "EXPIRED"
)

func (e *UploadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadStatus(s)
	case string:
		*e = UploadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadStatus: %T", src)
	}
	return nil
}

type NullUploadStatus struct {
	UploadStatus UploadStatus
	Valid        bool // Valid is true if UploadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UploadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadStatus), nil
}

type UserRole string

const (
	UserRoleTHERAPIST UserRole = "THERAPIST"
	UserRolePATIENT   UserRole = "PATIENT"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Address struct {
	ID             pgtype.UUID
	CountryCode    string
	Region         *string
	City           string
	PostalCode     string
	StreetLine     string
	BuildingNumber string
	UnitNumber     *string
	Directions     *string
	CreatedAt      pgtype.Timestamptz
}

type AudioUpload struct {
	ID                pgtype.UUID
	TherapistID       pgtype.UUID
	PatientFileID     pgtype.UUID
	SessionID         pgtype.UUID
	BucketName        string
	ObjectPath        string
	ContentType       string
	FileSizeBytes     *int64
	DurationSeconds   *int32
	SampleRateHz      *int32
	ChunkCount        int32
	Status            UploadStatus
	UploadStartedAt   pgtype.Timestamptz
	UploadCompletedAt pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	IdempotencyKey    *string
	ClientAppVersion  *string
	ClientPlatform    *string
	ErrorMessage      *string
	CreatedAt         pgtype.Timestamptz
}

type AuditEvent struct {
	ID             pgtype.UUID
	ActorUserID    pgtype.UUID
	OrganizationID pgtype.UUID
	Action         string
	ResourceType   string
	ResourceID     pgtype.UUID
	Metadata       []byte
	IpAddress      *netip.Addr
	UserAgent      *string
	OccurredAt     pgtype.Timestamptz
}

type HitopDimension struct {
	ID          pgtype.UUID
	Code        string
	DisplayName string
	ParentCode  *string
	Description *string
	Level       string
	IsActive    bool
}

type HitopMeasurement struct {
	ID                   pgtype.UUID
	SessionID            pgtype.UUID
	ReportID             pgtype.UUID
	DimensionID          pgtype.UUID
	Score                pgtype.Numeric
	Confidence           pgtype.Numeric
	EvidenceCiphertext   []byte
	EvidenceEncryptedDek []byte
	MeasuredAt           pgtype.Timestamptz
}

type Modality struct {
	ID                        pgtype.UUID
	SystemCode                string
	DisplayName               string
	TherapistAiGeneralPrompt  []byte
	TherapistAiSectionPrompts []byte
	PatientAiGeneralPrompt    []byte
	PatientAiSectionPrompts   []byte
	IsSupported               bool
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type Organization struct {
	ID                    pgtype.UUID
	LegalName             string
	TaxID                 *string
	VatIDEu               *string
	HeadquartersAddressID pgtype.UUID
	PrimaryAdminUserID    pgtype.UUID
	Type                  OrganizationType
	CreatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
}

type PatientFile struct {
	ID                    pgtype.UUID
	TherapistID           pgtype.UUID
	PatientID             pgtype.UUID
	RelationID            pgtype.UUID
	ModalityID            pgtype.UUID
	WorkingAlias          string
	ProcessType           ProcessType
	InitialComplaint      *string
	IsProcessClosed       bool
	HasRecordingConsent   bool
	ConsentGivenAt        pgtype.Timestamptz
	FirstConsultationAt   pgtype.Timestamptz
	PrivateTherapistNotes *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
}

type RagMemory struct {
	ID                  pgtype.UUID
	PatientFileID       pgtype.UUID
	SourceSessionID     pgtype.UUID
	SourceReportID      pgtype.UUID
	SummaryCiphertext   []byte
	SummaryEncryptedDek []byte
	Embedding           *pgvector.Vector
	ChunkType           string
	ImportanceScore     pgtype.Numeric
	IsCompacted         bool
	CompactedIntoID     pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	LastAccessedAt      pgtype.Timestamptz
}

type Report struct {
	ID                   pgtype.UUID
	SessionID            pgtype.UUID
	TranscriptID         pgtype.UUID
	ModalityID           pgtype.UUID
	ReportCiphertext     []byte
	ReportEncryptedDek   []byte
	Title                *string
	SummaryShort         *string
	SentimentLabel       *string
	RiskLevel            *string
	SpeakerRoleInference []byte
	LlmModel             string
	LlmInputTokens       *int32
	LlmOutputTokens      *int32
	LlmProcessingSeconds *int32
	LlmTotalCostUsd      pgtype.Numeric
	ParentReportID       pgtype.UUID
	GenerationCount      int32
	CreatedAt            pgtype.Timestamptz
}

type Session struct {
	ID                    pgtype.UUID
	TherapistID           pgtype.UUID
	PatientFileID         pgtype.UUID
	AudioUploadID         pgtype.UUID
	SessionDate           pgtype.Date
	SessionNumber         int32
	DurationSeconds       *int32
	ContactForm           ContactForm
	SpeakerLabelMapping   []byte
	LanguageCode          *string
	TherapistObservations *string
	IsConsentConfirmed    bool
	Status                SessionStatus
	StatusUpdatedAt       pgtype.Timestamptz
	ErrorMessage          *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
}

type TherapistPatientRelation struct {
	ID           pgtype.UUID
	TherapistID  pgtype.UUID
	PatientID    pgtype.UUID
	Status       RelationStatus
	InvitedAt    pgtype.Timestamptz
	ActivatedAt  pgtype.Timestamptz
	TerminatedAt pgtype.Timestamptz
}

type Transcript struct {
	ID                     pgtype.UUID
	SessionID              pgtype.UUID
	TranscriptCiphertext   []byte
	TranscriptEncryptedDek []byte
	LanguageCode           string
	WordCount              *int32
	SpeakerCount           *int32
	ConfidenceAvg          pgtype.Numeric
	SttModel               string
	SttProcessedAt         pgtype.Timestamptz
	SttProcessingSeconds   *int32
	BlobRebuiltAt          pgtype.Timestamptz
	BlobRebuildCount       int32
	CreatedAt              pgtype.Timestamptz
}

type TranscriptSegment struct {
	ID               pgtype.UUID
	TranscriptID     pgtype.UUID
	SpeakerTag       int32
	SpeakerLabel     string
	StartOffsetMs    int32
	EndOffsetMs      int32
	TextCiphertext   []byte
	TextEncryptedDek []byte
	TextWordCount    *int32
	Confidence       pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID                  pgtype.UUID
	Role                UserRole
	OrganizationID      pgtype.UUID
	DefaultModalityID   pgtype.UUID
	BillingAddressID    pgtype.UUID
	FirebaseUid         string
	Email               string
	PhoneNumber         *string
	IsEmailVerified     bool
	FirstName           string
	LastName            string
	ProfessionalTitle   *string
	CredentialsNumber   *string
	Biography           *string
	AvatarUrl           *string
	UiLanguage          string
	Timezone            string
	HasAcceptedTos      bool
	HasMarketingConsent bool
	CreatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
}
