// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient_files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPatientFileTherapist = `-- name: GetPatientFileTherapist :one
SELECT therapist_id
FROM patient_files
WHERE id = $1
`

// Ownership lookup for the ingestion auth guard (SECURITY #1).
// CreateAudioUpload derives the therapist from the validated Firebase
// token and must reject a caller who passes another therapist's
// patient_file_id. A soft-deleted file (deleted_at IS NOT NULL) still
// returns its owner — so "deleted" can't be used to bypass the check.
func (q *Queries) GetPatientFileTherapist(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPatientFileTherapist, id)
	var therapist_id pgtype.UUID
	err := row.Scan(&therapist_id)
	return therapist_id, err
}
