// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    therapist_id, patient_file_id, audio_upload_id,
    session_date, session_number, duration_seconds, contact_form
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, therapist_id, patient_file_id, audio_upload_id, session_date, session_number, duration_seconds, contact_form, speaker_label_mapping, language_code, therapist_observations, is_consent_confirmed, status, status_updated_at, error_message, created_at, updated_at, deleted_at
`

type CreateSessionParams struct {
	TherapistID     pgtype.UUID
	PatientFileID   pgtype.UUID
	AudioUploadID   pgtype.UUID
	SessionDate     pgtype.Date
	SessionNumber   int32
	DurationSeconds *int32
	ContactForm     ContactForm
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TherapistID,
		arg.PatientFileID,
		arg.AudioUploadID,
		arg.SessionDate,
		arg.SessionNumber,
		arg.DurationSeconds,
		arg.ContactForm,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.AudioUploadID,
		&i.SessionDate,
		&i.SessionNumber,
		&i.DurationSeconds,
		&i.ContactForm,
		&i.SpeakerLabelMapping,
		&i.LanguageCode,
		&i.TherapistObservations,
		&i.IsConsentConfirmed,
		&i.Status,
		&i.StatusUpdatedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNextSessionNumber = `-- name: GetNextSessionNumber :one
SELECT COALESCE(MAX(session_number), 0) + 1 AS next_number
FROM sessions
WHERE patient_file_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNextSessionNumber(ctx context.Context, patientFileID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextSessionNumber, patientFileID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}
