// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserOrganizationID = `-- name: GetUserOrganizationID :one
SELECT organization_id
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

// Resolves users.organization_id for a therapist — used by ingestion-svc
// post-commit to populate the org_id field on billing-svc.ReserveCredit
// (which requires both therapist + organization to scope quota correctly).
//
// Returns NULL via pgtype.UUID when the user isn't bound to an org yet
// (rare today after slice 4 bootstrap, but handled defensively in the
// caller — no reservation attempted in that case).
func (q *Queries) GetUserOrganizationID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserOrganizationID, id)
	var organization_id pgtype.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}
