// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_panel.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clientGetSharedSession = `-- name: ClientGetSharedSession :one
SELECT s.id, s.patient_file_id, s.session_date, s.session_number,
       s.duration_seconds, s.shared_with_client_at, s.deleted_at,
       pf.patient_id
FROM sessions s
JOIN patient_files pf ON pf.id = s.patient_file_id
WHERE s.id = $1 AND s.deleted_at IS NULL
`

type ClientGetSharedSessionRow struct {
	ID                 uuid.UUID          `json:"id"`
	PatientFileID      uuid.UUID          `json:"patient_file_id"`
	SessionDate        pgtype.Date        `json:"session_date"`
	SessionNumber      int32              `json:"session_number"`
	DurationSeconds    *int32             `json:"duration_seconds"`
	SharedWithClientAt pgtype.Timestamptz `json:"shared_with_client_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	PatientID          pgtype.UUID        `json:"patient_id"`
}

// Session + owning kartoteka's patient for the transcript authz:
// the handler checks patient_id == caller AND shared marker.
func (q *Queries) ClientGetSharedSession(ctx context.Context, id uuid.UUID) (ClientGetSharedSessionRow, error) {
	row := q.db.QueryRow(ctx, clientGetSharedSession, id)
	var i ClientGetSharedSessionRow
	err := row.Scan(
		&i.ID,
		&i.PatientFileID,
		&i.SessionDate,
		&i.SessionNumber,
		&i.DurationSeconds,
		&i.SharedWithClientAt,
		&i.DeletedAt,
		&i.PatientID,
	)
	return i, err
}

const clientListKartoteki = `-- name: ClientListKartoteki :many

SELECT
    pf.id AS patient_file_id,
    (t.first_name || ' ' || t.last_name)::text AS therapist_name,
    COALESCE(o.legal_name, '')::text AS organization_name,
    (SELECT COUNT(*) FROM sessions s
      WHERE s.patient_file_id = pf.id AND s.deleted_at IS NULL
        AND s.shared_with_client_at IS NOT NULL
        AND s.client_hidden_at IS NULL)::int AS shared_sessions,
    (SELECT COUNT(*) FROM patient_notes n
      WHERE n.patient_file_id = pf.id AND n.deleted_at IS NULL
        AND n.kind <> 'CLIENT_NOTE'
        AND n.shared_with_client_at IS NOT NULL
        AND n.client_hidden_at IS NULL)::int AS shared_notes,
    (SELECT COUNT(*) FROM patient_notes n
      WHERE n.patient_file_id = pf.id AND n.deleted_at IS NULL
        AND n.kind <> 'CLIENT_NOTE'
        AND n.shared_with_client_at IS NOT NULL
        AND n.client_hidden_at IS NULL
        AND n.read_by_client_at IS NULL)::int AS unread_notes
FROM patient_files pf
JOIN users t ON t.id = pf.therapist_id
LEFT JOIN organizations o ON o.id = t.organization_id
WHERE pf.patient_id = $1 AND pf.deleted_at IS NULL
ORDER BY pf.created_at ASC
`

type ClientListKartotekiRow struct {
	PatientFileID    uuid.UUID `json:"patient_file_id"`
	TherapistName    string    `json:"therapist_name"`
	OrganizationName string    `json:"organization_name"`
	SharedSessions   int32     `json:"shared_sessions"`
	SharedNotes      int32     `json:"shared_notes"`
	UnreadNotes      int32     `json:"unread_notes"`
}

// Client (patient) panel — docs/39. Every read is scoped by the
// caller's patient_id (requireClientFileAccess) and, for therapist
// content, by the explicit sharing markers (D2). No reports, no
// therapist-private notes.
// The client's kartoteki with per-file counters for the overview.
func (q *Queries) ClientListKartoteki(ctx context.Context, patientID pgtype.UUID) ([]ClientListKartotekiRow, error) {
	rows, err := q.db.Query(ctx, clientListKartoteki, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientListKartotekiRow
	for rows.Next() {
		var i ClientListKartotekiRow
		if err := rows.Scan(
			&i.PatientFileID,
			&i.TherapistName,
			&i.OrganizationName,
			&i.SharedSessions,
			&i.SharedNotes,
			&i.UnreadNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clientListSharedSessions = `-- name: ClientListSharedSessions :many
SELECT s.id, s.session_date, s.session_number, s.duration_seconds,
       s.shared_with_client_at,
       EXISTS(SELECT 1 FROM transcripts tr WHERE tr.session_id = s.id) AS has_transcript
FROM sessions s
WHERE s.patient_file_id = $1
  AND s.deleted_at IS NULL
  AND s.shared_with_client_at IS NOT NULL
  AND s.client_hidden_at IS NULL
ORDER BY s.session_date DESC, s.session_number DESC
`

type ClientListSharedSessionsRow struct {
	ID                 uuid.UUID          `json:"id"`
	SessionDate        pgtype.Date        `json:"session_date"`
	SessionNumber      int32              `json:"session_number"`
	DurationSeconds    *int32             `json:"duration_seconds"`
	SharedWithClientAt pgtype.Timestamptz `json:"shared_with_client_at"`
	HasTranscript      bool               `json:"has_transcript"`
}

func (q *Queries) ClientListSharedSessions(ctx context.Context, patientFileID uuid.UUID) ([]ClientListSharedSessionsRow, error) {
	rows, err := q.db.Query(ctx, clientListSharedSessions, patientFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientListSharedSessionsRow
	for rows.Next() {
		var i ClientListSharedSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionDate,
			&i.SessionNumber,
			&i.DurationSeconds,
			&i.SharedWithClientAt,
			&i.HasTranscript,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clientListVisibleNotes = `-- name: ClientListVisibleNotes :many
SELECT id, patient_file_id, therapist_id, kind, source_session_id, title_ciphertext, title_encrypted_dek, text_ciphertext, text_encrypted_dek, sent_to_patient_at, sent_to_email, created_at, updated_at, deleted_at, shared_with_client_at, author_role, read_by_therapist_at, read_by_client_at, sent_to_therapist_at, client_hidden_at FROM patient_notes
WHERE patient_file_id = $1
  AND deleted_at IS NULL
  AND client_hidden_at IS NULL
  AND (shared_with_client_at IS NOT NULL OR kind = 'CLIENT_NOTE')
ORDER BY created_at DESC
`

// Therapist notes shared with the client + the client's own notes.
// Excludes items the client dismissed from their panel (client_hidden_at);
// a client's own CLIENT_NOTE is never hidden (they hard-delete instead).
func (q *Queries) ClientListVisibleNotes(ctx context.Context, patientFileID uuid.UUID) ([]PatientNote, error) {
	rows, err := q.db.Query(ctx, clientListVisibleNotes, patientFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientNote
	for rows.Next() {
		var i PatientNote
		if err := rows.Scan(
			&i.ID,
			&i.PatientFileID,
			&i.TherapistID,
			&i.Kind,
			&i.SourceSessionID,
			&i.TitleCiphertext,
			&i.TitleEncryptedDek,
			&i.TextCiphertext,
			&i.TextEncryptedDek,
			&i.SentToPatientAt,
			&i.SentToEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SharedWithClientAt,
			&i.AuthorRole,
			&i.ReadByTherapistAt,
			&i.ReadByClientAt,
			&i.SentToTherapistAt,
			&i.ClientHiddenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnreadClientNotesForKartoteka = `-- name: CountUnreadClientNotesForKartoteka :one
SELECT COUNT(*)::int FROM patient_notes
WHERE patient_file_id = $1 AND kind = 'CLIENT_NOTE'
  AND sent_to_therapist_at IS NOT NULL
  AND read_by_therapist_at IS NULL AND deleted_at IS NULL
`

// Therapist-side badge.
func (q *Queries) CountUnreadClientNotesForKartoteka(ctx context.Context, patientFileID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadClientNotesForKartoteka, patientFileID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createClientNote = `-- name: CreateClientNote :one
INSERT INTO patient_notes (
    patient_file_id, therapist_id, kind, author_role,
    title_ciphertext, title_encrypted_dek, text_ciphertext, text_encrypted_dek,
    sent_to_therapist_at
) VALUES ($1, $2, 'CLIENT_NOTE', 'PATIENT', $3, $4, $5, $6,
    CASE WHEN $7::bool THEN now() ELSE NULL END)
RETURNING id, patient_file_id, therapist_id, kind, source_session_id, title_ciphertext, title_encrypted_dek, text_ciphertext, text_encrypted_dek, sent_to_patient_at, sent_to_email, created_at, updated_at, deleted_at, shared_with_client_at, author_role, read_by_therapist_at, read_by_client_at, sent_to_therapist_at, client_hidden_at
`

type CreateClientNoteParams struct {
	PatientFileID     uuid.UUID `json:"patient_file_id"`
	TherapistID       uuid.UUID `json:"therapist_id"`
	TitleCiphertext   []byte    `json:"title_ciphertext"`
	TitleEncryptedDek []byte    `json:"title_encrypted_dek"`
	TextCiphertext    []byte    `json:"text_ciphertext"`
	TextEncryptedDek  []byte    `json:"text_encrypted_dek"`
	Column7           bool      `json:"column_7"`
}

// kind=CLIENT_NOTE, author_role=PATIENT (chk_patient_notes_author).
// therapist_id is the counterparty (kartoteka owner). $7=true stamps
// sent_to_therapist_at (deliver on create); false saves a PRIVATE
// draft the therapist can't see (000068).
func (q *Queries) CreateClientNote(ctx context.Context, arg CreateClientNoteParams) (PatientNote, error) {
	row := q.db.QueryRow(ctx, createClientNote,
		arg.PatientFileID,
		arg.TherapistID,
		arg.TitleCiphertext,
		arg.TitleEncryptedDek,
		arg.TextCiphertext,
		arg.TextEncryptedDek,
		arg.Column7,
	)
	var i PatientNote
	err := row.Scan(
		&i.ID,
		&i.PatientFileID,
		&i.TherapistID,
		&i.Kind,
		&i.SourceSessionID,
		&i.TitleCiphertext,
		&i.TitleEncryptedDek,
		&i.TextCiphertext,
		&i.TextEncryptedDek,
		&i.SentToPatientAt,
		&i.SentToEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SharedWithClientAt,
		&i.AuthorRole,
		&i.ReadByTherapistAt,
		&i.ReadByClientAt,
		&i.SentToTherapistAt,
		&i.ClientHiddenAt,
	)
	return i, err
}

const getClientNoteForDelete = `-- name: GetClientNoteForDelete :one
SELECT id, patient_file_id, kind, author_role
FROM patient_notes
WHERE id = $1 AND deleted_at IS NULL
`

type GetClientNoteForDeleteRow struct {
	ID            uuid.UUID `json:"id"`
	PatientFileID uuid.UUID `json:"patient_file_id"`
	Kind          string    `json:"kind"`
	AuthorRole    UserRole  `json:"author_role"`
}

// docs/39 PR13: fetch a note for the hard-delete authz check. Handler
// verifies patient_file_id belongs to the caller and kind = CLIENT_NOTE.
func (q *Queries) GetClientNoteForDelete(ctx context.Context, id uuid.UUID) (GetClientNoteForDeleteRow, error) {
	row := q.db.QueryRow(ctx, getClientNoteForDelete, id)
	var i GetClientNoteForDeleteRow
	err := row.Scan(
		&i.ID,
		&i.PatientFileID,
		&i.Kind,
		&i.AuthorRole,
	)
	return i, err
}

const getPatientUserEmailForFile = `-- name: GetPatientUserEmailForFile :one
SELECT u.id AS patient_id, u.email, u.ui_language
FROM patient_files pf
JOIN users u ON u.id = pf.patient_id
WHERE pf.id = $1 AND u.is_active AND u.email IS NOT NULL
`

type GetPatientUserEmailForFileRow struct {
	PatientID  uuid.UUID `json:"patient_id"`
	Email      *string   `json:"email"`
	UiLanguage string    `json:"ui_language"`
}

// docs/39 PR9: the client-panel account e-mail for a kartoteka. Only an
// attached, ACTIVE patient user with an e-mail can receive the PHI-free
// "new item in your panel" signal — pseudonymous kartoteki skip it.
// PR12 also returns the client's users.id so the ITEM_SHARED event can
// address the recipient's Firestore inbox for live web-panel refresh.
func (q *Queries) GetPatientUserEmailForFile(ctx context.Context, id uuid.UUID) (GetPatientUserEmailForFileRow, error) {
	row := q.db.QueryRow(ctx, getPatientUserEmailForFile, id)
	var i GetPatientUserEmailForFileRow
	err := row.Scan(&i.PatientID, &i.Email, &i.UiLanguage)
	return i, err
}

const getUserEmailForNotify = `-- name: GetUserEmailForNotify :one
SELECT email, ui_language FROM users
WHERE id = $1 AND is_active AND email IS NOT NULL
`

type GetUserEmailForNotifyRow struct {
	Email      *string `json:"email"`
	UiLanguage string  `json:"ui_language"`
}

// docs/39 PR9: therapist recipient for client_note_received.
func (q *Queries) GetUserEmailForNotify(ctx context.Context, id uuid.UUID) (GetUserEmailForNotifyRow, error) {
	row := q.db.QueryRow(ctx, getUserEmailForNotify, id)
	var i GetUserEmailForNotifyRow
	err := row.Scan(&i.Email, &i.UiLanguage)
	return i, err
}

const hardDeleteClientNote = `-- name: HardDeleteClientNote :execrows
DELETE FROM patient_notes
WHERE id = $1 AND kind = 'CLIENT_NOTE'
`

// docs/39 PR13: the client removes their OWN note everywhere (including
// from the therapist if it was sent). Guarded to CLIENT_NOTE so a therapist
// note can never be destroyed through this path. Returns rows affected so
// the handler can 404 on a no-op.
func (q *Queries) HardDeleteClientNote(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteClientNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hideNoteFromClient = `-- name: HideNoteFromClient :execrows
UPDATE patient_notes
SET client_hidden_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
  AND kind <> 'CLIENT_NOTE'
  AND shared_with_client_at IS NOT NULL
  AND client_hidden_at IS NULL
`

// docs/39 PR13: dismiss a shared THERAPIST note from the client's panel
// only. kind <> CLIENT_NOTE so a client's own note can't be hidden (they
// hard-delete instead).
func (q *Queries) HideNoteFromClient(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hideNoteFromClient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hideSessionFromClient = `-- name: HideSessionFromClient :execrows
UPDATE sessions
SET client_hidden_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
  AND shared_with_client_at IS NOT NULL
  AND client_hidden_at IS NULL
`

// docs/39 PR13: dismiss a shared session from the client's panel only.
func (q *Queries) HideSessionFromClient(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hideSessionFromClient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markClientNoteSentToTherapist = `-- name: MarkClientNoteSentToTherapist :one
UPDATE patient_notes
SET sent_to_therapist_at = COALESCE(sent_to_therapist_at, now()),
    updated_at = now()
WHERE id = $1 AND kind = 'CLIENT_NOTE' AND deleted_at IS NULL
RETURNING id, patient_file_id, therapist_id, kind, source_session_id, title_ciphertext, title_encrypted_dek, text_ciphertext, text_encrypted_dek, sent_to_patient_at, sent_to_email, created_at, updated_at, deleted_at, shared_with_client_at, author_role, read_by_therapist_at, read_by_client_at, sent_to_therapist_at, client_hidden_at
`

// Deliver a saved draft. Idempotent — a delivered note keeps its
// first timestamp.
func (q *Queries) MarkClientNoteSentToTherapist(ctx context.Context, id uuid.UUID) (PatientNote, error) {
	row := q.db.QueryRow(ctx, markClientNoteSentToTherapist, id)
	var i PatientNote
	err := row.Scan(
		&i.ID,
		&i.PatientFileID,
		&i.TherapistID,
		&i.Kind,
		&i.SourceSessionID,
		&i.TitleCiphertext,
		&i.TitleEncryptedDek,
		&i.TextCiphertext,
		&i.TextEncryptedDek,
		&i.SentToPatientAt,
		&i.SentToEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SharedWithClientAt,
		&i.AuthorRole,
		&i.ReadByTherapistAt,
		&i.ReadByClientAt,
		&i.SentToTherapistAt,
		&i.ClientHiddenAt,
	)
	return i, err
}

const markKartotekaClientNotesReadByTherapist = `-- name: MarkKartotekaClientNotesReadByTherapist :exec
UPDATE patient_notes SET read_by_therapist_at = now()
WHERE patient_file_id = $1 AND kind = 'CLIENT_NOTE'
  AND sent_to_therapist_at IS NOT NULL
  AND read_by_therapist_at IS NULL AND deleted_at IS NULL
`

// Auto-mark when the therapist opens the kartoteka notes list — the
// badge is edge-triggered, not an inbox.
func (q *Queries) MarkKartotekaClientNotesReadByTherapist(ctx context.Context, patientFileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markKartotekaClientNotesReadByTherapist, patientFileID)
	return err
}

const markNoteReadByClient = `-- name: MarkNoteReadByClient :exec
UPDATE patient_notes SET read_by_client_at = now()
WHERE id = $1 AND read_by_client_at IS NULL
`

func (q *Queries) MarkNoteReadByClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNoteReadByClient, id)
	return err
}

const setNoteSharedWithClient = `-- name: SetNoteSharedWithClient :one
UPDATE patient_notes
SET shared_with_client_at = CASE
      WHEN $2::bool THEN COALESCE(shared_with_client_at, now())
      ELSE NULL END,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL AND kind <> 'CLIENT_NOTE'
RETURNING id, shared_with_client_at
`

type SetNoteSharedWithClientParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 bool      `json:"column_2"`
}

type SetNoteSharedWithClientRow struct {
	ID                 uuid.UUID          `json:"id"`
	SharedWithClientAt pgtype.Timestamptz `json:"shared_with_client_at"`
}

func (q *Queries) SetNoteSharedWithClient(ctx context.Context, arg SetNoteSharedWithClientParams) (SetNoteSharedWithClientRow, error) {
	row := q.db.QueryRow(ctx, setNoteSharedWithClient, arg.ID, arg.Column2)
	var i SetNoteSharedWithClientRow
	err := row.Scan(&i.ID, &i.SharedWithClientAt)
	return i, err
}

const setSessionSharedWithClient = `-- name: SetSessionSharedWithClient :one
UPDATE sessions
SET shared_with_client_at = CASE
      WHEN $2::bool THEN COALESCE(shared_with_client_at, now())
      ELSE NULL END,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, shared_with_client_at
`

type SetSessionSharedWithClientParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 bool      `json:"column_2"`
}

type SetSessionSharedWithClientRow struct {
	ID                 uuid.UUID          `json:"id"`
	SharedWithClientAt pgtype.Timestamptz `json:"shared_with_client_at"`
}

// shared=true stamps now() once (idempotent); false clears.
func (q *Queries) SetSessionSharedWithClient(ctx context.Context, arg SetSessionSharedWithClientParams) (SetSessionSharedWithClientRow, error) {
	row := q.db.QueryRow(ctx, setSessionSharedWithClient, arg.ID, arg.Column2)
	var i SetSessionSharedWithClientRow
	err := row.Scan(&i.ID, &i.SharedWithClientAt)
	return i, err
}
