// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dsar.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPatientNotesForExport = `-- name: GetPatientNotesForExport :many
SELECT id, patient_file_id, therapist_id, kind, source_session_id, title_ciphertext, title_encrypted_dek, text_ciphertext, text_encrypted_dek, sent_to_patient_at, sent_to_email, created_at, updated_at, deleted_at FROM patient_notes
WHERE patient_file_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetPatientNotesForExport(ctx context.Context, patientFileID uuid.UUID) ([]PatientNote, error) {
	rows, err := q.db.Query(ctx, getPatientNotesForExport, patientFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientNote
	for rows.Next() {
		var i PatientNote
		if err := rows.Scan(
			&i.ID,
			&i.PatientFileID,
			&i.TherapistID,
			&i.Kind,
			&i.SourceSessionID,
			&i.TitleCiphertext,
			&i.TitleEncryptedDek,
			&i.TextCiphertext,
			&i.TextEncryptedDek,
			&i.SentToPatientAt,
			&i.SentToEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsForExport = `-- name: GetSessionsForExport :many
SELECT id, therapist_id, patient_file_id, audio_upload_id, session_date, session_number, duration_seconds, contact_form, speaker_label_mapping, language_code, therapist_observations, is_consent_confirmed, status, status_updated_at, error_message, created_at, updated_at, deleted_at, report_language, name, report_viewed_at FROM sessions
WHERE patient_file_id = $1 AND deleted_at IS NULL
ORDER BY session_number ASC
`

func (q *Queries) GetSessionsForExport(ctx context.Context, patientFileID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsForExport, patientFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TherapistID,
			&i.PatientFileID,
			&i.AudioUploadID,
			&i.SessionDate,
			&i.SessionNumber,
			&i.DurationSeconds,
			&i.ContactForm,
			&i.SpeakerLabelMapping,
			&i.LanguageCode,
			&i.TherapistObservations,
			&i.IsConsentConfirmed,
			&i.Status,
			&i.StatusUpdatedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ReportLanguage,
			&i.Name,
			&i.ReportViewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePatientFileForDSAR = `-- name: SoftDeletePatientFileForDSAR :execrows
UPDATE patient_files
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND therapist_id = $2 AND deleted_at IS NULL
`

type SoftDeletePatientFileForDSARParams struct {
	ID          uuid.UUID `json:"id"`
	TherapistID uuid.UUID `json:"therapist_id"`
}

func (q *Queries) SoftDeletePatientFileForDSAR(ctx context.Context, arg SoftDeletePatientFileForDSARParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePatientFileForDSAR, arg.ID, arg.TherapistID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeletePatientNotesForDSAR = `-- name: SoftDeletePatientNotesForDSAR :exec
UPDATE patient_notes
SET deleted_at = now(), updated_at = now()
WHERE patient_file_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePatientNotesForDSAR(ctx context.Context, patientFileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePatientNotesForDSAR, patientFileID)
	return err
}

const softDeletePatientUserForDSAR = `-- name: SoftDeletePatientUserForDSAR :execrows
UPDATE users
SET deleted_at = now()
WHERE id = $1 AND role = 'PATIENT' AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePatientUserForDSAR(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePatientUserForDSAR, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteSessionsForDSAR = `-- name: SoftDeleteSessionsForDSAR :exec
UPDATE sessions
SET deleted_at = now(), updated_at = now()
WHERE patient_file_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSessionsForDSAR(ctx context.Context, patientFileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSessionsForDSAR, patientFileID)
	return err
}
