// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixed_costs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformFixedCosts = `-- name: GetPlatformFixedCosts :many
SELECT id, name, provider, amount_usd::float AS amount_usd, billing_period, created_at
FROM platform_fixed_costs
ORDER BY provider ASC, amount_usd DESC
`

type GetPlatformFixedCostsRow struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Provider      string             `json:"provider"`
	AmountUsd     float64            `json:"amount_usd"`
	BillingPeriod string             `json:"billing_period"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// CROSS-SERVICE READ: analytics-only
func (q *Queries) GetPlatformFixedCosts(ctx context.Context) ([]GetPlatformFixedCostsRow, error) {
	rows, err := q.db.Query(ctx, getPlatformFixedCosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlatformFixedCostsRow
	for rows.Next() {
		var i GetPlatformFixedCostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.AmountUsd,
			&i.BillingPeriod,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
