// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTranscriptForRebuild = `-- name: GetTranscriptForRebuild :one
SELECT t.id AS transcript_id, t.session_id, t.language_code
FROM transcripts t
WHERE t.session_id = $1
ORDER BY t.created_at DESC
LIMIT 1
`

type GetTranscriptForRebuildRow struct {
	TranscriptID uuid.UUID `json:"transcript_id"`
	SessionID    uuid.UUID `json:"session_id"`
	LanguageCode string    `json:"language_code"`
}

func (q *Queries) GetTranscriptForRebuild(ctx context.Context, sessionID uuid.UUID) (GetTranscriptForRebuildRow, error) {
	row := q.db.QueryRow(ctx, getTranscriptForRebuild, sessionID)
	var i GetTranscriptForRebuildRow
	err := row.Scan(&i.TranscriptID, &i.SessionID, &i.LanguageCode)
	return i, err
}

const listSegmentsForRebuild = `-- name: ListSegmentsForRebuild :many
SELECT speaker_tag, text_ciphertext, text_encrypted_dek,
       start_offset_ms, end_offset_ms, confidence
FROM transcript_segments
WHERE transcript_id = $1
ORDER BY start_offset_ms
`

type ListSegmentsForRebuildRow struct {
	SpeakerTag       int32          `json:"speaker_tag"`
	TextCiphertext   []byte         `json:"text_ciphertext"`
	TextEncryptedDek []byte         `json:"text_encrypted_dek"`
	StartOffsetMs    int32          `json:"start_offset_ms"`
	EndOffsetMs      int32          `json:"end_offset_ms"`
	Confidence       pgtype.Numeric `json:"confidence"`
}

func (q *Queries) ListSegmentsForRebuild(ctx context.Context, transcriptID uuid.UUID) ([]ListSegmentsForRebuildRow, error) {
	rows, err := q.db.Query(ctx, listSegmentsForRebuild, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSegmentsForRebuildRow
	for rows.Next() {
		var i ListSegmentsForRebuildRow
		if err := rows.Scan(
			&i.SpeakerTag,
			&i.TextCiphertext,
			&i.TextEncryptedDek,
			&i.StartOffsetMs,
			&i.EndOffsetMs,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSegmentLabel = `-- name: UpdateSegmentLabel :exec
UPDATE transcript_segments SET speaker_label = $3
WHERE transcript_id = $1 AND speaker_tag = $2
`

type UpdateSegmentLabelParams struct {
	TranscriptID uuid.UUID `json:"transcript_id"`
	SpeakerTag   int32     `json:"speaker_tag"`
	SpeakerLabel string    `json:"speaker_label"`
}

func (q *Queries) UpdateSegmentLabel(ctx context.Context, arg UpdateSegmentLabelParams) error {
	_, err := q.db.Exec(ctx, updateSegmentLabel, arg.TranscriptID, arg.SpeakerTag, arg.SpeakerLabel)
	return err
}

const updateSessionLabelMapping = `-- name: UpdateSessionLabelMapping :exec
UPDATE sessions SET speaker_label_mapping = $2
WHERE id = $1
`

type UpdateSessionLabelMappingParams struct {
	ID                  uuid.UUID `json:"id"`
	SpeakerLabelMapping []byte    `json:"speaker_label_mapping"`
}

func (q *Queries) UpdateSessionLabelMapping(ctx context.Context, arg UpdateSessionLabelMappingParams) error {
	_, err := q.db.Exec(ctx, updateSessionLabelMapping, arg.ID, arg.SpeakerLabelMapping)
	return err
}

const updateTranscriptBlob = `-- name: UpdateTranscriptBlob :exec
UPDATE transcripts SET
    transcript_ciphertext = $2,
    transcript_encrypted_dek = $3,
    blob_rebuilt_at = now(),
    blob_rebuild_count = blob_rebuild_count + 1
WHERE id = $1
`

type UpdateTranscriptBlobParams struct {
	ID                     uuid.UUID `json:"id"`
	TranscriptCiphertext   []byte    `json:"transcript_ciphertext"`
	TranscriptEncryptedDek []byte    `json:"transcript_encrypted_dek"`
}

func (q *Queries) UpdateTranscriptBlob(ctx context.Context, arg UpdateTranscriptBlobParams) error {
	_, err := q.db.Exec(ctx, updateTranscriptBlob, arg.ID, arg.TranscriptCiphertext, arg.TranscriptEncryptedDek)
	return err
}
