// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: modalities.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getModalityByCode = `-- name: GetModalityByCode :one
SELECT id, system_code, display_name, is_supported, modality_type
FROM modalities
WHERE system_code = $1 AND is_supported = TRUE
`

type GetModalityByCodeRow struct {
	ID           uuid.UUID    `json:"id"`
	SystemCode   string       `json:"system_code"`
	DisplayName  string       `json:"display_name"`
	IsSupported  bool         `json:"is_supported"`
	ModalityType ModalityType `json:"modality_type"`
}

func (q *Queries) GetModalityByCode(ctx context.Context, systemCode string) (GetModalityByCodeRow, error) {
	row := q.db.QueryRow(ctx, getModalityByCode, systemCode)
	var i GetModalityByCodeRow
	err := row.Scan(
		&i.ID,
		&i.SystemCode,
		&i.DisplayName,
		&i.IsSupported,
		&i.ModalityType,
	)
	return i, err
}

const listSupportedModalities = `-- name: ListSupportedModalities :many
SELECT id, system_code, display_name, is_supported, modality_type
FROM modalities
WHERE is_supported = TRUE
ORDER BY display_name
`

type ListSupportedModalitiesRow struct {
	ID           uuid.UUID    `json:"id"`
	SystemCode   string       `json:"system_code"`
	DisplayName  string       `json:"display_name"`
	IsSupported  bool         `json:"is_supported"`
	ModalityType ModalityType `json:"modality_type"`
}

func (q *Queries) ListSupportedModalities(ctx context.Context) ([]ListSupportedModalitiesRow, error) {
	rows, err := q.db.Query(ctx, listSupportedModalities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupportedModalitiesRow
	for rows.Next() {
		var i ListSupportedModalitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.SystemCode,
			&i.DisplayName,
			&i.IsSupported,
			&i.ModalityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
