// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_analytics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrgTherapistMetrics = `-- name: GetOrgTherapistMetrics :many

SELECT
    u.id AS therapist_id,
    u.first_name,
    u.last_name,
    u.is_active,
    COUNT(s.id) FILTER (WHERE s.status = 'COMPLETED')::int AS sessions_completed,
    COUNT(s.id) FILTER (WHERE s.status = 'FAILED')::int AS sessions_failed,
    COUNT(s.id) FILTER (WHERE s.status IN ('CANCELED', 'CANCELLED_BY_USER'))::int AS sessions_cancelled,
    COALESCE(SUM(s.duration_seconds) FILTER (WHERE s.status = 'COMPLETED'), 0)::bigint AS total_duration_seconds,
    COUNT(s.id) FILTER (WHERE s.status = 'COMPLETED' AND s.report_viewed_at IS NOT NULL)::int AS sessions_report_viewed,
    MAX(s.session_date)::date AS last_session_date,
    (SELECT COUNT(*) FROM patient_files pf
      WHERE pf.therapist_id = u.id AND pf.deleted_at IS NULL
        AND pf.is_process_closed = FALSE)::int AS active_patients,
    (SELECT COUNT(*) FROM patient_files pf
      WHERE pf.therapist_id = u.id AND pf.deleted_at IS NULL
        AND pf.created_at >= $2)::int AS new_patients,
    (SELECT COUNT(*) FROM report_ratings rr
      WHERE rr.therapist_id = u.id AND rr.rating = 'positive'
        AND rr.created_at >= $2)::int AS ratings_positive,
    (SELECT COUNT(*) FROM report_ratings rr
      WHERE rr.therapist_id = u.id AND rr.rating = 'negative'
        AND rr.created_at >= $2)::int AS ratings_negative
FROM users u
LEFT JOIN sessions s
       ON s.therapist_id = u.id
      AND s.deleted_at IS NULL
      AND s.created_at >= $2
WHERE u.organization_id = $1
  AND u.deleted_at IS NULL
  -- Menedżer, który sam przyjmuje pacjentów (SetManagerTherapistSeat),
  -- prowadzi sesje jak każdy inny praktyk — jego prawem do praktykowania
  -- jest MIEJSCE w planie, nie rola. Filtr wyłącznie po roli ukrywałby
  -- jego sesje w statystykach organizacji, mimo że liczą się do limitu.
  -- ORG_ADMIN bez miejsca zostaje poza zestawieniem: nie praktykuje.
  AND (
        u.role = 'THERAPIST'
     OR (u.role = 'ORG_ADMIN' AND EXISTS (
            SELECT 1 FROM seat_assignments sa
            WHERE sa.user_id = u.id AND sa.unassigned_at IS NULL))
  )
GROUP BY u.id, u.first_name, u.last_name, u.is_active
ORDER BY u.last_name, u.first_name
`

type GetOrgTherapistMetricsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	CreatedAt      time.Time   `json:"created_at"`
}

type GetOrgTherapistMetricsRow struct {
	TherapistID          uuid.UUID   `json:"therapist_id"`
	FirstName            string      `json:"first_name"`
	LastName             string      `json:"last_name"`
	IsActive             bool        `json:"is_active"`
	SessionsCompleted    int32       `json:"sessions_completed"`
	SessionsFailed       int32       `json:"sessions_failed"`
	SessionsCancelled    int32       `json:"sessions_cancelled"`
	TotalDurationSeconds int64       `json:"total_duration_seconds"`
	SessionsReportViewed int32       `json:"sessions_report_viewed"`
	LastSessionDate      pgtype.Date `json:"last_session_date"`
	ActivePatients       int32       `json:"active_patients"`
	NewPatients          int32       `json:"new_patients"`
	RatingsPositive      int32       `json:"ratings_positive"`
	RatingsNegative      int32       `json:"ratings_negative"`
}

// Org analytics (docs/38 §7) — per-therapist METADATA aggregates for
// the ORG_ADMIN dashboard. Hard privacy boundary (§7.3): counts,
// durations and dates only. No transcript/report/note content, no
// patient identifiers ever leave this query.
// $1 = organization_id, $2 = window start (timestamptz).
// Sessions / new patients / ratings are windowed; active_patients is
// a point-in-time count of open kartoteki.
func (q *Queries) GetOrgTherapistMetrics(ctx context.Context, arg GetOrgTherapistMetricsParams) ([]GetOrgTherapistMetricsRow, error) {
	rows, err := q.db.Query(ctx, getOrgTherapistMetrics, arg.OrganizationID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrgTherapistMetricsRow
	for rows.Next() {
		var i GetOrgTherapistMetricsRow
		if err := rows.Scan(
			&i.TherapistID,
			&i.FirstName,
			&i.LastName,
			&i.IsActive,
			&i.SessionsCompleted,
			&i.SessionsFailed,
			&i.SessionsCancelled,
			&i.TotalDurationSeconds,
			&i.SessionsReportViewed,
			&i.LastSessionDate,
			&i.ActivePatients,
			&i.NewPatients,
			&i.RatingsPositive,
			&i.RatingsNegative,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgAnalyticsKPIs = `-- name: OrgAnalyticsKPIs :one
SELECT
    (SELECT COUNT(DISTINCT s.therapist_id) FROM sessions s
      JOIN users u ON u.id = s.therapist_id
      WHERE u.organization_id = $1 AND s.deleted_at IS NULL
        AND s.created_at >= now() - interval '7 days')::int AS kpi_wau,
    (SELECT COUNT(*) FROM sessions s
      JOIN users u ON u.id = s.therapist_id
      WHERE u.organization_id = $1 AND s.deleted_at IS NULL
        AND s.created_at >= date_trunc('week', now()))::int AS kpi_sessions_this_week,
    (SELECT COALESCE(AVG(s.duration_seconds) / 60.0, 0) FROM sessions s
      JOIN users u ON u.id = s.therapist_id
      WHERE u.organization_id = $1 AND s.deleted_at IS NULL
        AND s.status = 'COMPLETED' AND s.duration_seconds IS NOT NULL
        AND s.created_at >= now() - interval '90 days')::float8 AS kpi_avg_session_duration,
    (SELECT COUNT(*) FROM sessions s
      JOIN users u ON u.id = s.therapist_id
      WHERE u.organization_id = $1 AND s.deleted_at IS NULL
        AND s.created_at >= date_trunc('month', now()))::int AS sessions_this_month,
    (SELECT COUNT(*) FROM sessions s
      JOIN users u ON u.id = s.therapist_id
      WHERE u.organization_id = $1 AND s.deleted_at IS NULL
        AND s.created_at >= date_trunc('year', now()))::int AS sessions_this_year
`

type OrgAnalyticsKPIsRow struct {
	KpiWau                int32   `json:"kpi_wau"`
	KpiSessionsThisWeek   int32   `json:"kpi_sessions_this_week"`
	KpiAvgSessionDuration float64 `json:"kpi_avg_session_duration"`
	SessionsThisMonth     int32   `json:"sessions_this_month"`
	SessionsThisYear      int32   `json:"sessions_this_year"`
}

// KPI strip + time-saved session counts, one round trip. All scoped to
// the org's therapists; sessions soft-delete-aware.
func (q *Queries) OrgAnalyticsKPIs(ctx context.Context, organizationID pgtype.UUID) (OrgAnalyticsKPIsRow, error) {
	row := q.db.QueryRow(ctx, orgAnalyticsKPIs, organizationID)
	var i OrgAnalyticsKPIsRow
	err := row.Scan(
		&i.KpiWau,
		&i.KpiSessionsThisWeek,
		&i.KpiAvgSessionDuration,
		&i.SessionsThisMonth,
		&i.SessionsThisYear,
	)
	return i, err
}

const orgHourlyHeatmap = `-- name: OrgHourlyHeatmap :many
SELECT
    EXTRACT(dow FROM s.created_at)::int AS day_of_week,
    EXTRACT(hour FROM s.created_at)::int AS hour,
    COUNT(*)::bigint AS count
FROM sessions s
JOIN users u ON u.id = s.therapist_id
WHERE u.organization_id = $1 AND s.deleted_at IS NULL
  AND s.created_at >= now() - interval '90 days'
GROUP BY 1, 2
`

type OrgHourlyHeatmapRow struct {
	DayOfWeek int32 `json:"day_of_week"`
	Hour      int32 `json:"hour"`
	Count     int64 `json:"count"`
}

// Day-of-week × hour recording histogram, last 90 days.
func (q *Queries) OrgHourlyHeatmap(ctx context.Context, organizationID pgtype.UUID) ([]OrgHourlyHeatmapRow, error) {
	rows, err := q.db.Query(ctx, orgHourlyHeatmap, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgHourlyHeatmapRow
	for rows.Next() {
		var i OrgHourlyHeatmapRow
		if err := rows.Scan(&i.DayOfWeek, &i.Hour, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgTherapistUtilization = `-- name: OrgTherapistUtilization :many
SELECT
    (u.first_name || ' ' || u.last_name)::text AS therapist_name,
    to_char(date_trunc('week', c.period_start), 'IYYY-IW') AS week,
    CASE WHEN c.tokens_limit > 0
         THEN ROUND((c.tokens_used::numeric / c.tokens_limit) * 100)
         ELSE 0 END::float8 AS value
FROM usage_counters c
JOIN users u ON u.id = c.therapist_id
JOIN subscriptions sub ON sub.id = c.subscription_id
WHERE sub.organization_id = $1
  AND c.therapist_id IS NOT NULL
  AND c.period_start >= now() - interval '180 days'
ORDER BY therapist_name, week
`

type OrgTherapistUtilizationRow struct {
	TherapistName string  `json:"therapist_name"`
	Week          string  `json:"week"`
	Value         float64 `json:"value"`
}

// Token utilization % per THERAPIST per counter period (docs/38 §7.2)
// — the per-seat mirror of the admin per-org heatmap. Week label =
// ISO week of period_start.
func (q *Queries) OrgTherapistUtilization(ctx context.Context, organizationID uuid.UUID) ([]OrgTherapistUtilizationRow, error) {
	rows, err := q.db.Query(ctx, orgTherapistUtilization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgTherapistUtilizationRow
	for rows.Next() {
		var i OrgTherapistUtilizationRow
		if err := rows.Scan(&i.TherapistName, &i.Week, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgWeeklySessionTrend = `-- name: OrgWeeklySessionTrend :many
SELECT
    to_char(date_trunc('week', s.created_at), 'IYYY-IW') AS week,
    COUNT(*)::int AS sessions,
    COUNT(DISTINCT s.therapist_id)::int AS active_therapists,
    COALESCE(AVG(s.duration_seconds) FILTER (WHERE s.status = 'COMPLETED') / 60.0, 0)::float8 AS avg_duration_min
FROM sessions s
JOIN users u ON u.id = s.therapist_id
WHERE u.organization_id = $1 AND s.deleted_at IS NULL
  AND s.created_at >= date_trunc('week', now()) - interval '8 weeks'
GROUP BY 1
ORDER BY 1
`

type OrgWeeklySessionTrendRow struct {
	Week             string  `json:"week"`
	Sessions         int32   `json:"sessions"`
	ActiveTherapists int32   `json:"active_therapists"`
	AvgDurationMin   float64 `json:"avg_duration_min"`
}

// Sessions per ISO week (last 9 weeks incl. current) + distinct
// therapists + avg completed duration — one scan feeds three charts.
func (q *Queries) OrgWeeklySessionTrend(ctx context.Context, organizationID pgtype.UUID) ([]OrgWeeklySessionTrendRow, error) {
	rows, err := q.db.Query(ctx, orgWeeklySessionTrend, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgWeeklySessionTrendRow
	for rows.Next() {
		var i OrgWeeklySessionTrendRow
		if err := rows.Scan(
			&i.Week,
			&i.Sessions,
			&i.ActiveTherapists,
			&i.AvgDurationMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
