// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient_notes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPatientNote = `-- name: CreatePatientNote :one

INSERT INTO patient_notes (
  patient_file_id, therapist_id, kind, source_session_id,
  title_ciphertext, title_encrypted_dek,
  text_ciphertext, text_encrypted_dek
) VALUES (
  $1, $2, $3, $4,
  $5, $6,
  $7, $8
)
RETURNING id, patient_file_id, therapist_id, kind, source_session_id, title_ciphertext, title_encrypted_dek, text_ciphertext, text_encrypted_dek, sent_to_patient_at, sent_to_email, created_at, updated_at, deleted_at
`

type CreatePatientNoteParams struct {
	PatientFileID     uuid.UUID   `json:"patient_file_id"`
	TherapistID       uuid.UUID   `json:"therapist_id"`
	Kind              string      `json:"kind"`
	SourceSessionID   pgtype.UUID `json:"source_session_id"`
	TitleCiphertext   []byte      `json:"title_ciphertext"`
	TitleEncryptedDek []byte      `json:"title_encrypted_dek"`
	TextCiphertext    []byte      `json:"text_ciphertext"`
	TextEncryptedDek  []byte      `json:"text_encrypted_dek"`
}

// patient_notes — per-patient free-text notes + action plans (docs/22,
// migration 000040). Clinical PHI: title/text are envelope-encrypted at
// the handler layer (cryptobox) and stored as (ciphertext, encrypted_dek)
// BYTEA blobs, same as transcripts/reports. Authz (the note's
// patient_file.therapist_id == ctx user) is enforced in the gRPC handler;
// these queries only filter soft-deleted rows.
// source_session_id is NULL for FREE_NOTE; set to the seeding session for
// an ACTION_PLAN. The four blob columns carry the encrypted title+text.
func (q *Queries) CreatePatientNote(ctx context.Context, arg CreatePatientNoteParams) (PatientNote, error) {
	row := q.db.QueryRow(ctx, createPatientNote,
		arg.PatientFileID,
		arg.TherapistID,
		arg.Kind,
		arg.SourceSessionID,
		arg.TitleCiphertext,
		arg.TitleEncryptedDek,
		arg.TextCiphertext,
		arg.TextEncryptedDek,
	)
	var i PatientNote
	err := row.Scan(
		&i.ID,
		&i.PatientFileID,
		&i.TherapistID,
		&i.Kind,
		&i.SourceSessionID,
		&i.TitleCiphertext,
		&i.TitleEncryptedDek,
		&i.TextCiphertext,
		&i.TextEncryptedDek,
		&i.SentToPatientAt,
		&i.SentToEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPatientNote = `-- name: GetPatientNote :one
SELECT id, patient_file_id, therapist_id, kind, source_session_id, title_ciphertext, title_encrypted_dek, text_ciphertext, text_encrypted_dek, sent_to_patient_at, sent_to_email, created_at, updated_at, deleted_at FROM patient_notes
WHERE id = $1 AND deleted_at IS NULL
`

// Single note for authz + update/delete/send. Soft-deleted rows are
// invisible (treated as 404 by the handler).
func (q *Queries) GetPatientNote(ctx context.Context, id uuid.UUID) (PatientNote, error) {
	row := q.db.QueryRow(ctx, getPatientNote, id)
	var i PatientNote
	err := row.Scan(
		&i.ID,
		&i.PatientFileID,
		&i.TherapistID,
		&i.Kind,
		&i.SourceSessionID,
		&i.TitleCiphertext,
		&i.TitleEncryptedDek,
		&i.TextCiphertext,
		&i.TextEncryptedDek,
		&i.SentToPatientAt,
		&i.SentToEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPatientNotesByFile = `-- name: ListPatientNotesByFile :many
SELECT id, patient_file_id, therapist_id, kind, source_session_id, title_ciphertext, title_encrypted_dek, text_ciphertext, text_encrypted_dek, sent_to_patient_at, sent_to_email, created_at, updated_at, deleted_at FROM patient_notes
WHERE patient_file_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

// All live notes for a kartoteka, newest first. Matches the partial
// index idx_patient_notes_file (patient_file_id, created_at DESC).
func (q *Queries) ListPatientNotesByFile(ctx context.Context, patientFileID uuid.UUID) ([]PatientNote, error) {
	rows, err := q.db.Query(ctx, listPatientNotesByFile, patientFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientNote
	for rows.Next() {
		var i PatientNote
		if err := rows.Scan(
			&i.ID,
			&i.PatientFileID,
			&i.TherapistID,
			&i.Kind,
			&i.SourceSessionID,
			&i.TitleCiphertext,
			&i.TitleEncryptedDek,
			&i.TextCiphertext,
			&i.TextEncryptedDek,
			&i.SentToPatientAt,
			&i.SentToEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPatientNoteSent = `-- name: MarkPatientNoteSent :one
UPDATE patient_notes SET
  sent_to_patient_at = now(),
  sent_to_email      = $2,
  updated_at         = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, patient_file_id, therapist_id, kind, source_session_id, title_ciphertext, title_encrypted_dek, text_ciphertext, text_encrypted_dek, sent_to_patient_at, sent_to_email, created_at, updated_at, deleted_at
`

type MarkPatientNoteSentParams struct {
	ID          uuid.UUID `json:"id"`
	SentToEmail *string   `json:"sent_to_email"`
}

// Stamps the action-plan e-mail send. Called after notification-svc
// confirms delivery. Returns the refreshed row so the handler can
// re-emit the proto with sent_to_patient_at populated.
func (q *Queries) MarkPatientNoteSent(ctx context.Context, arg MarkPatientNoteSentParams) (PatientNote, error) {
	row := q.db.QueryRow(ctx, markPatientNoteSent, arg.ID, arg.SentToEmail)
	var i PatientNote
	err := row.Scan(
		&i.ID,
		&i.PatientFileID,
		&i.TherapistID,
		&i.Kind,
		&i.SourceSessionID,
		&i.TitleCiphertext,
		&i.TitleEncryptedDek,
		&i.TextCiphertext,
		&i.TextEncryptedDek,
		&i.SentToPatientAt,
		&i.SentToEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeletePatientNote = `-- name: SoftDeletePatientNote :exec
UPDATE patient_notes SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Soft delete — keeps the row for audit, hides it from List/Get. (Hard
// erasure happens via the patient_files CASCADE on RODO delete.)
func (q *Queries) SoftDeletePatientNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePatientNote, id)
	return err
}

const updatePatientNote = `-- name: UpdatePatientNote :one
UPDATE patient_notes SET
  title_ciphertext    = $2,
  title_encrypted_dek = $3,
  text_ciphertext     = $4,
  text_encrypted_dek  = $5,
  updated_at          = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, patient_file_id, therapist_id, kind, source_session_id, title_ciphertext, title_encrypted_dek, text_ciphertext, text_encrypted_dek, sent_to_patient_at, sent_to_email, created_at, updated_at, deleted_at
`

type UpdatePatientNoteParams struct {
	ID                uuid.UUID `json:"id"`
	TitleCiphertext   []byte    `json:"title_ciphertext"`
	TitleEncryptedDek []byte    `json:"title_encrypted_dek"`
	TextCiphertext    []byte    `json:"text_ciphertext"`
	TextEncryptedDek  []byte    `json:"text_encrypted_dek"`
}

// Replaces the encrypted title+text blobs wholesale (the handler
// re-encrypts the full plaintext on every edit). bumps updated_at.
func (q *Queries) UpdatePatientNote(ctx context.Context, arg UpdatePatientNoteParams) (PatientNote, error) {
	row := q.db.QueryRow(ctx, updatePatientNote,
		arg.ID,
		arg.TitleCiphertext,
		arg.TitleEncryptedDek,
		arg.TextCiphertext,
		arg.TextEncryptedDek,
	)
	var i PatientNote
	err := row.Scan(
		&i.ID,
		&i.PatientFileID,
		&i.TherapistID,
		&i.Kind,
		&i.SourceSessionID,
		&i.TitleCiphertext,
		&i.TitleEncryptedDek,
		&i.TextCiphertext,
		&i.TextEncryptedDek,
		&i.SentToPatientAt,
		&i.SentToEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
