// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient_files.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPatientFilesByTherapist = `-- name: CountPatientFilesByTherapist :one
SELECT COUNT(*) FROM patient_files
WHERE therapist_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountPatientFilesByTherapist(ctx context.Context, therapistID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPatientFilesByTherapist, therapistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPatientFile = `-- name: CreatePatientFile :one
INSERT INTO patient_files (
  therapist_id, patient_id, modality_id, working_alias,
  process_type, initial_complaint, has_recording_consent,
  consent_given_at, idempotency_key
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  CASE WHEN $7::boolean THEN now() ELSE NULL END,
  $8
)
RETURNING id, therapist_id, patient_id, relation_id, modality_id, working_alias, process_type, initial_complaint, is_process_closed, has_recording_consent, consent_given_at, first_consultation_at, private_therapist_notes, created_at, updated_at, deleted_at, idempotency_key
`

type CreatePatientFileParams struct {
	TherapistID         uuid.UUID   `json:"therapist_id"`
	PatientID           pgtype.UUID `json:"patient_id"`
	ModalityID          uuid.UUID   `json:"modality_id"`
	WorkingAlias        string      `json:"working_alias"`
	ProcessType         ProcessType `json:"process_type"`
	InitialComplaint    *string     `json:"initial_complaint"`
	HasRecordingConsent bool        `json:"has_recording_consent"`
	IdempotencyKey      *string     `json:"idempotency_key"`
}

// patient_id is the FK to the paired users row (role='PATIENT'),
// created by clinical-svc.CreatePatientFile handler immediately
// before this insert. The handler runs both in one transaction so
// patient_file never points at a missing user.
//
// consent_given_at is set to now() at insert time iff has_recording_consent
// is true. This stamps when the therapist confirmed consent in our system —
// the boolean alone gives no audit trail, and RODO inspections / supervisor
// audits routinely ask "when was consent given?". If consent is later
// revoked (separate flow, not implemented yet), the timestamp stays as
// the historical record of when it was originally granted.
//
// idempotency_key (migration 000017): client-supplied retry key. The
// handler pre-checks via GetPatientFileByIdempotency before insert;
// this query is also wrapped with a unique-violation catch on
// ux_patient_files_idempotency for the race window between the
// pre-check and the insert.
func (q *Queries) CreatePatientFile(ctx context.Context, arg CreatePatientFileParams) (PatientFile, error) {
	row := q.db.QueryRow(ctx, createPatientFile,
		arg.TherapistID,
		arg.PatientID,
		arg.ModalityID,
		arg.WorkingAlias,
		arg.ProcessType,
		arg.InitialComplaint,
		arg.HasRecordingConsent,
		arg.IdempotencyKey,
	)
	var i PatientFile
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientID,
		&i.RelationID,
		&i.ModalityID,
		&i.WorkingAlias,
		&i.ProcessType,
		&i.InitialComplaint,
		&i.IsProcessClosed,
		&i.HasRecordingConsent,
		&i.ConsentGivenAt,
		&i.FirstConsultationAt,
		&i.PrivateTherapistNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPatientFile = `-- name: GetPatientFile :one
SELECT id, therapist_id, patient_id, relation_id, modality_id, working_alias, process_type, initial_complaint, is_process_closed, has_recording_consent, consent_given_at, first_consultation_at, private_therapist_notes, created_at, updated_at, deleted_at, idempotency_key FROM patient_files
WHERE id = $1 AND deleted_at IS NULL
`

// Kept for code paths that don't need user fields (e.g. internal
// authz/ownership checks). External callers use GetPatientFileWithUser.
func (q *Queries) GetPatientFile(ctx context.Context, id uuid.UUID) (PatientFile, error) {
	row := q.db.QueryRow(ctx, getPatientFile, id)
	var i PatientFile
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientID,
		&i.RelationID,
		&i.ModalityID,
		&i.WorkingAlias,
		&i.ProcessType,
		&i.InitialComplaint,
		&i.IsProcessClosed,
		&i.HasRecordingConsent,
		&i.ConsentGivenAt,
		&i.FirstConsultationAt,
		&i.PrivateTherapistNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPatientFileByIdempotency = `-- name: GetPatientFileByIdempotency :one
SELECT id, therapist_id, patient_id, relation_id, modality_id, working_alias, process_type, initial_complaint, is_process_closed, has_recording_consent, consent_given_at, first_consultation_at, private_therapist_notes, created_at, updated_at, deleted_at, idempotency_key FROM patient_files
WHERE therapist_id = $1
  AND idempotency_key = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetPatientFileByIdempotencyParams struct {
	TherapistID    uuid.UUID `json:"therapist_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

// Lenient-mode idempotency lookup. Same (therapist_id, idempotency_key)
// returns the first matching row regardless of payload differences.
// Soft-deleted rows are excluded so the key is re-usable after a
// DELETE — matches the partial unique index ux_patient_files_idempotency.
// Empty/NULL key short-circuits in Go (handler doesn't call this query).
func (q *Queries) GetPatientFileByIdempotency(ctx context.Context, arg GetPatientFileByIdempotencyParams) (PatientFile, error) {
	row := q.db.QueryRow(ctx, getPatientFileByIdempotency, arg.TherapistID, arg.IdempotencyKey)
	var i PatientFile
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientID,
		&i.RelationID,
		&i.ModalityID,
		&i.WorkingAlias,
		&i.ProcessType,
		&i.InitialComplaint,
		&i.IsProcessClosed,
		&i.HasRecordingConsent,
		&i.ConsentGivenAt,
		&i.FirstConsultationAt,
		&i.PrivateTherapistNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPatientFileWithUser = `-- name: GetPatientFileWithUser :one
SELECT
  pf.id, pf.therapist_id, pf.patient_id, pf.relation_id, pf.modality_id, pf.working_alias, pf.process_type, pf.initial_complaint, pf.is_process_closed, pf.has_recording_consent, pf.consent_given_at, pf.first_consultation_at, pf.private_therapist_notes, pf.created_at, pf.updated_at, pf.deleted_at, pf.idempotency_key,
  u.first_name  AS patient_first_name,
  u.last_name   AS patient_last_name,
  u.ui_language AS patient_language_code,
  m.system_code AS modality_code
FROM patient_files pf
LEFT JOIN users u ON u.id = pf.patient_id AND u.role = 'PATIENT' AND u.deleted_at IS NULL
INNER JOIN modalities m ON m.id = pf.modality_id
WHERE pf.id = $1 AND pf.deleted_at IS NULL
`

type GetPatientFileWithUserRow struct {
	ID                    uuid.UUID          `json:"id"`
	TherapistID           uuid.UUID          `json:"therapist_id"`
	PatientID             pgtype.UUID        `json:"patient_id"`
	RelationID            pgtype.UUID        `json:"relation_id"`
	ModalityID            uuid.UUID          `json:"modality_id"`
	WorkingAlias          string             `json:"working_alias"`
	ProcessType           ProcessType        `json:"process_type"`
	InitialComplaint      *string            `json:"initial_complaint"`
	IsProcessClosed       bool               `json:"is_process_closed"`
	HasRecordingConsent   bool               `json:"has_recording_consent"`
	ConsentGivenAt        pgtype.Timestamptz `json:"consent_given_at"`
	FirstConsultationAt   pgtype.Timestamptz `json:"first_consultation_at"`
	PrivateTherapistNotes *string            `json:"private_therapist_notes"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	IdempotencyKey        *string            `json:"idempotency_key"`
	PatientFirstName      *string            `json:"patient_first_name"`
	PatientLastName       *string            `json:"patient_last_name"`
	PatientLanguageCode   *string            `json:"patient_language_code"`
	ModalityCode          string             `json:"modality_code"`
}

// Returns the patient_file plus the JOINed user fields used in the
// proto response. LEFT JOIN on users because patient_id may be NULL
// after DeletePatientUser left an orphan (only possible before
// migration 000014's CASCADE flip; kept LEFT for defensiveness on
// already-orphaned rows in production). NULL user columns are
// emitted as empty strings by the proto mapper.
//
// INNER JOIN on modalities — patient_files.modality_id is NOT NULL
// (migration 000005), so an INNER JOIN won't drop any rows but does
// give us a non-null `modality_code` to populate the proto response
// without a second round-trip. Closes the "modality empty after
// create" gap surfaced by the previous Faza 2 TODO.
func (q *Queries) GetPatientFileWithUser(ctx context.Context, id uuid.UUID) (GetPatientFileWithUserRow, error) {
	row := q.db.QueryRow(ctx, getPatientFileWithUser, id)
	var i GetPatientFileWithUserRow
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientID,
		&i.RelationID,
		&i.ModalityID,
		&i.WorkingAlias,
		&i.ProcessType,
		&i.InitialComplaint,
		&i.IsProcessClosed,
		&i.HasRecordingConsent,
		&i.ConsentGivenAt,
		&i.FirstConsultationAt,
		&i.PrivateTherapistNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
		&i.PatientFirstName,
		&i.PatientLastName,
		&i.PatientLanguageCode,
		&i.ModalityCode,
	)
	return i, err
}

const hardDeletePatientFile = `-- name: HardDeletePatientFile :execrows
DELETE FROM patient_files WHERE id = $1 AND therapist_id = $2
`

type HardDeletePatientFileParams struct {
	ID          uuid.UUID `json:"id"`
	TherapistID uuid.UUID `json:"therapist_id"`
}

// Permanent removal. Migration 000012 added ON DELETE CASCADE on
// sessions.patient_file_id and audio_uploads.patient_file_id, so all
// child sessions (and their transcripts/reports/hitop rows via the
// second-level cascade) get wiped in a single statement.
// therapist_id predicate is the authz guard at the SQL layer.
// Returns row count so caller can distinguish 404 from success.
func (q *Queries) HardDeletePatientFile(ctx context.Context, arg HardDeletePatientFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeletePatientFile, arg.ID, arg.TherapistID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPatientFilesByTherapist = `-- name: ListPatientFilesByTherapist :many
SELECT id, therapist_id, patient_id, relation_id, modality_id, working_alias, process_type, initial_complaint, is_process_closed, has_recording_consent, consent_given_at, first_consultation_at, private_therapist_notes, created_at, updated_at, deleted_at, idempotency_key FROM patient_files
WHERE therapist_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPatientFilesByTherapistParams struct {
	TherapistID uuid.UUID `json:"therapist_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListPatientFilesByTherapist(ctx context.Context, arg ListPatientFilesByTherapistParams) ([]PatientFile, error) {
	rows, err := q.db.Query(ctx, listPatientFilesByTherapist, arg.TherapistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientFile
	for rows.Next() {
		var i PatientFile
		if err := rows.Scan(
			&i.ID,
			&i.TherapistID,
			&i.PatientID,
			&i.RelationID,
			&i.ModalityID,
			&i.WorkingAlias,
			&i.ProcessType,
			&i.InitialComplaint,
			&i.IsProcessClosed,
			&i.HasRecordingConsent,
			&i.ConsentGivenAt,
			&i.FirstConsultationAt,
			&i.PrivateTherapistNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientFilesByTherapistWithUser = `-- name: ListPatientFilesByTherapistWithUser :many
SELECT
  pf.id, pf.therapist_id, pf.patient_id, pf.relation_id, pf.modality_id, pf.working_alias, pf.process_type, pf.initial_complaint, pf.is_process_closed, pf.has_recording_consent, pf.consent_given_at, pf.first_consultation_at, pf.private_therapist_notes, pf.created_at, pf.updated_at, pf.deleted_at, pf.idempotency_key,
  u.first_name  AS patient_first_name,
  u.last_name   AS patient_last_name,
  u.ui_language AS patient_language_code,
  m.system_code AS modality_code
FROM patient_files pf
LEFT JOIN users u ON u.id = pf.patient_id AND u.role = 'PATIENT' AND u.deleted_at IS NULL
INNER JOIN modalities m ON m.id = pf.modality_id
WHERE pf.therapist_id = $1 AND pf.deleted_at IS NULL
ORDER BY pf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPatientFilesByTherapistWithUserParams struct {
	TherapistID uuid.UUID `json:"therapist_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListPatientFilesByTherapistWithUserRow struct {
	ID                    uuid.UUID          `json:"id"`
	TherapistID           uuid.UUID          `json:"therapist_id"`
	PatientID             pgtype.UUID        `json:"patient_id"`
	RelationID            pgtype.UUID        `json:"relation_id"`
	ModalityID            uuid.UUID          `json:"modality_id"`
	WorkingAlias          string             `json:"working_alias"`
	ProcessType           ProcessType        `json:"process_type"`
	InitialComplaint      *string            `json:"initial_complaint"`
	IsProcessClosed       bool               `json:"is_process_closed"`
	HasRecordingConsent   bool               `json:"has_recording_consent"`
	ConsentGivenAt        pgtype.Timestamptz `json:"consent_given_at"`
	FirstConsultationAt   pgtype.Timestamptz `json:"first_consultation_at"`
	PrivateTherapistNotes *string            `json:"private_therapist_notes"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	IdempotencyKey        *string            `json:"idempotency_key"`
	PatientFirstName      *string            `json:"patient_first_name"`
	PatientLastName       *string            `json:"patient_last_name"`
	PatientLanguageCode   *string            `json:"patient_language_code"`
	ModalityCode          string             `json:"modality_code"`
}

// See GetPatientFileWithUser comment for the JOIN strategy. Same
// shape, just the WHERE switches to therapist_id + paged.
func (q *Queries) ListPatientFilesByTherapistWithUser(ctx context.Context, arg ListPatientFilesByTherapistWithUserParams) ([]ListPatientFilesByTherapistWithUserRow, error) {
	rows, err := q.db.Query(ctx, listPatientFilesByTherapistWithUser, arg.TherapistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatientFilesByTherapistWithUserRow
	for rows.Next() {
		var i ListPatientFilesByTherapistWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TherapistID,
			&i.PatientID,
			&i.RelationID,
			&i.ModalityID,
			&i.WorkingAlias,
			&i.ProcessType,
			&i.InitialComplaint,
			&i.IsProcessClosed,
			&i.HasRecordingConsent,
			&i.ConsentGivenAt,
			&i.FirstConsultationAt,
			&i.PrivateTherapistNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IdempotencyKey,
			&i.PatientFirstName,
			&i.PatientLastName,
			&i.PatientLanguageCode,
			&i.ModalityCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionIDsForPatientFile = `-- name: ListSessionIDsForPatientFile :many
SELECT id FROM sessions WHERE patient_file_id = $1 AND deleted_at IS NULL
`

// Pre-fetched BEFORE HardDeletePatientFile runs, so the caller can
// publish one session.deleted Pub/Sub event per affected session for
// Firestore + inbox cleanup downstream. After the hard delete the
// rows are gone and we'd have nothing to publish.
func (q *Queries) ListSessionIDsForPatientFile(ctx context.Context, patientFileID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSessionIDsForPatientFile, patientFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePatientFile = `-- name: SoftDeletePatientFile :exec
UPDATE patient_files SET deleted_at = now()
WHERE id = $1 AND therapist_id = $2
`

type SoftDeletePatientFileParams struct {
	ID          uuid.UUID `json:"id"`
	TherapistID uuid.UUID `json:"therapist_id"`
}

// Kept for backwards compatibility — old gRPC handlers may still call
// it. New code (post-000012) uses HardDeletePatientFile to satisfy
// RODO right-to-erasure.
func (q *Queries) SoftDeletePatientFile(ctx context.Context, arg SoftDeletePatientFileParams) error {
	_, err := q.db.Exec(ctx, softDeletePatientFile, arg.ID, arg.TherapistID)
	return err
}

const updatePatientFile = `-- name: UpdatePatientFile :one
UPDATE patient_files SET
  working_alias = COALESCE(NULLIF($2, ''), working_alias),
  initial_complaint = NULLIF($3, ''),
  private_therapist_notes = NULLIF($4, ''),
  is_process_closed = $5,
  updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, therapist_id, patient_id, relation_id, modality_id, working_alias, process_type, initial_complaint, is_process_closed, has_recording_consent, consent_given_at, first_consultation_at, private_therapist_notes, created_at, updated_at, deleted_at, idempotency_key
`

type UpdatePatientFileParams struct {
	ID              uuid.UUID   `json:"id"`
	Column2         interface{} `json:"column_2"`
	Column3         interface{} `json:"column_3"`
	Column4         interface{} `json:"column_4"`
	IsProcessClosed bool        `json:"is_process_closed"`
}

// Mutates only the therapist-editable kartoteka fields. modality_id is
// intentionally NOT here: sessions/reports were analyzed under the
// modality picked at create time, and silently swapping it would
// re-frame past clinical work. See PatientFile.modality_id in
// clinical.proto. process_type follows the same logic.
// Patient-user fields (first_name/last_name/language_code) live in
// patient_users.sql::UpdatePatientUser.
func (q *Queries) UpdatePatientFile(ctx context.Context, arg UpdatePatientFileParams) (PatientFile, error) {
	row := q.db.QueryRow(ctx, updatePatientFile,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.IsProcessClosed,
	)
	var i PatientFile
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientID,
		&i.RelationID,
		&i.ModalityID,
		&i.WorkingAlias,
		&i.ProcessType,
		&i.InitialComplaint,
		&i.IsProcessClosed,
		&i.HasRecordingConsent,
		&i.ConsentGivenAt,
		&i.FirstConsultationAt,
		&i.PrivateTherapistNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
	)
	return i, err
}
