// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient_users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPatientUser = `-- name: CreatePatientUser :one

INSERT INTO users (role, first_name, last_name, ui_language)
VALUES ('PATIENT', '', '', $1)
RETURNING id
`

// Patient user CRUD — operates on rows in `users` with role='PATIENT'.
// Created/edited from clinical-svc.CreatePatientFile + UpdatePatientUser
// + DeletePatientUser handlers. The therapist-side ownership check
// happens at the handler layer (patient_files.therapist_id == ctx user);
// queries here filter only by role to defend against accidentally
// mutating a non-patient row.
// Inserts a fresh PATIENT row. firebase_uid + email stay NULL (patient
// has no account yet); the partial CHECK constraints in migration 000013
// allow that for role='PATIENT'.
//
// first_name/last_name are deliberately blank (docs/43 §4: the client's
// only direct identifier is the e-mail; the kartoteka identifies the
// client by patient_files.working_alias). Columns stay NOT NULL for the
// therapist rows, so we write ”.
func (q *Queries) CreatePatientUser(ctx context.Context, uiLanguage string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPatientUser, uiLanguage)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deletePatientUser = `-- name: DeletePatientUser :execrows
DELETE FROM users WHERE id = $1 AND role = 'PATIENT'
`

// Hard delete. patient_files.patient_id FK is SET NULL (migration
// 000013) so any kartoteka referencing this row gets its patient_id
// cleared automatically. Returns rows-affected so the handler can
// distinguish "not found / not a patient" from success.
func (q *Queries) DeletePatientUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePatientUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPatientUser = `-- name: GetPatientUser :one
SELECT id, ui_language
FROM users
WHERE id = $1 AND role = 'PATIENT' AND deleted_at IS NULL
`

type GetPatientUserRow struct {
	ID         uuid.UUID `json:"id"`
	UiLanguage string    `json:"ui_language"`
}

func (q *Queries) GetPatientUser(ctx context.Context, id uuid.UUID) (GetPatientUserRow, error) {
	row := q.db.QueryRow(ctx, getPatientUser, id)
	var i GetPatientUserRow
	err := row.Scan(&i.ID, &i.UiLanguage)
	return i, err
}

const getTherapistUILanguage = `-- name: GetTherapistUILanguage :one
SELECT COALESCE(ui_language, '') AS ui_language
FROM users
WHERE id = $1
`

// Used by CreatePatientFile to default the new patient's ui_language
// when the caller didn't pass one. Returns ” if the therapist row is
// somehow missing (shouldn't happen — auth interceptor would reject).
func (q *Queries) GetTherapistUILanguage(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTherapistUILanguage, id)
	var ui_language string
	err := row.Scan(&ui_language)
	return ui_language, err
}

const listSessionIDsForPatient = `-- name: ListSessionIDsForPatient :many
SELECT s.id
FROM sessions s
JOIN patient_files pf ON pf.id = s.patient_file_id
WHERE pf.patient_id = $1 AND pf.deleted_at IS NULL AND s.deleted_at IS NULL
`

// Pre-fetched before DeletePatientUser runs so the handler can fan
// out one session.deleted Pub/Sub event per session that will be
// cascade-deleted by the user row going away (migration 000014).
// JOIN-based because sessions don't reference users directly — they
// hang off patient_files which hang off users.
// After the cascade the rows are gone; we'd have nothing to publish
// from a post-delete query.
func (q *Queries) ListSessionIDsForPatient(ctx context.Context, patientID pgtype.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSessionIDsForPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatientUser = `-- name: UpdatePatientUser :one
UPDATE users SET
  ui_language = COALESCE(NULLIF($1::text, ''), ui_language)
WHERE id = $2 AND role = 'PATIENT' AND deleted_at IS NULL
RETURNING id, ui_language
`

type UpdatePatientUserParams struct {
	LanguageCode string    `json:"language_code"`
	ID           uuid.UUID `json:"id"`
}

type UpdatePatientUserRow struct {
	ID         uuid.UUID `json:"id"`
	UiLanguage string    `json:"ui_language"`
}

// COALESCE/NULLIF pattern: empty string from the caller means "leave
// this field alone". Names are no longer editable here (docs/43 §4 —
// the kartoteka's identifier is working_alias, edited via
// UpdatePatientFile); only the patient's UI language remains.
func (q *Queries) UpdatePatientUser(ctx context.Context, arg UpdatePatientUserParams) (UpdatePatientUserRow, error) {
	row := q.db.QueryRow(ctx, updatePatientUser, arg.LanguageCode, arg.ID)
	var i UpdatePatientUserRow
	err := row.Scan(&i.ID, &i.UiLanguage)
	return i, err
}
