// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient_users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPatientUser = `-- name: CreatePatientUser :one

INSERT INTO users (role, first_name, last_name, ui_language)
VALUES ('PATIENT', $1, $2, $3)
RETURNING id
`

type CreatePatientUserParams struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	UiLanguage string `json:"ui_language"`
}

// Patient user CRUD — operates on rows in `users` with role='PATIENT'.
// Created/edited from clinical-svc.CreatePatientFile + UpdatePatientUser
// + DeletePatientUser handlers. The therapist-side ownership check
// happens at the handler layer (patient_files.therapist_id == ctx user);
// queries here filter only by role to defend against accidentally
// mutating a non-patient row.
// Inserts a fresh PATIENT row. firebase_uid + email stay NULL (patient
// has no account yet); the partial CHECK constraints in migration 000013
// allow that for role='PATIENT'.
func (q *Queries) CreatePatientUser(ctx context.Context, arg CreatePatientUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPatientUser, arg.FirstName, arg.LastName, arg.UiLanguage)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deletePatientUser = `-- name: DeletePatientUser :execrows
DELETE FROM users WHERE id = $1 AND role = 'PATIENT'
`

// Hard delete. patient_files.patient_id FK is SET NULL (migration
// 000013) so any kartoteka referencing this row gets its patient_id
// cleared automatically. Returns rows-affected so the handler can
// distinguish "not found / not a patient" from success.
func (q *Queries) DeletePatientUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePatientUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPatientUser = `-- name: GetPatientUser :one
SELECT id, first_name, last_name, ui_language
FROM users
WHERE id = $1 AND role = 'PATIENT' AND deleted_at IS NULL
`

type GetPatientUserRow struct {
	ID         uuid.UUID `json:"id"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
	UiLanguage string    `json:"ui_language"`
}

func (q *Queries) GetPatientUser(ctx context.Context, id uuid.UUID) (GetPatientUserRow, error) {
	row := q.db.QueryRow(ctx, getPatientUser, id)
	var i GetPatientUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.UiLanguage,
	)
	return i, err
}

const getTherapistUILanguage = `-- name: GetTherapistUILanguage :one
SELECT COALESCE(ui_language, '') AS ui_language
FROM users
WHERE id = $1
`

// Used by CreatePatientFile to default the new patient's ui_language
// when the caller didn't pass one. Returns ” if the therapist row is
// somehow missing (shouldn't happen — auth interceptor would reject).
func (q *Queries) GetTherapistUILanguage(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTherapistUILanguage, id)
	var ui_language string
	err := row.Scan(&ui_language)
	return ui_language, err
}

const updatePatientUser = `-- name: UpdatePatientUser :one
UPDATE users SET
  first_name  = COALESCE(NULLIF($1::text, ''), first_name),
  last_name   = COALESCE(NULLIF($2::text, ''), last_name),
  ui_language = COALESCE(NULLIF($3::text, ''), ui_language)
WHERE id = $4 AND role = 'PATIENT' AND deleted_at IS NULL
RETURNING id, first_name, last_name, ui_language
`

type UpdatePatientUserParams struct {
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	LanguageCode string    `json:"language_code"`
	ID           uuid.UUID `json:"id"`
}

type UpdatePatientUserRow struct {
	ID         uuid.UUID `json:"id"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
	UiLanguage string    `json:"ui_language"`
}

// COALESCE/NULLIF pattern: empty string from the caller means "leave
// this field alone". Concrete value (even a single character) replaces
// the column. Returns the refreshed row so the handler can re-emit the
// PatientFile proto with fresh user fields.
func (q *Queries) UpdatePatientUser(ctx context.Context, arg UpdatePatientUserParams) (UpdatePatientUserRow, error) {
	row := q.db.QueryRow(ctx, updatePatientUser,
		arg.FirstName,
		arg.LastName,
		arg.LanguageCode,
		arg.ID,
	)
	var i UpdatePatientUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.UiLanguage,
	)
	return i, err
}
