// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient_files.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countPatientFilesByTherapist = `-- name: CountPatientFilesByTherapist :one
SELECT COUNT(*) FROM patient_files
WHERE therapist_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountPatientFilesByTherapist(ctx context.Context, therapistID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPatientFilesByTherapist, therapistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPatientFile = `-- name: CreatePatientFile :one
INSERT INTO patient_files (
  therapist_id, modality_id, working_alias,
  process_type, initial_complaint, has_recording_consent
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, therapist_id, patient_id, relation_id, modality_id, working_alias, process_type, initial_complaint, is_process_closed, has_recording_consent, consent_given_at, first_consultation_at, private_therapist_notes, created_at, updated_at, deleted_at
`

type CreatePatientFileParams struct {
	TherapistID         uuid.UUID   `json:"therapist_id"`
	ModalityID          uuid.UUID   `json:"modality_id"`
	WorkingAlias        string      `json:"working_alias"`
	ProcessType         ProcessType `json:"process_type"`
	InitialComplaint    *string     `json:"initial_complaint"`
	HasRecordingConsent bool        `json:"has_recording_consent"`
}

func (q *Queries) CreatePatientFile(ctx context.Context, arg CreatePatientFileParams) (PatientFile, error) {
	row := q.db.QueryRow(ctx, createPatientFile,
		arg.TherapistID,
		arg.ModalityID,
		arg.WorkingAlias,
		arg.ProcessType,
		arg.InitialComplaint,
		arg.HasRecordingConsent,
	)
	var i PatientFile
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientID,
		&i.RelationID,
		&i.ModalityID,
		&i.WorkingAlias,
		&i.ProcessType,
		&i.InitialComplaint,
		&i.IsProcessClosed,
		&i.HasRecordingConsent,
		&i.ConsentGivenAt,
		&i.FirstConsultationAt,
		&i.PrivateTherapistNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPatientFile = `-- name: GetPatientFile :one
SELECT id, therapist_id, patient_id, relation_id, modality_id, working_alias, process_type, initial_complaint, is_process_closed, has_recording_consent, consent_given_at, first_consultation_at, private_therapist_notes, created_at, updated_at, deleted_at FROM patient_files
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPatientFile(ctx context.Context, id uuid.UUID) (PatientFile, error) {
	row := q.db.QueryRow(ctx, getPatientFile, id)
	var i PatientFile
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientID,
		&i.RelationID,
		&i.ModalityID,
		&i.WorkingAlias,
		&i.ProcessType,
		&i.InitialComplaint,
		&i.IsProcessClosed,
		&i.HasRecordingConsent,
		&i.ConsentGivenAt,
		&i.FirstConsultationAt,
		&i.PrivateTherapistNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeletePatientFile = `-- name: HardDeletePatientFile :execrows
DELETE FROM patient_files WHERE id = $1 AND therapist_id = $2
`

type HardDeletePatientFileParams struct {
	ID          uuid.UUID `json:"id"`
	TherapistID uuid.UUID `json:"therapist_id"`
}

// Permanent removal. Migration 000012 added ON DELETE CASCADE on
// sessions.patient_file_id and audio_uploads.patient_file_id, so all
// child sessions (and their transcripts/reports/hitop rows via the
// second-level cascade) get wiped in a single statement.
// therapist_id predicate is the authz guard at the SQL layer.
// Returns row count so caller can distinguish 404 from success.
func (q *Queries) HardDeletePatientFile(ctx context.Context, arg HardDeletePatientFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeletePatientFile, arg.ID, arg.TherapistID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPatientFilesByTherapist = `-- name: ListPatientFilesByTherapist :many
SELECT id, therapist_id, patient_id, relation_id, modality_id, working_alias, process_type, initial_complaint, is_process_closed, has_recording_consent, consent_given_at, first_consultation_at, private_therapist_notes, created_at, updated_at, deleted_at FROM patient_files
WHERE therapist_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPatientFilesByTherapistParams struct {
	TherapistID uuid.UUID `json:"therapist_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListPatientFilesByTherapist(ctx context.Context, arg ListPatientFilesByTherapistParams) ([]PatientFile, error) {
	rows, err := q.db.Query(ctx, listPatientFilesByTherapist, arg.TherapistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientFile
	for rows.Next() {
		var i PatientFile
		if err := rows.Scan(
			&i.ID,
			&i.TherapistID,
			&i.PatientID,
			&i.RelationID,
			&i.ModalityID,
			&i.WorkingAlias,
			&i.ProcessType,
			&i.InitialComplaint,
			&i.IsProcessClosed,
			&i.HasRecordingConsent,
			&i.ConsentGivenAt,
			&i.FirstConsultationAt,
			&i.PrivateTherapistNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionIDsForPatientFile = `-- name: ListSessionIDsForPatientFile :many
SELECT id FROM sessions WHERE patient_file_id = $1 AND deleted_at IS NULL
`

// Pre-fetched BEFORE HardDeletePatientFile runs, so the caller can
// publish one session.deleted Pub/Sub event per affected session for
// Firestore + inbox cleanup downstream. After the hard delete the
// rows are gone and we'd have nothing to publish.
func (q *Queries) ListSessionIDsForPatientFile(ctx context.Context, patientFileID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSessionIDsForPatientFile, patientFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePatientFile = `-- name: SoftDeletePatientFile :exec
UPDATE patient_files SET deleted_at = now()
WHERE id = $1 AND therapist_id = $2
`

type SoftDeletePatientFileParams struct {
	ID          uuid.UUID `json:"id"`
	TherapistID uuid.UUID `json:"therapist_id"`
}

// Kept for backwards compatibility — old gRPC handlers may still call
// it. New code (post-000012) uses HardDeletePatientFile to satisfy
// RODO right-to-erasure.
func (q *Queries) SoftDeletePatientFile(ctx context.Context, arg SoftDeletePatientFileParams) error {
	_, err := q.db.Exec(ctx, softDeletePatientFile, arg.ID, arg.TherapistID)
	return err
}

const updatePatientFile = `-- name: UpdatePatientFile :one
UPDATE patient_files SET
  working_alias = COALESCE(NULLIF($2, ''), working_alias),
  initial_complaint = NULLIF($3, ''),
  private_therapist_notes = NULLIF($4, ''),
  is_process_closed = $5,
  updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, therapist_id, patient_id, relation_id, modality_id, working_alias, process_type, initial_complaint, is_process_closed, has_recording_consent, consent_given_at, first_consultation_at, private_therapist_notes, created_at, updated_at, deleted_at
`

type UpdatePatientFileParams struct {
	ID              uuid.UUID   `json:"id"`
	Column2         interface{} `json:"column_2"`
	Column3         interface{} `json:"column_3"`
	Column4         interface{} `json:"column_4"`
	IsProcessClosed bool        `json:"is_process_closed"`
}

func (q *Queries) UpdatePatientFile(ctx context.Context, arg UpdatePatientFileParams) (PatientFile, error) {
	row := q.db.QueryRow(ctx, updatePatientFile,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.IsProcessClosed,
	)
	var i PatientFile
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientID,
		&i.RelationID,
		&i.ModalityID,
		&i.WorkingAlias,
		&i.ProcessType,
		&i.InitialComplaint,
		&i.IsProcessClosed,
		&i.HasRecordingConsent,
		&i.ConsentGivenAt,
		&i.FirstConsultationAt,
		&i.PrivateTherapistNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
