// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountPatientFilesByTherapist(ctx context.Context, therapistID uuid.UUID) (int64, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	// patient_id is the FK to the paired users row (role='PATIENT'),
	// created by clinical-svc.CreatePatientFile handler immediately
	// before this insert. The handler runs both in one transaction so
	// patient_file never points at a missing user.
	//
	// consent_given_at is set to now() at insert time iff has_recording_consent
	// is true. This stamps when the therapist confirmed consent in our system —
	// the boolean alone gives no audit trail, and RODO inspections / supervisor
	// audits routinely ask "when was consent given?". If consent is later
	// revoked (separate flow, not implemented yet), the timestamp stays as
	// the historical record of when it was originally granted.
	CreatePatientFile(ctx context.Context, arg CreatePatientFileParams) (PatientFile, error)
	// Patient user CRUD — operates on rows in `users` with role='PATIENT'.
	// Created/edited from clinical-svc.CreatePatientFile + UpdatePatientUser
	// + DeletePatientUser handlers. The therapist-side ownership check
	// happens at the handler layer (patient_files.therapist_id == ctx user);
	// queries here filter only by role to defend against accidentally
	// mutating a non-patient row.
	// Inserts a fresh PATIENT row. firebase_uid + email stay NULL (patient
	// has no account yet); the partial CHECK constraints in migration 000013
	// allow that for role='PATIENT'.
	CreatePatientUser(ctx context.Context, arg CreatePatientUserParams) (uuid.UUID, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Hard delete. patient_files.patient_id FK is SET NULL (migration
	// 000013) so any kartoteka referencing this row gets its patient_id
	// cleared automatically. Returns rows-affected so the handler can
	// distinguish "not found / not a patient" from success.
	DeletePatientUser(ctx context.Context, id uuid.UUID) (int64, error)
	// Compute the default session.name as production would set it on
	// create. Used by ingestion-svc.CompleteAudioUpload when populating
	// the column for a brand-new session. The COALESCE guards against
	// a missing modality join (defensive — modality_id is NOT NULL on
	// patient_files so this should never fire, but cheap insurance).
	GetDefaultSessionName(ctx context.Context, arg GetDefaultSessionNameParams) (interface{}, error)
	GetModalityByCode(ctx context.Context, systemCode string) (GetModalityByCodeRow, error)
	// Kept for code paths that don't need user fields (e.g. internal
	// authz/ownership checks). External callers use GetPatientFileWithUser.
	GetPatientFile(ctx context.Context, id uuid.UUID) (PatientFile, error)
	// Returns the patient_file plus the JOINed user fields used in the
	// proto response. LEFT JOIN on users because patient_id may be NULL
	// after DeletePatientUser left an orphan (only possible before
	// migration 000014's CASCADE flip; kept LEFT for defensiveness on
	// already-orphaned rows in production). NULL user columns are
	// emitted as empty strings by the proto mapper.
	//
	// INNER JOIN on modalities — patient_files.modality_id is NOT NULL
	// (migration 000005), so an INNER JOIN won't drop any rows but does
	// give us a non-null `modality_code` to populate the proto response
	// without a second round-trip. Closes the "modality empty after
	// create" gap surfaced by the previous Faza 2 TODO.
	GetPatientFileWithUser(ctx context.Context, id uuid.UUID) (GetPatientFileWithUserRow, error)
	GetPatientUser(ctx context.Context, id uuid.UUID) (GetPatientUserRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionWithDetails(ctx context.Context, id uuid.UUID) (GetSessionWithDetailsRow, error)
	// Used by CreatePatientFile to default the new patient's ui_language
	// when the caller didn't pass one. Returns '' if the therapist row is
	// somehow missing (shouldn't happen — auth interceptor would reject).
	GetTherapistUILanguage(ctx context.Context, id uuid.UUID) (string, error)
	GetTranscriptBySession(ctx context.Context, sessionID uuid.UUID) (Transcript, error)
	GetTranscriptForRebuild(ctx context.Context, sessionID uuid.UUID) (GetTranscriptForRebuildRow, error)
	// Permanent removal. Migration 000012 added ON DELETE CASCADE on
	// sessions.patient_file_id and audio_uploads.patient_file_id, so all
	// child sessions (and their transcripts/reports/hitop rows via the
	// second-level cascade) get wiped in a single statement.
	// therapist_id predicate is the authz guard at the SQL layer.
	// Returns row count so caller can distinguish 404 from success.
	HardDeletePatientFile(ctx context.Context, arg HardDeletePatientFileParams) (int64, error)
	// Permanent delete. Migration 000012 added ON DELETE CASCADE on
	// transcripts.session_id, reports.session_id, hitop_measurements.session_id,
	// so dependent rows are removed automatically. notification_deliveries
	// gets SET NULL — delivery history survives, just unbound from session.
	// audio_uploads.session_id is already SET NULL since 000007.
	// The therapist_id predicate is the authz guard at the query level.
	// Returns affected rows so the handler can distinguish "not found /
	// not yours" (0 rows) from successful delete (1 row).
	HardDeleteSession(ctx context.Context, arg HardDeleteSessionParams) (int64, error)
	ListPatientFilesByTherapist(ctx context.Context, arg ListPatientFilesByTherapistParams) ([]PatientFile, error)
	// See GetPatientFileWithUser comment for the JOIN strategy. Same
	// shape, just the WHERE switches to therapist_id + paged.
	ListPatientFilesByTherapistWithUser(ctx context.Context, arg ListPatientFilesByTherapistWithUserParams) ([]ListPatientFilesByTherapistWithUserRow, error)
	ListReportsBySession(ctx context.Context, sessionID uuid.UUID) ([]Report, error)
	ListSegmentsForRebuild(ctx context.Context, transcriptID uuid.UUID) ([]ListSegmentsForRebuildRow, error)
	// Pre-fetched before DeletePatientUser runs so the handler can fan
	// out one session.deleted Pub/Sub event per session that will be
	// cascade-deleted by the user row going away (migration 000014).
	// JOIN-based because sessions don't reference users directly — they
	// hang off patient_files which hang off users.
	// After the cascade the rows are gone; we'd have nothing to publish
	// from a post-delete query.
	ListSessionIDsForPatient(ctx context.Context, patientID pgtype.UUID) ([]uuid.UUID, error)
	// Pre-fetched BEFORE HardDeletePatientFile runs, so the caller can
	// publish one session.deleted Pub/Sub event per affected session for
	// Firestore + inbox cleanup downstream. After the hard delete the
	// rows are gone and we'd have nothing to publish.
	ListSessionIDsForPatientFile(ctx context.Context, patientFileID uuid.UUID) ([]uuid.UUID, error)
	ListSessionsByPatient(ctx context.Context, patientFileID uuid.UUID) ([]Session, error)
	ListSupportedModalities(ctx context.Context) ([]ListSupportedModalitiesRow, error)
	ListTranscriptSegments(ctx context.Context, transcriptID uuid.UUID) ([]TranscriptSegment, error)
	// Kept for backwards compatibility — old gRPC handlers may still call
	// it. New code (post-000012) uses HardDeletePatientFile to satisfy
	// RODO right-to-erasure.
	SoftDeletePatientFile(ctx context.Context, arg SoftDeletePatientFileParams) error
	// Mutates only the therapist-editable kartoteka fields. modality_id is
	// intentionally NOT here: sessions/reports were analyzed under the
	// modality picked at create time, and silently swapping it would
	// re-frame past clinical work. See PatientFile.modality_id in
	// clinical.proto. process_type follows the same logic.
	// Patient-user fields (first_name/last_name/language_code) live in
	// patient_users.sql::UpdatePatientUser.
	UpdatePatientFile(ctx context.Context, arg UpdatePatientFileParams) (PatientFile, error)
	// COALESCE/NULLIF pattern: empty string from the caller means "leave
	// this field alone". Concrete value (even a single character) replaces
	// the column. Returns the refreshed row so the handler can re-emit the
	// PatientFile proto with fresh user fields.
	UpdatePatientUser(ctx context.Context, arg UpdatePatientUserParams) (UpdatePatientUserRow, error)
	UpdateSegmentLabel(ctx context.Context, arg UpdateSegmentLabelParams) error
	UpdateSessionLabelMapping(ctx context.Context, arg UpdateSessionLabelMappingParams) error
	// Rename a session. Caller is responsible for the authz check
	// (session.therapist_id == ctx user). Returns the refreshed row so
	// the gRPC handler can re-emit the proto Session.
	UpdateSessionName(ctx context.Context, arg UpdateSessionNameParams) (Session, error)
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
	UpdateTranscriptBlob(ctx context.Context, arg UpdateTranscriptBlobParams) error
}

var _ Querier = (*Queries)(nil)
