// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report_ratings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLatestSuggestionDismissForDimension = `-- name: GetLatestSuggestionDismissForDimension :one
SELECT id, dimension, from_value, to_value, trigger_count, created_at
FROM preference_suggestions_log
WHERE therapist_id = $1
  AND dimension = $2
  AND action = 'dismissed'
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestSuggestionDismissForDimensionParams struct {
	TherapistID uuid.UUID `json:"therapist_id"`
	Dimension   string    `json:"dimension"`
}

type GetLatestSuggestionDismissForDimensionRow struct {
	ID           uuid.UUID `json:"id"`
	Dimension    string    `json:"dimension"`
	FromValue    string    `json:"from_value"`
	ToValue      string    `json:"to_value"`
	TriggerCount int32     `json:"trigger_count"`
	CreatedAt    time.Time `json:"created_at"`
}

// Used by the suggestion engine to honor the 14-day cooldown after
// a banner is dismissed for a given dimension. Returns the most
// recent 'dismissed' row for (therapist, dimension) or NotFound.
func (q *Queries) GetLatestSuggestionDismissForDimension(ctx context.Context, arg GetLatestSuggestionDismissForDimensionParams) (GetLatestSuggestionDismissForDimensionRow, error) {
	row := q.db.QueryRow(ctx, getLatestSuggestionDismissForDimension, arg.TherapistID, arg.Dimension)
	var i GetLatestSuggestionDismissForDimensionRow
	err := row.Scan(
		&i.ID,
		&i.Dimension,
		&i.FromValue,
		&i.ToValue,
		&i.TriggerCount,
		&i.CreatedAt,
	)
	return i, err
}

const getReportRating = `-- name: GetReportRating :one

SELECT id, report_id, therapist_id, rating, issues, notes, source, created_at, updated_at FROM report_ratings
WHERE report_id = $1 AND therapist_id = $2
`

type GetReportRatingParams struct {
	ReportID    uuid.UUID `json:"report_id"`
	TherapistID uuid.UUID `json:"therapist_id"`
}

// Report-rating queries. Spec: docs/10_REPORT_CUSTOMIZATION.md §5.
// All paths assume the gRPC handler has already validated that the
// therapist owns the session that owns the report (auth happens at
// the handler boundary, not in SQL).
func (q *Queries) GetReportRating(ctx context.Context, arg GetReportRatingParams) (ReportRating, error) {
	row := q.db.QueryRow(ctx, getReportRating, arg.ReportID, arg.TherapistID)
	var i ReportRating
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.TherapistID,
		&i.Rating,
		&i.Issues,
		&i.Notes,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPreferenceSuggestionLog = `-- name: InsertPreferenceSuggestionLog :exec

INSERT INTO preference_suggestions_log (
    therapist_id, dimension, from_value, to_value, trigger_count, action
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPreferenceSuggestionLogParams struct {
	TherapistID  uuid.UUID `json:"therapist_id"`
	Dimension    string    `json:"dimension"`
	FromValue    string    `json:"from_value"`
	ToValue      string    `json:"to_value"`
	TriggerCount int32     `json:"trigger_count"`
	Action       string    `json:"action"`
}

// ─── preference_suggestions_log ─────────────────────────────
// Telemetry-only. Three action values: 'shown' | 'applied' |
// 'dismissed' — DB CHECK constraint enforces.
func (q *Queries) InsertPreferenceSuggestionLog(ctx context.Context, arg InsertPreferenceSuggestionLogParams) error {
	_, err := q.db.Exec(ctx, insertPreferenceSuggestionLog,
		arg.TherapistID,
		arg.Dimension,
		arg.FromValue,
		arg.ToValue,
		arg.TriggerCount,
		arg.Action,
	)
	return err
}

const listRecentNegativeRatings = `-- name: ListRecentNegativeRatings :many
SELECT id, report_id, rating, issues, created_at
FROM report_ratings
WHERE therapist_id = $1
  AND rating = 'negative'
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentNegativeRatingsParams struct {
	TherapistID uuid.UUID `json:"therapist_id"`
	Limit       int32     `json:"limit"`
}

type ListRecentNegativeRatingsRow struct {
	ID        uuid.UUID `json:"id"`
	ReportID  uuid.UUID `json:"report_id"`
	Rating    string    `json:"rating"`
	Issues    []string  `json:"issues"`
	CreatedAt time.Time `json:"created_at"`
}

// Pulls the last N negative ratings for a therapist. The
// suggestion-engine Go code aggregates by chip category. We cap at
// 5 in production today (the trigger window) but the LIMIT comes
// from the caller so eval / debugging can ask for more.
func (q *Queries) ListRecentNegativeRatings(ctx context.Context, arg ListRecentNegativeRatingsParams) ([]ListRecentNegativeRatingsRow, error) {
	rows, err := q.db.Query(ctx, listRecentNegativeRatings, arg.TherapistID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentNegativeRatingsRow
	for rows.Next() {
		var i ListRecentNegativeRatingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.Rating,
			&i.Issues,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReportRating = `-- name: UpsertReportRating :one
INSERT INTO report_ratings (
    report_id, therapist_id, rating, issues, notes, source
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (report_id, therapist_id) DO UPDATE SET
    rating     = EXCLUDED.rating,
    issues     = EXCLUDED.issues,
    notes      = EXCLUDED.notes,
    source     = EXCLUDED.source,
    updated_at = now()
RETURNING id, report_id, therapist_id, rating, issues, notes, source, created_at, updated_at
`

type UpsertReportRatingParams struct {
	ReportID    uuid.UUID `json:"report_id"`
	TherapistID uuid.UUID `json:"therapist_id"`
	Rating      string    `json:"rating"`
	Issues      []string  `json:"issues"`
	Notes       string    `json:"notes"`
	Source      string    `json:"source"`
}

// UPSERT on the unique (report_id, therapist_id) pair so re-rating
// replaces in place. updated_at is bumped on every conflict — gives
// analytics a "last-touch" timestamp without a separate column.
func (q *Queries) UpsertReportRating(ctx context.Context, arg UpsertReportRatingParams) (ReportRating, error) {
	row := q.db.QueryRow(ctx, upsertReportRating,
		arg.ReportID,
		arg.TherapistID,
		arg.Rating,
		arg.Issues,
		arg.Notes,
		arg.Source,
	)
	var i ReportRating
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.TherapistID,
		&i.Rating,
		&i.Issues,
		&i.Notes,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
