// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminListRecentSessions = `-- name: AdminListRecentSessions :many
SELECT
    s.id,
    s.created_at,
    s.session_date,
    s.duration_seconds,
    s.status::text AS status,
    s.session_number,
    u.id AS therapist_id,
    COALESCE(u.first_name, '') AS therapist_first_name,
    COALESCE(u.last_name,  '') AS therapist_last_name,
    COALESCE(u.email,      '') AS therapist_email,
    COALESCE(u.organization_id::text, '') AS organization_id,
    COALESCE(o.legal_name, '') AS organization_name
FROM sessions s
JOIN users u ON u.id = s.therapist_id
LEFT JOIN organizations o ON o.id = u.organization_id
WHERE s.deleted_at IS NULL
  AND s.created_at >= $1::timestamptz
  AND s.created_at <  $2::timestamptz
  AND (
        $3::text = ''
        OR LOWER(COALESCE(u.first_name,'') || ' ' || COALESCE(u.last_name,'')) LIKE '%' || LOWER($3::text) || '%'
        OR LOWER(COALESCE(u.email,'')) LIKE '%' || LOWER($3::text) || '%'
      )
ORDER BY s.created_at DESC
LIMIT $5::int OFFSET $4::int
`

type AdminListRecentSessionsParams struct {
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	TherapistFilter string    `json:"therapist_filter"`
	PageOffset      int32     `json:"page_offset"`
	PageLimit       int32     `json:"page_limit"`
}

type AdminListRecentSessionsRow struct {
	ID                 uuid.UUID   `json:"id"`
	CreatedAt          time.Time   `json:"created_at"`
	SessionDate        pgtype.Date `json:"session_date"`
	DurationSeconds    *int32      `json:"duration_seconds"`
	Status             string      `json:"status"`
	SessionNumber      int32       `json:"session_number"`
	TherapistID        uuid.UUID   `json:"therapist_id"`
	TherapistFirstName string      `json:"therapist_first_name"`
	TherapistLastName  string      `json:"therapist_last_name"`
	TherapistEmail     string      `json:"therapist_email"`
	OrganizationID     interface{} `json:"organization_id"`
	OrganizationName   string      `json:"organization_name"`
}

// Cross-org session activity for /admin/sessions (SUPERWIZOR_ADMIN).
// Filter window is on sessions.created_at (when the server-side row
// was created, i.e. when the upload landed) — this matches "recent
// activity" semantics better than the user-entered session_date.
//
// The therapist filter is a single substring matched
// case-insensitively against first_name + last_name + email. Empty
// string means "no filter".
//
// ORDER BY created_at DESC + LIMIT/OFFSET pagination. The handler
// requests LIMIT+1 so it can compute has_more without a separate
// COUNT(*) over the (possibly huge) sessions table.
func (q *Queries) AdminListRecentSessions(ctx context.Context, arg AdminListRecentSessionsParams) ([]AdminListRecentSessionsRow, error) {
	rows, err := q.db.Query(ctx, adminListRecentSessions,
		arg.StartTime,
		arg.EndTime,
		arg.TherapistFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListRecentSessionsRow
	for rows.Next() {
		var i AdminListRecentSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SessionDate,
			&i.DurationSeconds,
			&i.Status,
			&i.SessionNumber,
			&i.TherapistID,
			&i.TherapistFirstName,
			&i.TherapistLastName,
			&i.TherapistEmail,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    therapist_id,
    patient_file_id,
    audio_upload_id,
    session_date,
    session_number,
    duration_seconds,
    contact_form,
    speaker_label_mapping,
    language_code,
    report_language,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, therapist_id, patient_file_id, audio_upload_id, session_date, session_number, duration_seconds, contact_form, speaker_label_mapping, language_code, therapist_observations, is_consent_confirmed, status, status_updated_at, error_message, created_at, updated_at, deleted_at, report_language, name
`

type CreateSessionParams struct {
	TherapistID         uuid.UUID     `json:"therapist_id"`
	PatientFileID       uuid.UUID     `json:"patient_file_id"`
	AudioUploadID       pgtype.UUID   `json:"audio_upload_id"`
	SessionDate         pgtype.Date   `json:"session_date"`
	SessionNumber       int32         `json:"session_number"`
	DurationSeconds     *int32        `json:"duration_seconds"`
	ContactForm         ContactForm   `json:"contact_form"`
	SpeakerLabelMapping []byte        `json:"speaker_label_mapping"`
	LanguageCode        *string       `json:"language_code"`
	ReportLanguage      string        `json:"report_language"`
	Status              SessionStatus `json:"status"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TherapistID,
		arg.PatientFileID,
		arg.AudioUploadID,
		arg.SessionDate,
		arg.SessionNumber,
		arg.DurationSeconds,
		arg.ContactForm,
		arg.SpeakerLabelMapping,
		arg.LanguageCode,
		arg.ReportLanguage,
		arg.Status,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.AudioUploadID,
		&i.SessionDate,
		&i.SessionNumber,
		&i.DurationSeconds,
		&i.ContactForm,
		&i.SpeakerLabelMapping,
		&i.LanguageCode,
		&i.TherapistObservations,
		&i.IsConsentConfirmed,
		&i.Status,
		&i.StatusUpdatedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReportLanguage,
		&i.Name,
	)
	return i, err
}

const getDefaultSessionName = `-- name: GetDefaultSessionName :one
SELECT COALESCE(m.display_name, 'Sesja') || ' ' || $2::text AS default_name
FROM patient_files pf
LEFT JOIN modalities m ON m.id = pf.modality_id
WHERE pf.id = $1
`

type GetDefaultSessionNameParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 string    `json:"column_2"`
}

// Compute the default session.name as production would set it on
// create. Used by ingestion-svc.CompleteAudioUpload when populating
// the column for a brand-new session. The COALESCE guards against
// a missing modality join (defensive — modality_id is NOT NULL on
// patient_files so this should never fire, but cheap insurance).
func (q *Queries) GetDefaultSessionName(ctx context.Context, arg GetDefaultSessionNameParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getDefaultSessionName, arg.ID, arg.Column2)
	var default_name interface{}
	err := row.Scan(&default_name)
	return default_name, err
}

const getSession = `-- name: GetSession :one
SELECT id, therapist_id, patient_file_id, audio_upload_id, session_date, session_number, duration_seconds, contact_form, speaker_label_mapping, language_code, therapist_observations, is_consent_confirmed, status, status_updated_at, error_message, created_at, updated_at, deleted_at, report_language, name FROM sessions
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.AudioUploadID,
		&i.SessionDate,
		&i.SessionNumber,
		&i.DurationSeconds,
		&i.ContactForm,
		&i.SpeakerLabelMapping,
		&i.LanguageCode,
		&i.TherapistObservations,
		&i.IsConsentConfirmed,
		&i.Status,
		&i.StatusUpdatedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReportLanguage,
		&i.Name,
	)
	return i, err
}

const getSessionWithDetails = `-- name: GetSessionWithDetails :one
SELECT 
    s.id,
    s.therapist_id,
    s.patient_file_id,
    s.audio_upload_id,
    s.session_date,
    s.session_number,
    s.duration_seconds,
    s.contact_form,
    s.speaker_label_mapping,
    s.language_code,
    s.report_language,
    s.status,
    s.status_updated_at,
    s.created_at,
    s.deleted_at,
    t.id AS transcript_id,
    t.session_id AS transcript_session_id,
    r.id AS report_id,
    r.session_id AS report_session_id
FROM sessions s
LEFT JOIN transcripts t ON t.session_id = s.id
LEFT JOIN reports r ON r.session_id = s.id
WHERE s.id = $1 AND s.deleted_at IS NULL
`

type GetSessionWithDetailsRow struct {
	ID                  uuid.UUID          `json:"id"`
	TherapistID         uuid.UUID          `json:"therapist_id"`
	PatientFileID       uuid.UUID          `json:"patient_file_id"`
	AudioUploadID       pgtype.UUID        `json:"audio_upload_id"`
	SessionDate         pgtype.Date        `json:"session_date"`
	SessionNumber       int32              `json:"session_number"`
	DurationSeconds     *int32             `json:"duration_seconds"`
	ContactForm         ContactForm        `json:"contact_form"`
	SpeakerLabelMapping []byte             `json:"speaker_label_mapping"`
	LanguageCode        *string            `json:"language_code"`
	ReportLanguage      string             `json:"report_language"`
	Status              SessionStatus      `json:"status"`
	StatusUpdatedAt     time.Time          `json:"status_updated_at"`
	CreatedAt           time.Time          `json:"created_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	TranscriptID        pgtype.UUID        `json:"transcript_id"`
	TranscriptSessionID pgtype.UUID        `json:"transcript_session_id"`
	ReportID            pgtype.UUID        `json:"report_id"`
	ReportSessionID     pgtype.UUID        `json:"report_session_id"`
}

func (q *Queries) GetSessionWithDetails(ctx context.Context, id uuid.UUID) (GetSessionWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithDetails, id)
	var i GetSessionWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.AudioUploadID,
		&i.SessionDate,
		&i.SessionNumber,
		&i.DurationSeconds,
		&i.ContactForm,
		&i.SpeakerLabelMapping,
		&i.LanguageCode,
		&i.ReportLanguage,
		&i.Status,
		&i.StatusUpdatedAt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.TranscriptID,
		&i.TranscriptSessionID,
		&i.ReportID,
		&i.ReportSessionID,
	)
	return i, err
}

const getTranscriptBySession = `-- name: GetTranscriptBySession :one
SELECT id, session_id, transcript_ciphertext, transcript_encrypted_dek, language_code, word_count, speaker_count, confidence_avg, stt_model, stt_processed_at, stt_processing_seconds, blob_rebuilt_at, blob_rebuild_count, created_at FROM transcripts
WHERE session_id = $1
`

func (q *Queries) GetTranscriptBySession(ctx context.Context, sessionID uuid.UUID) (Transcript, error) {
	row := q.db.QueryRow(ctx, getTranscriptBySession, sessionID)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TranscriptCiphertext,
		&i.TranscriptEncryptedDek,
		&i.LanguageCode,
		&i.WordCount,
		&i.SpeakerCount,
		&i.ConfidenceAvg,
		&i.SttModel,
		&i.SttProcessedAt,
		&i.SttProcessingSeconds,
		&i.BlobRebuiltAt,
		&i.BlobRebuildCount,
		&i.CreatedAt,
	)
	return i, err
}

const hardDeleteSession = `-- name: HardDeleteSession :execrows
DELETE FROM sessions WHERE id = $1 AND therapist_id = $2
`

type HardDeleteSessionParams struct {
	ID          uuid.UUID `json:"id"`
	TherapistID uuid.UUID `json:"therapist_id"`
}

// Permanent delete. Migration 000012 added ON DELETE CASCADE on
// transcripts.session_id, reports.session_id, hitop_measurements.session_id,
// so dependent rows are removed automatically. notification_deliveries
// gets SET NULL — delivery history survives, just unbound from session.
// audio_uploads.session_id is already SET NULL since 000007.
// The therapist_id predicate is the authz guard at the query level.
// Returns affected rows so the handler can distinguish "not found /
// not yours" (0 rows) from successful delete (1 row).
func (q *Queries) HardDeleteSession(ctx context.Context, arg HardDeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteSession, arg.ID, arg.TherapistID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listReportsBySession = `-- name: ListReportsBySession :many
SELECT id, session_id, transcript_id, modality_id, report_ciphertext, report_encrypted_dek, title, summary_short, sentiment_label, risk_level, speaker_role_inference, llm_model, llm_input_tokens, llm_output_tokens, llm_processing_seconds, llm_total_cost_usd, parent_report_id, generation_count, created_at FROM reports
WHERE session_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReportsBySession(ctx context.Context, sessionID uuid.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TranscriptID,
			&i.ModalityID,
			&i.ReportCiphertext,
			&i.ReportEncryptedDek,
			&i.Title,
			&i.SummaryShort,
			&i.SentimentLabel,
			&i.RiskLevel,
			&i.SpeakerRoleInference,
			&i.LlmModel,
			&i.LlmInputTokens,
			&i.LlmOutputTokens,
			&i.LlmProcessingSeconds,
			&i.LlmTotalCostUsd,
			&i.ParentReportID,
			&i.GenerationCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByPatient = `-- name: ListSessionsByPatient :many
SELECT id, therapist_id, patient_file_id, audio_upload_id, session_date, session_number, duration_seconds, contact_form, speaker_label_mapping, language_code, therapist_observations, is_consent_confirmed, status, status_updated_at, error_message, created_at, updated_at, deleted_at, report_language, name FROM sessions
WHERE patient_file_id = $1 AND deleted_at IS NULL
ORDER BY session_number DESC
`

func (q *Queries) ListSessionsByPatient(ctx context.Context, patientFileID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByPatient, patientFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TherapistID,
			&i.PatientFileID,
			&i.AudioUploadID,
			&i.SessionDate,
			&i.SessionNumber,
			&i.DurationSeconds,
			&i.ContactForm,
			&i.SpeakerLabelMapping,
			&i.LanguageCode,
			&i.TherapistObservations,
			&i.IsConsentConfirmed,
			&i.Status,
			&i.StatusUpdatedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ReportLanguage,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptSegments = `-- name: ListTranscriptSegments :many
SELECT id, transcript_id, speaker_tag, speaker_label, start_offset_ms, end_offset_ms, text_ciphertext, text_encrypted_dek, text_word_count, confidence, created_at FROM transcript_segments
WHERE transcript_id = $1
ORDER BY start_offset_ms ASC
`

func (q *Queries) ListTranscriptSegments(ctx context.Context, transcriptID uuid.UUID) ([]TranscriptSegment, error) {
	rows, err := q.db.Query(ctx, listTranscriptSegments, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranscriptSegment
	for rows.Next() {
		var i TranscriptSegment
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.SpeakerTag,
			&i.SpeakerLabel,
			&i.StartOffsetMs,
			&i.EndOffsetMs,
			&i.TextCiphertext,
			&i.TextEncryptedDek,
			&i.TextWordCount,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionName = `-- name: UpdateSessionName :one
UPDATE sessions
SET name = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, therapist_id, patient_file_id, audio_upload_id, session_date, session_number, duration_seconds, contact_form, speaker_label_mapping, language_code, therapist_observations, is_consent_confirmed, status, status_updated_at, error_message, created_at, updated_at, deleted_at, report_language, name
`

type UpdateSessionNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

// Rename a session. Caller is responsible for the authz check
// (session.therapist_id == ctx user). Returns the refreshed row so
// the gRPC handler can re-emit the proto Session.
func (q *Queries) UpdateSessionName(ctx context.Context, arg UpdateSessionNameParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionName, arg.ID, arg.Name)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.AudioUploadID,
		&i.SessionDate,
		&i.SessionNumber,
		&i.DurationSeconds,
		&i.ContactForm,
		&i.SpeakerLabelMapping,
		&i.LanguageCode,
		&i.TherapistObservations,
		&i.IsConsentConfirmed,
		&i.Status,
		&i.StatusUpdatedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReportLanguage,
		&i.Name,
	)
	return i, err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions
SET status = $2, status_updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateSessionStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status SessionStatus `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatus, arg.ID, arg.Status)
	return err
}
