// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    therapist_id,
    patient_file_id,
    audio_upload_id,
    session_date,
    session_number,
    duration_seconds,
    contact_form,
    speaker_label_mapping,
    language_code,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, therapist_id, patient_file_id, audio_upload_id, session_date, session_number, duration_seconds, contact_form, speaker_label_mapping, language_code, therapist_observations, is_consent_confirmed, status, status_updated_at, error_message, created_at, updated_at, deleted_at
`

type CreateSessionParams struct {
	TherapistID         uuid.UUID     `json:"therapist_id"`
	PatientFileID       uuid.UUID     `json:"patient_file_id"`
	AudioUploadID       pgtype.UUID   `json:"audio_upload_id"`
	SessionDate         pgtype.Date   `json:"session_date"`
	SessionNumber       int32         `json:"session_number"`
	DurationSeconds     *int32        `json:"duration_seconds"`
	ContactForm         ContactForm   `json:"contact_form"`
	SpeakerLabelMapping []byte        `json:"speaker_label_mapping"`
	LanguageCode        *string       `json:"language_code"`
	Status              SessionStatus `json:"status"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TherapistID,
		arg.PatientFileID,
		arg.AudioUploadID,
		arg.SessionDate,
		arg.SessionNumber,
		arg.DurationSeconds,
		arg.ContactForm,
		arg.SpeakerLabelMapping,
		arg.LanguageCode,
		arg.Status,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.AudioUploadID,
		&i.SessionDate,
		&i.SessionNumber,
		&i.DurationSeconds,
		&i.ContactForm,
		&i.SpeakerLabelMapping,
		&i.LanguageCode,
		&i.TherapistObservations,
		&i.IsConsentConfirmed,
		&i.Status,
		&i.StatusUpdatedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, therapist_id, patient_file_id, audio_upload_id, session_date, session_number, duration_seconds, contact_form, speaker_label_mapping, language_code, therapist_observations, is_consent_confirmed, status, status_updated_at, error_message, created_at, updated_at, deleted_at FROM sessions
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TherapistID,
		&i.PatientFileID,
		&i.AudioUploadID,
		&i.SessionDate,
		&i.SessionNumber,
		&i.DurationSeconds,
		&i.ContactForm,
		&i.SpeakerLabelMapping,
		&i.LanguageCode,
		&i.TherapistObservations,
		&i.IsConsentConfirmed,
		&i.Status,
		&i.StatusUpdatedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTranscriptBySession = `-- name: GetTranscriptBySession :one
SELECT id, session_id, transcript_ciphertext, transcript_encrypted_dek, language_code, word_count, speaker_count, confidence_avg, stt_model, stt_processed_at, stt_processing_seconds, blob_rebuilt_at, blob_rebuild_count, created_at FROM transcripts
WHERE session_id = $1
`

func (q *Queries) GetTranscriptBySession(ctx context.Context, sessionID uuid.UUID) (Transcript, error) {
	row := q.db.QueryRow(ctx, getTranscriptBySession, sessionID)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TranscriptCiphertext,
		&i.TranscriptEncryptedDek,
		&i.LanguageCode,
		&i.WordCount,
		&i.SpeakerCount,
		&i.ConfidenceAvg,
		&i.SttModel,
		&i.SttProcessedAt,
		&i.SttProcessingSeconds,
		&i.BlobRebuiltAt,
		&i.BlobRebuildCount,
		&i.CreatedAt,
	)
	return i, err
}

const listReportsBySession = `-- name: ListReportsBySession :many
SELECT id, session_id, transcript_id, modality_id, report_ciphertext, report_encrypted_dek, title, summary_short, sentiment_label, risk_level, speaker_role_inference, llm_model, llm_input_tokens, llm_output_tokens, llm_processing_seconds, llm_total_cost_usd, parent_report_id, generation_count, created_at FROM reports
WHERE session_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReportsBySession(ctx context.Context, sessionID uuid.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TranscriptID,
			&i.ModalityID,
			&i.ReportCiphertext,
			&i.ReportEncryptedDek,
			&i.Title,
			&i.SummaryShort,
			&i.SentimentLabel,
			&i.RiskLevel,
			&i.SpeakerRoleInference,
			&i.LlmModel,
			&i.LlmInputTokens,
			&i.LlmOutputTokens,
			&i.LlmProcessingSeconds,
			&i.LlmTotalCostUsd,
			&i.ParentReportID,
			&i.GenerationCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByPatient = `-- name: ListSessionsByPatient :many
SELECT id, therapist_id, patient_file_id, audio_upload_id, session_date, session_number, duration_seconds, contact_form, speaker_label_mapping, language_code, therapist_observations, is_consent_confirmed, status, status_updated_at, error_message, created_at, updated_at, deleted_at FROM sessions
WHERE patient_file_id = $1 AND deleted_at IS NULL
ORDER BY session_number DESC
`

func (q *Queries) ListSessionsByPatient(ctx context.Context, patientFileID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByPatient, patientFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TherapistID,
			&i.PatientFileID,
			&i.AudioUploadID,
			&i.SessionDate,
			&i.SessionNumber,
			&i.DurationSeconds,
			&i.ContactForm,
			&i.SpeakerLabelMapping,
			&i.LanguageCode,
			&i.TherapistObservations,
			&i.IsConsentConfirmed,
			&i.Status,
			&i.StatusUpdatedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptSegments = `-- name: ListTranscriptSegments :many
SELECT id, transcript_id, speaker_tag, speaker_label, start_offset_ms, end_offset_ms, text_ciphertext, text_encrypted_dek, text_word_count, confidence, created_at FROM transcript_segments
WHERE transcript_id = $1
ORDER BY start_offset_ms ASC
`

func (q *Queries) ListTranscriptSegments(ctx context.Context, transcriptID uuid.UUID) ([]TranscriptSegment, error) {
	rows, err := q.db.Query(ctx, listTranscriptSegments, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranscriptSegment
	for rows.Next() {
		var i TranscriptSegment
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.SpeakerTag,
			&i.SpeakerLabel,
			&i.StartOffsetMs,
			&i.EndOffsetMs,
			&i.TextCiphertext,
			&i.TextEncryptedDek,
			&i.TextWordCount,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions
SET status = $2, status_updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateSessionStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status SessionStatus `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatus, arg.ID, arg.Status)
	return err
}
