// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_billing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserDisplayName = `-- name: GetUserDisplayName :one
SELECT first_name, last_name
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserDisplayNameRow struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

// first_name + last_name for a user (therapist), used by
// SavePatientNote to populate the action-plan e-mail's
// therapist_display_name. Both columns are NOT NULL on the users table
// (migration 000003) so no null handling is needed here.
func (q *Queries) GetUserDisplayName(ctx context.Context, id uuid.UUID) (GetUserDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, getUserDisplayName, id)
	var i GetUserDisplayNameRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}

const getUserOrganizationID = `-- name: GetUserOrganizationID :one
SELECT organization_id
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

// Resolves users.organization_id for a therapist — used by
// clinical-svc.GetMyBillingState (proxy to billing-svc.GetSubscription)
// to derive the org from the auth-context user_id.
//
// Returns NULL via pgtype.UUID when the user isn't bound to an org
// yet (rare after the trial-signup bootstrap — but handled
// defensively in the caller as FailedPrecondition).
func (q *Queries) GetUserOrganizationID(ctx context.Context, id uuid.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserOrganizationID, id)
	var organization_id pgtype.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}
