DROP TABLE IF EXISTS rag_memory CASCADE;
DROP TABLE IF EXISTS hitop_measurements CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS transcript_segments CASCADE;
DROP TABLE IF EXISTS transcripts CASCADE;
