import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

// next-intl plugin: tells the framework where the per-request i18n
// config lives. Path is relative to the project root.
const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");

const nextConfig: NextConfig = {
  // @superwizor/proto-ts ships raw .ts files (generated by buf — see
  // superwizor-backend/buf.gen.yaml). Next needs to transpile them via
  // its own toolchain instead of expecting pre-compiled .js. This is
  // the standard pattern for monorepo-local TS packages.
  transpilePackages: ["@superwizor/proto-ts"],
};

export default withNextIntl(nextConfig);
