import type { NextConfig } from "next";
import createNextIntlPlugin from "next-intl/plugin";

// next-intl plugin: tells the framework where the per-request i18n
// config lives. Path is relative to the project root.
const withNextIntl = createNextIntlPlugin("./src/i18n/request.ts");

const nextConfig: NextConfig = {
  // Static export — Firebase Hosting serves the prerendered HTML
  // directly, no SSR Cloud Function required. Per the 2026-05-28
  // diagnosis: the firebase-frameworks adapter's npm-ci-against-pnpm-
  // lockfile dance breaks Cloud Build deploys. Pure static export
  // sidesteps that entirely — pages with dynamic data fetch it
  // client-side at runtime against the Cloud Run backends.
  output: process.env.NODE_ENV === "production" ? "export" : undefined,

  // Required for static export: every route becomes a directory with
  // an index.html. Firebase Hosting resolves them without explicit
  // .html extensions in the URL bar.
  trailingSlash: true,

  // next/image's default loader requires a server. Switch to the
  // unoptimized renderer so static export works. We don't ship many
  // images and what we do have is already optimised at design time.
  images: {
    unoptimized: true,
  },

  // @superwizor/proto-ts ships raw .ts files (generated by buf — see
  // superwizor-backend/buf.gen.yaml). Next needs to transpile them via
  // its own toolchain instead of expecting pre-compiled .js. This is
  // the standard pattern for monorepo-local TS packages.
  transpilePackages: ["@superwizor/proto-ts"],

  // ── Local dev rewrites ──────────────────────────────────────────
  // In production the static export is served by Firebase Hosting
  // which has Cloud Run rewrites for /api/* (see firebase.json).
  // In dev mode we proxy these routes to the local Go backend
  // services (started by KOMENDY/1 → run_local_backend.sh).
  async rewrites() {
    return [
      // billing-svc (port 8081)
      { source: "/api/checkout", destination: "http://127.0.0.1:8081/api/checkout" },
      { source: "/api/billing-portal", destination: "http://127.0.0.1:8081/api/billing-portal" },
      // identity-svc (port 8080)
      { source: "/api/nip-lookup", destination: "http://127.0.0.1:8080/api/nip-lookup" },
    ];
  },

  // Note: the /login → app.superwizor.ai redirect that previously
  // lived in `redirects()` is now handled by Firebase Hosting (see
  // firebase.json `hosting[0].redirects`). Static export builds
  // forbid the next.config redirect API — Hosting-level redirects
  // are the equivalent and run at the edge, not in a Cloud Function.
};

export default withNextIntl(nextConfig);
