// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUsageCounter = `-- name: CreateUsageCounter :one
INSERT INTO usage_counters (
    subscription_id, period_start, period_end,
    tokens_used, tokens_reserved, tokens_limit
) VALUES (
    $1, $2, $3, 0, 0, $4
)
RETURNING id, subscription_id, period_start, period_end,
          tokens_used, tokens_reserved, tokens_limit, updated_at
`

type CreateUsageCounterParams struct {
	SubscriptionID uuid.UUID `json:"subscription_id"`
	PeriodStart    time.Time `json:"period_start"`
	PeriodEnd      time.Time `json:"period_end"`
	TokensLimit    int32     `json:"tokens_limit"`
}

// Tworzy nowy bucket licznika dla rozpoczętego okresu. UNIQUE (subscription_id,
// period_start) chroni przed double-create przy concurrent renewal.
func (q *Queries) CreateUsageCounter(ctx context.Context, arg CreateUsageCounterParams) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, createUsageCounter,
		arg.SubscriptionID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TokensLimit,
	)
	var i UsageCounter
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TokensUsed,
		&i.TokensReserved,
		&i.TokensLimit,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredManualSubscriptions = `-- name: ListExpiredManualSubscriptions :many
SELECT
    s.id, s.organization_id, s.plan_id,
    s.current_period_start, s.current_period_end,
    p.tokens_per_period
FROM subscriptions s
JOIN subscription_plans p ON p.id = s.plan_id
WHERE s.provider = 'MANUAL'
  AND s.status = 'ACTIVE'
  AND s.current_period_end < now()
`

type ListExpiredManualSubscriptionsRow struct {
	ID                 uuid.UUID `json:"id"`
	OrganizationID     uuid.UUID `json:"organization_id"`
	PlanID             uuid.UUID `json:"plan_id"`
	CurrentPeriodStart time.Time `json:"current_period_start"`
	CurrentPeriodEnd   time.Time `json:"current_period_end"`
	TokensPerPeriod    int32     `json:"tokens_per_period"`
}

// Cron daily o 00:05 UTC — znajduje MANUAL ACTIVE subskrypcje, których
// bieżący okres rozliczeniowy się skończył (period_end < now).
// Per row musimy: shift current_period_*, utworzyć nowy usage_counters.
func (q *Queries) ListExpiredManualSubscriptions(ctx context.Context) ([]ListExpiredManualSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredManualSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredManualSubscriptionsRow
	for rows.Next() {
		var i ListExpiredManualSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PlanID,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.TokensPerPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsMissingCounter = `-- name: ListSubscriptionsMissingCounter :many
SELECT s.id, s.organization_id, s.plan_id, s.current_period_start, s.current_period_end,
       p.tokens_per_period
FROM subscriptions s
JOIN subscription_plans p ON p.id = s.plan_id
WHERE s.status IN ('ACTIVE', 'TRIALING')
  AND NOT EXISTS (
    SELECT 1 FROM usage_counters c
    WHERE c.subscription_id = s.id
      AND c.period_start <= now()
      AND c.period_end > now()
)
`

type ListSubscriptionsMissingCounterRow struct {
	ID                 uuid.UUID `json:"id"`
	OrganizationID     uuid.UUID `json:"organization_id"`
	PlanID             uuid.UUID `json:"plan_id"`
	CurrentPeriodStart time.Time `json:"current_period_start"`
	CurrentPeriodEnd   time.Time `json:"current_period_end"`
	TokensPerPeriod    int32     `json:"tokens_per_period"`
}

// Weekly safety-check — znajdź ACTIVE/TRIALING subskrypcje, które nie mają
// aktywnego usage_counters dla bieżącego momentu. Jeśli się pojawi
// którakolwiek — alert (cron triggeruje monitoring).
func (q *Queries) ListSubscriptionsMissingCounter(ctx context.Context) ([]ListSubscriptionsMissingCounterRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsMissingCounter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsMissingCounterRow
	for rows.Next() {
		var i ListSubscriptionsMissingCounterRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PlanID,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.TokensPerPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shiftSubscriptionPeriod = `-- name: ShiftSubscriptionPeriod :exec
UPDATE subscriptions
SET current_period_start = $2,
    current_period_end   = $3,
    updated_at = now()
WHERE id = $1
`

type ShiftSubscriptionPeriodParams struct {
	ID                 uuid.UUID `json:"id"`
	CurrentPeriodStart time.Time `json:"current_period_start"`
	CurrentPeriodEnd   time.Time `json:"current_period_end"`
}

// Atomic shift okresu rozliczeniowego — używane przez manual renewal cron
// ORAZ (w slice 2) przez Stripe invoice.paid handler.
func (q *Queries) ShiftSubscriptionPeriod(ctx context.Context, arg ShiftSubscriptionPeriodParams) error {
	_, err := q.db.Exec(ctx, shiftSubscriptionPeriod, arg.ID, arg.CurrentPeriodStart, arg.CurrentPeriodEnd)
	return err
}
