// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// pg_advisory_xact_lock per subscription_id — serializuje wszystkie operacje
	// billingowe dotyczące tej samej subskrypcji. Lock zwalniany automatycznie
	// na koniec transakcji (xact = transaction-scoped).
	//
	// hashtextextended(text, 0) daje bigint hash z UUID-stringa — pg_advisory_xact_lock
	// wymaga bigint, a my chcemy klucza pochodzącego z subscription_id.
	// Collision risk z innych advisory locks: niski (przestrzeń bigint, my
	// używamy advisory_xact_lock tylko w tym miejscu w całym systemie billingowym).
	AcquireSubscriptionLock(ctx context.Context, dollar_1 string) error
	// Inkrementuje tokens_reserved. Wywoływane PO sprawdzeniu dostępności
	// w transakcji ReserveCredit.
	AddReservedTokens(ctx context.Context, arg AddReservedTokensParams) error
	// AdminChangePlan step 1. Flips subscriptions.plan_id to the new plan.
	// tokens_used + tokens_reserved on the active counter are LEFT ALONE;
	// only tokens_limit is updated separately (via AdminUpdateCounter using
	// the new plan's tokens_per_period). If the operator wants a clean
	// slate, they follow up with AdminResetTokens.
	AdminChangeSubscriptionPlan(ctx context.Context, arg AdminChangeSubscriptionPlanParams) (Subscription, error)
	// ──────────────────────────────────────────────────────────────────
	// Web-admin RPCs (docs/18 §13.7) — SUPERWIZOR_ADMIN actions.
	// ──────────────────────────────────────────────────────────────────
	// Resolves a (plan_tier, billing_cycle) pair to the live subscription_plans
	// row — used by AdminChangePlan to look up the new tier's tokens_per_period.
	AdminGetPlanByTierCycle(ctx context.Context, arg AdminGetPlanByTierCycleParams) (SubscriptionPlan, error)
	// AdminResetTokens, per-therapist half (docs/38): applies the
	// tokens_used override to EVERY active per-seat counter of the
	// subscription. tokens_limit is intentionally NOT applied here — per
	// -therapist limits come from each seat's plan; an org-wide limit
	// override only makes sense on the org-level counter.
	AdminResetTherapistCounters(ctx context.Context, arg AdminResetTherapistCountersParams) (int64, error)
	// AdminResetTokens core. Selective COALESCE — pass NULL on tokens_used or
	// tokens_limit to leave that column unchanged. The handler maps proto
	// value -1 (sentinel) to NULL before calling.
	AdminUpdateCounter(ctx context.Context, arg AdminUpdateCounterParams) (UsageCounter, error)
	// Sprawdza czy istnieje usage_counter dla danej subskrypcji i okresu.
	// Używane w upsertSubscriptionFromStripe żeby uniknąć UNIQUE violation
	// w transakcji (które by ją unieważniły w Postgresie).
	CheckUsageCounterExists(ctx context.Context, arg CheckUsageCounterExistsParams) (bool, error)
	// Atomic: inkrement tokens_used + dekrement tokens_reserved.
	// Używane w CommitUsage tylko jeśli usage_events INSERT zwrócił nowy row.
	CommitTokens(ctx context.Context, arg CommitTokensParams) error
	// Web-admin actions (SUPERWIZOR_ADMIN) on billing data land here. Mirrors
	// identity-svc's audit_events insert. reason is enforced >=10 chars at
	// the handler level, NOT NULL-allowed at the schema level (legacy events
	// don't have it populated).
	CreateBillingAuditEvent(ctx context.Context, arg CreateBillingAuditEventParams) (AuditEvent, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	// Admin-provisioned B2B subscription (docs/38 §4). provider_subscription_id
	// is deterministic ("b2b-<org>") so a wizard retry collides on the
	// UNIQUE(provider, provider_subscription_id) instead of double-creating.
	CreateManualSubscription(ctx context.Context, arg CreateManualSubscriptionParams) (CreateManualSubscriptionRow, error)
	// Idempotent insert zdarzenia płatności (ADR-BL-002).
	// UNIQUE(provider, provider_event_id) zapewnia że to samo zdarzenie
	// Stripe nie zostanie przetworzone dwukrotnie — zwraca pusty RETURNING
	// przy konflikcie (caller sprawdza czy id jest zero UUID).
	CreatePaymentEvent(ctx context.Context, arg CreatePaymentEventParams) (CreatePaymentEventRow, error)
	// Insert webhook event jako IGNORED (stub mode). UNIQUE constraint na
	// (provider, provider_event_id) zwróci unique-violation przy duplikacie —
	// caller (StripeStubHandler) używa tego do idempotency check.
	CreatePaymentEventStub(ctx context.Context, arg CreatePaymentEventStubParams) (CreatePaymentEventStubRow, error)
	// Tworzy rezerwację. UNIQUE constraint na session_id zapewnia że nawet
	// równoczesny ReserveCredit z różnymi idempotency_keys da tylko jedną
	// rezerwację — drugi dostanie unique-violation i handler przechwyci.
	CreateReservation(ctx context.Context, arg CreateReservationParams) (PendingReservation, error)
	// Per-seat counter, minted by AdminSetSeatAllocations for already-seated
	// therapists and lazily by the debit path for later joiners. UNIQUE
	// (subscription_id, therapist_id, period_start) absorbs races.
	CreateTherapistUsageCounter(ctx context.Context, arg CreateTherapistUsageCounterParams) (UsageCounter, error)
	// Tworzy nowy bucket licznika dla rozpoczętego okresu. UNIQUE (subscription_id,
	// period_start) chroni przed double-create przy concurrent renewal.
	CreateUsageCounter(ctx context.Context, arg CreateUsageCounterParams) (UsageCounter, error)
	// Insert idempotent po session_id (UNIQUE constraint). Race: dwóch równoczesnych
	// CommitUsage z tym samym session_id — jeden wygrywa INSERT, drugi dostaje
	// unique-violation. Handler przechwytuje i refetchuje przez GetUsageEventBySession.
	//
	// Nie używamy ON CONFLICT DO NOTHING bo chcemy rozróżnić "świeży insert"
	// (zwiększyć counter) od "duplikatu" (no-op).
	CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error)
	// Anuluje wszystkie inne aktywne/trialing/past_due subskrypcje dla danej organizacji,
	// oprócz tej o podanym Stripe ID (jeśli podane). Zapobiega to naruszeniu unique index
	// idx_subscriptions_one_active_per_org przy przejściu na płatną subskrypcję.
	DeactivateOtherActiveSubscriptions(ctx context.Context, arg DeactivateOtherActiveSubscriptionsParams) error
	// Pobiera bieżący usage_counters row dla subskrypcji.
	// Zakładamy że istnieje dokładnie jeden aktywny okres na timestamp now()
	// (gwarancja ze §9 — webhook/cron tworzy nowy row przy renewal).
	// W przypadku braku row (race przy renewal) zwraca pgx.ErrNoRows i handler
	// musi tworzyć fallback counter (lub fail z odpowiednim błędem).
	GetActiveCounter(ctx context.Context, subscriptionID uuid.UUID) (UsageCounter, error)
	// Per-therapist counter (docs/38 billing model). NULL-therapist rows
	// (org-level) are matched by GetActiveCounter, not here.
	GetActiveCounterForTherapist(ctx context.Context, arg GetActiveCounterForTherapistParams) (UsageCounter, error)
	// Zwraca pojedynczą subskrypcję uznawaną za "billing-relevant".
	// Constraint idx_subscriptions_one_active_per_org gwarantuje, że
	// jest co najwyżej jedna w stanie ACTIVE/TRIALING/PAST_DUE.
	// Zwracamy też plan-side dane potrzebne do QuotaDecision bez dodatkowego query.
	//
	// DETERMINISTYCZNY wybór (feat/tokens-exhausted, 2026-05-30): mimo że
	// partial-unique index gwarantuje co najwyżej jeden ACTIVE/TRIALING/
	// PAST_DUE per org, kiedyś inwariant został naruszony (failed
	// TRIAL→paid upgrade zostawił dwa wiersze). Bez ORDER BY `LIMIT 1`
	// zwracał DOWOLNY z nich — w incydencie 2026-05-29 zwracał stary
	// TRIAL (3 tokeny) zamiast nowego Solo (20), powodując fałszywe
	// QUOTA_EXHAUSTED. ORDER BY poniżej preferuje płatny plan:
	//   1. ACTIVE > TRIALING > PAST_DUE  (płatny aktywny wygrywa z trialem)
	//   2. najnowszy created_at          (upgrade jest nowszy niż trial)
	// Dzięki temu reserve/quota zawsze patrzy na plan, za który klient
	// faktycznie płaci, nawet jeśli inwariant zostanie kiedyś naruszony.
	GetActiveSubscriptionByOrg(ctx context.Context, organizationID uuid.UUID) (GetActiveSubscriptionByOrgRow, error)
	GetPlanByID(ctx context.Context, id uuid.UUID) (GetPlanByIDRow, error)
	// Lookup planu po stripe_price_id — używane przy checkout.session.completed
	// żeby wiedzieć ile tokenów przypisać i jaki tier.
	GetPlanByStripePriceID(ctx context.Context, stripePriceID *string) (GetPlanByStripePriceIDRow, error)
	// Idempotency lookup PRZED próbą INSERT-u. Zwraca aktywną lub już sfinalizowaną
	// rezerwację (status determinuje co handler robi).
	GetReservationBySession(ctx context.Context, sessionID uuid.UUID) (PendingReservation, error)
	// Lazy counter creation on the debit path: which plan does the caller's
	// open seat sit in? ErrNoRows = therapist has no seat (org-level
	// fallback applies).
	GetSeatPlanForTherapist(ctx context.Context, userID uuid.UUID) (GetSeatPlanForTherapistRow, error)
	// Lookup subskrypcji po stripe subscription ID.
	GetSubscriptionByStripeID(ctx context.Context, providerSubscriptionID string) (GetSubscriptionByStripeIDRow, error)
	// Idempotency lookup. Zwraca już zaistniały event jeśli był (no-op path
	// w CommitUsage).
	GetUsageEventBySession(ctx context.Context, sessionID uuid.UUID) (UsageEvent, error)
	ListActivePlans(ctx context.Context) ([]ListActivePlansRow, error)
	// Per-therapist usage for the current period (GetMyOrgSeatUsage).
	ListActiveTherapistCounters(ctx context.Context, subscriptionID uuid.UUID) ([]ListActiveTherapistCountersRow, error)
	// Cron daily o 00:05 UTC — znajduje MANUAL subskrypcje (ACTIVE + TRIALING),
	// których bieżący okres rozliczeniowy się skończył (period_end < now).
	// TRIALING status covers BETA plan subscriptions (120 tokens × 2 months).
	// Per row musimy: shift current_period_*, utworzyć nowy usage_counters.
	ListExpiredManualSubscriptions(ctx context.Context) ([]ListExpiredManualSubscriptionsRow, error)
	ListInvoicesByOrg(ctx context.Context, organizationID uuid.UUID) ([]Invoice, error)
	// Allocation + catalog plan join + both occupancy halves (docs/38 §3:
	// active assignments + pending unexpired invitations).
	ListSeatAllocationsByOrg(ctx context.Context, organizationID uuid.UUID) ([]ListSeatAllocationsByOrgRow, error)
	// Active (seated) therapists + their seat's plan — counter provisioning
	// in AdminSetSeatAllocations and the GetMyOrgSeatUsage dashboard.
	ListSeatedTherapistsByOrg(ctx context.Context, organizationID uuid.UUID) ([]ListSeatedTherapistsByOrgRow, error)
	// Weekly safety-check — znajdź ACTIVE/TRIALING subskrypcje, które nie mają
	// aktywnego usage_counters dla bieżącego momentu. Jeśli się pojawi
	// którakolwiek — alert (cron triggeruje monitoring).
	ListSubscriptionsMissingCounter(ctx context.Context) ([]ListSubscriptionsMissingCounterRow, error)
	// Wersja z FOR UPDATE — używana wewnątrz transakcji ReserveCredit / CommitUsage,
	// po pg_advisory_xact_lock. SELECT FOR UPDATE chroni przed równoległym
	// modyfikowaniem TEGO konkretnego row (advisory lock chroni przed równoległą
	// pracą per-subscription jeszcze przed dotknięciem row).
	LockActiveCounter(ctx context.Context, subscriptionID uuid.UUID) (UsageCounter, error)
	// FOR UPDATE wariant per-therapist — ReserveCredit/CommitUsage debit
	// path. Advisory lock per subscription is still taken first.
	LockActiveCounterForTherapist(ctx context.Context, arg LockActiveCounterForTherapistParams) (UsageCounter, error)
	// Cron job (release-expired-reservations) — zwraca subscription_id +
	// tokens_reserved per row, żeby handler mógł zaktualizować odpowiednie
	// usage_counters w tej samej transakcji.
	MarkExpiredReservations(ctx context.Context) ([]MarkExpiredReservationsRow, error)
	MarkPaymentEventFailed(ctx context.Context, arg MarkPaymentEventFailedParams) error
	MarkPaymentEventProcessed(ctx context.Context, id uuid.UUID) error
	// Wywoływane wewnątrz transakcji CommitUsage, po insert do usage_events.
	MarkReservationCommitted(ctx context.Context, sessionID uuid.UUID) error
	// Wywoływane przez ReleaseCredit (jawne anulowanie sesji).
	MarkReservationReleased(ctx context.Context, sessionID uuid.UUID) error
	// Renewal-policy switch (docs/38): admin-provisioned B2B orgs (invoiced
	// offline) auto-renew their MANUAL subscription; other MANUAL subs are
	// canceled at period end (2026-07 incident policy).
	OrgHasSeatAllocations(ctx context.Context, organizationID uuid.UUID) (bool, error)
	// Dekrementuje tokens_reserved (clamp do 0). Wywoływane przy ReleaseCredit
	// i przy CommitUsage (transfer rezerwacja → used).
	ReleaseReservedTokens(ctx context.Context, arg ReleaseReservedTokensParams) error
	// Atomic shift okresu rozliczeniowego — używane przez manual renewal cron
	// ORAZ (w slice 2) przez Stripe invoice.paid handler.
	ShiftSubscriptionPeriod(ctx context.Context, arg ShiftSubscriptionPeriodParams) error
	// Org-wide aggregate across org-level + per-therapist counters for the
	// current period. GetSubscription fallback for allocation-managed orgs
	// (which may have no org-level row).
	SumActiveCounters(ctx context.Context, subscriptionID uuid.UUID) (SumActiveCountersRow, error)
	// Aktualizuje status subskrypcji i opcjonalnie cancel_at_period_end.
	// Używane przy invoice.payment_failed, customer.subscription.deleted,
	// customer.subscription.updated.
	UpdateSubscriptionStatusByStripeID(ctx context.Context, arg UpdateSubscriptionStatusByStripeIDParams) error
	// Aktualizuje tokens_limit i period_end dla istniejącego usage_counter
	// przy zmianie planu (upgrade/downgrade). Nie resetuje tokens_used/reserved.
	UpdateUsageCounterOnPlanChange(ctx context.Context, arg UpdateUsageCounterOnPlanChangeParams) error
	// Seat allocations — billing-svc side (docs/38 §3-4).
	//
	// billing-svc OWNS org_seat_allocations writes (AdminSetSeatAllocations);
	// identity-svc reads them for invite-time seat checks. seat_assignments
	// is written by identity-svc (AcceptInvitation / SetTherapistStatus);
	// billing reads it for occupancy + counter provisioning.
	UpsertSeatAllocation(ctx context.Context, arg UpsertSeatAllocationParams) (OrgSeatAllocation, error)
	// Tworzy lub aktualizuje subskrypcję po zdarzeniu Stripe.
	// ON CONFLICT (provider, provider_subscription_id) aktualizuje pola.
	// Używane przy checkout.session.completed i customer.subscription.created.
	UpsertStripeSubscription(ctx context.Context, arg UpsertStripeSubscriptionParams) (UpsertStripeSubscriptionRow, error)
}

var _ Querier = (*Queries)(nil)
