// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// pg_advisory_xact_lock per subscription_id — serializuje wszystkie operacje
	// billingowe dotyczące tej samej subskrypcji. Lock zwalniany automatycznie
	// na koniec transakcji (xact = transaction-scoped).
	//
	// hashtextextended(text, 0) daje bigint hash z UUID-stringa — pg_advisory_xact_lock
	// wymaga bigint, a my chcemy klucza pochodzącego z subscription_id.
	// Collision risk z innych advisory locks: niski (przestrzeń bigint, my
	// używamy advisory_xact_lock tylko w tym miejscu w całym systemie billingowym).
	AcquireSubscriptionLock(ctx context.Context, dollar_1 string) error
	// Inkrementuje tokens_reserved. Wywoływane PO sprawdzeniu dostępności
	// w transakcji ReserveCredit.
	AddReservedTokens(ctx context.Context, arg AddReservedTokensParams) error
	// Atomic: inkrement tokens_used + dekrement tokens_reserved.
	// Używane w CommitUsage tylko jeśli usage_events INSERT zwrócił nowy row.
	CommitTokens(ctx context.Context, arg CommitTokensParams) error
	// Tworzy rezerwację. UNIQUE constraint na session_id zapewnia że nawet
	// równoczesny ReserveCredit z różnymi idempotency_keys da tylko jedną
	// rezerwację — drugi dostanie unique-violation i handler przechwyci.
	CreateReservation(ctx context.Context, arg CreateReservationParams) (PendingReservation, error)
	// Insert idempotent po session_id (UNIQUE constraint). Race: dwóch równoczesnych
	// CommitUsage z tym samym session_id — jeden wygrywa INSERT, drugi dostaje
	// unique-violation. Handler przechwytuje i refetchuje przez GetUsageEventBySession.
	//
	// Nie używamy ON CONFLICT DO NOTHING bo chcemy rozróżnić "świeży insert"
	// (zwiększyć counter) od "duplikatu" (no-op).
	CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error)
	// Pobiera bieżący usage_counters row dla subskrypcji.
	// Zakładamy że istnieje dokładnie jeden aktywny okres na timestamp now()
	// (gwarancja ze §9 — webhook/cron tworzy nowy row przy renewal).
	// W przypadku braku row (race przy renewal) zwraca pgx.ErrNoRows i handler
	// musi tworzyć fallback counter (lub fail z odpowiednim błędem).
	GetActiveCounter(ctx context.Context, subscriptionID uuid.UUID) (UsageCounter, error)
	// Zwraca pojedynczą subskrypcję uznawaną za "billing-relevant".
	// Constraint idx_subscriptions_one_active_per_org gwarantuje, że
	// jest co najwyżej jedna w stanie ACTIVE/TRIALING/PAST_DUE.
	// Zwracamy też plan-side dane potrzebne do QuotaDecision bez dodatkowego query.
	GetActiveSubscriptionByOrg(ctx context.Context, organizationID uuid.UUID) (GetActiveSubscriptionByOrgRow, error)
	// Idempotency lookup PRZED próbą INSERT-u. Zwraca aktywną lub już sfinalizowaną
	// rezerwację (status determinuje co handler robi).
	GetReservationBySession(ctx context.Context, sessionID uuid.UUID) (PendingReservation, error)
	GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error)
	// Idempotency lookup. Zwraca już zaistniały event jeśli był (no-op path
	// w CommitUsage).
	GetUsageEventBySession(ctx context.Context, sessionID uuid.UUID) (UsageEvent, error)
	// Wersja z FOR UPDATE — używana wewnątrz transakcji ReserveCredit / CommitUsage,
	// po pg_advisory_xact_lock. SELECT FOR UPDATE chroni przed równoległym
	// modyfikowaniem TEGO konkretnego row (advisory lock chroni przed równoległą
	// pracą per-subscription jeszcze przed dotknięciem row).
	LockActiveCounter(ctx context.Context, subscriptionID uuid.UUID) (UsageCounter, error)
	// Cron job (release-expired-reservations) — zwraca subscription_id +
	// tokens_reserved per row, żeby handler mógł zaktualizować odpowiednie
	// usage_counters w tej samej transakcji.
	MarkExpiredReservations(ctx context.Context) ([]MarkExpiredReservationsRow, error)
	// Wywoływane wewnątrz transakcji CommitUsage, po insert do usage_events.
	MarkReservationCommitted(ctx context.Context, sessionID uuid.UUID) error
	// Wywoływane przez ReleaseCredit (jawne anulowanie sesji).
	MarkReservationReleased(ctx context.Context, sessionID uuid.UUID) error
	// Dekrementuje tokens_reserved (clamp do 0). Wywoływane przy ReleaseCredit
	// i przy CommitUsage (transfer rezerwacja → used).
	ReleaseReservedTokens(ctx context.Context, arg ReleaseReservedTokensParams) error
}

var _ Querier = (*Queries)(nil)
