// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO pending_reservations (
    session_id, subscription_id, organization_id,
    tokens_reserved, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, session_id, subscription_id, organization_id,
          tokens_reserved, status, created_at, expires_at, finalized_at
`

type CreateReservationParams struct {
	SessionID      uuid.UUID `json:"session_id"`
	SubscriptionID uuid.UUID `json:"subscription_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	TokensReserved int32     `json:"tokens_reserved"`
	ExpiresAt      time.Time `json:"expires_at"`
}

// Tworzy rezerwację. UNIQUE constraint na session_id zapewnia że nawet
// równoczesny ReserveCredit z różnymi idempotency_keys da tylko jedną
// rezerwację — drugi dostanie unique-violation i handler przechwyci.
func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (PendingReservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.SessionID,
		arg.SubscriptionID,
		arg.OrganizationID,
		arg.TokensReserved,
		arg.ExpiresAt,
	)
	var i PendingReservation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SubscriptionID,
		&i.OrganizationID,
		&i.TokensReserved,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FinalizedAt,
	)
	return i, err
}

const getReservationBySession = `-- name: GetReservationBySession :one
SELECT id, session_id, subscription_id, organization_id,
       tokens_reserved, status, created_at, expires_at, finalized_at
FROM pending_reservations
WHERE session_id = $1
`

// Idempotency lookup PRZED próbą INSERT-u. Zwraca aktywną lub już sfinalizowaną
// rezerwację (status determinuje co handler robi).
func (q *Queries) GetReservationBySession(ctx context.Context, sessionID uuid.UUID) (PendingReservation, error) {
	row := q.db.QueryRow(ctx, getReservationBySession, sessionID)
	var i PendingReservation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SubscriptionID,
		&i.OrganizationID,
		&i.TokensReserved,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FinalizedAt,
	)
	return i, err
}

const markExpiredReservations = `-- name: MarkExpiredReservations :many
UPDATE pending_reservations
SET status = 'EXPIRED', finalized_at = now()
WHERE status = 'ACTIVE' AND expires_at < now()
RETURNING id, session_id, subscription_id, tokens_reserved
`

type MarkExpiredReservationsRow struct {
	ID             uuid.UUID `json:"id"`
	SessionID      uuid.UUID `json:"session_id"`
	SubscriptionID uuid.UUID `json:"subscription_id"`
	TokensReserved int32     `json:"tokens_reserved"`
}

// Cron job (release-expired-reservations) — zwraca subscription_id +
// tokens_reserved per row, żeby handler mógł zaktualizować odpowiednie
// usage_counters w tej samej transakcji.
func (q *Queries) MarkExpiredReservations(ctx context.Context) ([]MarkExpiredReservationsRow, error) {
	rows, err := q.db.Query(ctx, markExpiredReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkExpiredReservationsRow
	for rows.Next() {
		var i MarkExpiredReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SubscriptionID,
			&i.TokensReserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReservationCommitted = `-- name: MarkReservationCommitted :exec
UPDATE pending_reservations
SET status = 'COMMITTED', finalized_at = now()
WHERE session_id = $1 AND status = 'ACTIVE'
`

// Wywoływane wewnątrz transakcji CommitUsage, po insert do usage_events.
func (q *Queries) MarkReservationCommitted(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markReservationCommitted, sessionID)
	return err
}

const markReservationReleased = `-- name: MarkReservationReleased :exec
UPDATE pending_reservations
SET status = 'RELEASED', finalized_at = now()
WHERE session_id = $1 AND status = 'ACTIVE'
`

// Wywoływane przez ReleaseCredit (jawne anulowanie sesji).
func (q *Queries) MarkReservationReleased(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markReservationReleased, sessionID)
	return err
}
