// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seat_allocations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createManualSubscription = `-- name: CreateManualSubscription :one
INSERT INTO subscriptions (
    organization_id, plan_id, provider, provider_subscription_id,
    status, current_period_start, current_period_end
) VALUES (
    $1, $2, 'MANUAL', $3, 'ACTIVE', $4, $5
)
ON CONFLICT (provider, provider_subscription_id) DO UPDATE
SET status = 'ACTIVE',
    plan_id = EXCLUDED.plan_id,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    updated_at = now()
RETURNING id, organization_id, plan_id, current_period_start, current_period_end
`

type CreateManualSubscriptionParams struct {
	OrganizationID         uuid.UUID `json:"organization_id"`
	PlanID                 uuid.UUID `json:"plan_id"`
	ProviderSubscriptionID string    `json:"provider_subscription_id"`
	CurrentPeriodStart     time.Time `json:"current_period_start"`
	CurrentPeriodEnd       time.Time `json:"current_period_end"`
}

type CreateManualSubscriptionRow struct {
	ID                 uuid.UUID `json:"id"`
	OrganizationID     uuid.UUID `json:"organization_id"`
	PlanID             uuid.UUID `json:"plan_id"`
	CurrentPeriodStart time.Time `json:"current_period_start"`
	CurrentPeriodEnd   time.Time `json:"current_period_end"`
}

// Admin-provisioned B2B subscription (docs/38 §4). provider_subscription_id
// is deterministic ("b2b-<org>") so a wizard retry — or an edit after the
// renewal cron CANCELED a MANUAL sub (which GetActiveSubscriptionByOrg then
// skips, sending us down this create path) — collides on
// UNIQUE(provider, provider_subscription_id). ON CONFLICT REACTIVATES that
// row instead of erroring ("Błąd serwera" on seat-allocation edit,
// 2026-07-05). Safe: we only reach this branch when the org has no
// ACTIVE/TRIALING/PAST_DUE sub, so flipping the b2b row back to ACTIVE
// can't violate idx_subscriptions_one_active_per_org.
func (q *Queries) CreateManualSubscription(ctx context.Context, arg CreateManualSubscriptionParams) (CreateManualSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, createManualSubscription,
		arg.OrganizationID,
		arg.PlanID,
		arg.ProviderSubscriptionID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i CreateManualSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, tier, cycle, display_name, price_gross, currency_code,
       tokens_per_period, licenses_limit, is_active
FROM subscription_plans
WHERE id = $1
`

type GetPlanByIDRow struct {
	ID              uuid.UUID      `json:"id"`
	Tier            PlanTier       `json:"tier"`
	Cycle           BillingCycle   `json:"cycle"`
	DisplayName     string         `json:"display_name"`
	PriceGross      pgtype.Numeric `json:"price_gross"`
	CurrencyCode    string         `json:"currency_code"`
	TokensPerPeriod int32          `json:"tokens_per_period"`
	LicensesLimit   int32          `json:"licenses_limit"`
	IsActive        bool           `json:"is_active"`
}

func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (GetPlanByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i GetPlanByIDRow
	err := row.Scan(
		&i.ID,
		&i.Tier,
		&i.Cycle,
		&i.DisplayName,
		&i.PriceGross,
		&i.CurrencyCode,
		&i.TokensPerPeriod,
		&i.LicensesLimit,
		&i.IsActive,
	)
	return i, err
}

const getSeatPlanForTherapist = `-- name: GetSeatPlanForTherapist :one
SELECT a.organization_id, p.id AS plan_id, p.tokens_per_period
FROM seat_assignments sa
JOIN org_seat_allocations a ON a.id = sa.allocation_id
JOIN subscription_plans p ON p.id = a.plan_id
WHERE sa.user_id = $1 AND sa.unassigned_at IS NULL
`

type GetSeatPlanForTherapistRow struct {
	OrganizationID  uuid.UUID `json:"organization_id"`
	PlanID          uuid.UUID `json:"plan_id"`
	TokensPerPeriod int32     `json:"tokens_per_period"`
}

// Lazy counter creation on the debit path: which plan does the caller's
// open seat sit in? ErrNoRows = therapist has no seat (org-level
// fallback applies).
func (q *Queries) GetSeatPlanForTherapist(ctx context.Context, userID uuid.UUID) (GetSeatPlanForTherapistRow, error) {
	row := q.db.QueryRow(ctx, getSeatPlanForTherapist, userID)
	var i GetSeatPlanForTherapistRow
	err := row.Scan(&i.OrganizationID, &i.PlanID, &i.TokensPerPeriod)
	return i, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, tier, cycle, display_name, price_gross, currency_code,
       tokens_per_period, licenses_limit
FROM subscription_plans
WHERE is_active = TRUE
ORDER BY tier, cycle
`

type ListActivePlansRow struct {
	ID              uuid.UUID      `json:"id"`
	Tier            PlanTier       `json:"tier"`
	Cycle           BillingCycle   `json:"cycle"`
	DisplayName     string         `json:"display_name"`
	PriceGross      pgtype.Numeric `json:"price_gross"`
	CurrencyCode    string         `json:"currency_code"`
	TokensPerPeriod int32          `json:"tokens_per_period"`
	LicensesLimit   int32          `json:"licenses_limit"`
}

func (q *Queries) ListActivePlans(ctx context.Context) ([]ListActivePlansRow, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePlansRow
	for rows.Next() {
		var i ListActivePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Tier,
			&i.Cycle,
			&i.DisplayName,
			&i.PriceGross,
			&i.CurrencyCode,
			&i.TokensPerPeriod,
			&i.LicensesLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTherapistCounters = `-- name: ListActiveTherapistCounters :many
SELECT c.therapist_id, c.tokens_used, c.tokens_reserved, c.tokens_limit,
       u.first_name, u.last_name, u.is_active
FROM usage_counters c
JOIN users u ON u.id = c.therapist_id
WHERE c.subscription_id = $1
  AND c.therapist_id IS NOT NULL
  AND c.period_start <= now()
  AND c.period_end > now()
ORDER BY u.last_name, u.first_name
`

type ListActiveTherapistCountersRow struct {
	TherapistID    pgtype.UUID `json:"therapist_id"`
	TokensUsed     int32       `json:"tokens_used"`
	TokensReserved int32       `json:"tokens_reserved"`
	TokensLimit    int32       `json:"tokens_limit"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	IsActive       bool        `json:"is_active"`
}

// Per-therapist usage for the current period (GetMyOrgSeatUsage).
func (q *Queries) ListActiveTherapistCounters(ctx context.Context, subscriptionID uuid.UUID) ([]ListActiveTherapistCountersRow, error) {
	rows, err := q.db.Query(ctx, listActiveTherapistCounters, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTherapistCountersRow
	for rows.Next() {
		var i ListActiveTherapistCountersRow
		if err := rows.Scan(
			&i.TherapistID,
			&i.TokensUsed,
			&i.TokensReserved,
			&i.TokensLimit,
			&i.FirstName,
			&i.LastName,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatAllocationsByOrg = `-- name: ListSeatAllocationsByOrg :many
SELECT a.id, a.organization_id, a.plan_id, a.seats,
       a.price_gross_per_seat, a.currency_code,
       p.tier AS plan_tier, p.cycle AS plan_cycle,
       p.price_gross AS catalog_price_gross,
       p.tokens_per_period,
       (SELECT COUNT(*) FROM seat_assignments sa
         WHERE sa.allocation_id = a.id AND sa.unassigned_at IS NULL) AS seats_assigned,
       (SELECT COUNT(*) FROM invitations i
         WHERE i.allocation_id = a.id AND i.accepted_at IS NULL
           AND i.expires_at > now()) AS seats_pending
FROM org_seat_allocations a
JOIN subscription_plans p ON p.id = a.plan_id
WHERE a.organization_id = $1
ORDER BY p.tier, p.cycle
`

type ListSeatAllocationsByOrgRow struct {
	ID                uuid.UUID      `json:"id"`
	OrganizationID    uuid.UUID      `json:"organization_id"`
	PlanID            uuid.UUID      `json:"plan_id"`
	Seats             int32          `json:"seats"`
	PriceGrossPerSeat pgtype.Numeric `json:"price_gross_per_seat"`
	CurrencyCode      string         `json:"currency_code"`
	PlanTier          PlanTier       `json:"plan_tier"`
	PlanCycle         BillingCycle   `json:"plan_cycle"`
	CatalogPriceGross pgtype.Numeric `json:"catalog_price_gross"`
	TokensPerPeriod   int32          `json:"tokens_per_period"`
	SeatsAssigned     int64          `json:"seats_assigned"`
	SeatsPending      int64          `json:"seats_pending"`
}

// Allocation + catalog plan join + both occupancy halves (docs/38 §3:
// active assignments + pending unexpired invitations).
func (q *Queries) ListSeatAllocationsByOrg(ctx context.Context, organizationID uuid.UUID) ([]ListSeatAllocationsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listSeatAllocationsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatAllocationsByOrgRow
	for rows.Next() {
		var i ListSeatAllocationsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PlanID,
			&i.Seats,
			&i.PriceGrossPerSeat,
			&i.CurrencyCode,
			&i.PlanTier,
			&i.PlanCycle,
			&i.CatalogPriceGross,
			&i.TokensPerPeriod,
			&i.SeatsAssigned,
			&i.SeatsPending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatedTherapistsByOrg = `-- name: ListSeatedTherapistsByOrg :many
SELECT u.id AS therapist_id, u.first_name, u.last_name, u.is_active,
       a.id AS allocation_id, a.plan_id,
       p.tier AS plan_tier, p.tokens_per_period
FROM seat_assignments sa
JOIN users u ON u.id = sa.user_id
JOIN org_seat_allocations a ON a.id = sa.allocation_id
JOIN subscription_plans p ON p.id = a.plan_id
WHERE a.organization_id = $1
  AND sa.unassigned_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY u.last_name, u.first_name
`

type ListSeatedTherapistsByOrgRow struct {
	TherapistID     uuid.UUID `json:"therapist_id"`
	FirstName       string    `json:"first_name"`
	LastName        string    `json:"last_name"`
	IsActive        bool      `json:"is_active"`
	AllocationID    uuid.UUID `json:"allocation_id"`
	PlanID          uuid.UUID `json:"plan_id"`
	PlanTier        PlanTier  `json:"plan_tier"`
	TokensPerPeriod int32     `json:"tokens_per_period"`
}

// Active (seated) therapists + their seat's plan — counter provisioning
// in AdminSetSeatAllocations and the GetMyOrgSeatUsage dashboard.
func (q *Queries) ListSeatedTherapistsByOrg(ctx context.Context, organizationID uuid.UUID) ([]ListSeatedTherapistsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listSeatedTherapistsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatedTherapistsByOrgRow
	for rows.Next() {
		var i ListSeatedTherapistsByOrgRow
		if err := rows.Scan(
			&i.TherapistID,
			&i.FirstName,
			&i.LastName,
			&i.IsActive,
			&i.AllocationID,
			&i.PlanID,
			&i.PlanTier,
			&i.TokensPerPeriod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgHasSeatAllocations = `-- name: OrgHasSeatAllocations :one
SELECT EXISTS(
    SELECT 1 FROM org_seat_allocations WHERE organization_id = $1
) AS has_allocations
`

// Renewal-policy switch (docs/38): admin-provisioned B2B orgs (invoiced
// offline) auto-renew their MANUAL subscription; other MANUAL subs are
// canceled at period end (2026-07 incident policy).
func (q *Queries) OrgHasSeatAllocations(ctx context.Context, organizationID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, orgHasSeatAllocations, organizationID)
	var has_allocations bool
	err := row.Scan(&has_allocations)
	return has_allocations, err
}

const upsertSeatAllocation = `-- name: UpsertSeatAllocation :one

INSERT INTO org_seat_allocations (
    organization_id, plan_id, seats, price_gross_per_seat, currency_code
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (organization_id, plan_id) DO UPDATE
SET seats = EXCLUDED.seats,
    price_gross_per_seat = EXCLUDED.price_gross_per_seat,
    currency_code = EXCLUDED.currency_code,
    updated_at = now()
RETURNING id, organization_id, plan_id, seats, price_gross_per_seat,
          currency_code, created_at, updated_at
`

type UpsertSeatAllocationParams struct {
	OrganizationID    uuid.UUID      `json:"organization_id"`
	PlanID            uuid.UUID      `json:"plan_id"`
	Seats             int32          `json:"seats"`
	PriceGrossPerSeat pgtype.Numeric `json:"price_gross_per_seat"`
	CurrencyCode      string         `json:"currency_code"`
}

// Seat allocations — billing-svc side (docs/38 §3-4).
//
// billing-svc OWNS org_seat_allocations writes (AdminSetSeatAllocations);
// identity-svc reads them for invite-time seat checks. seat_assignments
// is written by identity-svc (AcceptInvitation / SetTherapistStatus);
// billing reads it for occupancy + counter provisioning.
func (q *Queries) UpsertSeatAllocation(ctx context.Context, arg UpsertSeatAllocationParams) (OrgSeatAllocation, error) {
	row := q.db.QueryRow(ctx, upsertSeatAllocation,
		arg.OrganizationID,
		arg.PlanID,
		arg.Seats,
		arg.PriceGrossPerSeat,
		arg.CurrencyCode,
	)
	var i OrgSeatAllocation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Seats,
		&i.PriceGrossPerSeat,
		&i.CurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
