// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_counters.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addReservedTokens = `-- name: AddReservedTokens :exec
UPDATE usage_counters
SET tokens_reserved = tokens_reserved + $2,
    updated_at = now()
WHERE id = $1
`

type AddReservedTokensParams struct {
	ID             uuid.UUID `json:"id"`
	TokensReserved int32     `json:"tokens_reserved"`
}

// Inkrementuje tokens_reserved. Wywoływane PO sprawdzeniu dostępności
// w transakcji ReserveCredit.
func (q *Queries) AddReservedTokens(ctx context.Context, arg AddReservedTokensParams) error {
	_, err := q.db.Exec(ctx, addReservedTokens, arg.ID, arg.TokensReserved)
	return err
}

const checkUsageCounterExists = `-- name: CheckUsageCounterExists :one
SELECT EXISTS(
    SELECT 1 FROM usage_counters
    WHERE subscription_id = $1 AND period_start = $2 AND therapist_id IS NULL
) AS exists
`

type CheckUsageCounterExistsParams struct {
	SubscriptionID uuid.UUID `json:"subscription_id"`
	PeriodStart    time.Time `json:"period_start"`
}

// Sprawdza czy istnieje usage_counter dla danej subskrypcji i okresu.
// Używane w upsertSubscriptionFromStripe żeby uniknąć UNIQUE violation
// w transakcji (które by ją unieważniły w Postgresie).
func (q *Queries) CheckUsageCounterExists(ctx context.Context, arg CheckUsageCounterExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsageCounterExists, arg.SubscriptionID, arg.PeriodStart)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const commitTokens = `-- name: CommitTokens :exec
UPDATE usage_counters
SET tokens_used = tokens_used + $2,
    tokens_reserved = GREATEST(0, tokens_reserved - $3),
    updated_at = now()
WHERE id = $1
`

type CommitTokensParams struct {
	ID             uuid.UUID `json:"id"`
	TokensUsed     int32     `json:"tokens_used"`
	TokensReserved int32     `json:"tokens_reserved"`
}

// Atomic: inkrement tokens_used + dekrement tokens_reserved.
// Używane w CommitUsage tylko jeśli usage_events INSERT zwrócił nowy row.
func (q *Queries) CommitTokens(ctx context.Context, arg CommitTokensParams) error {
	_, err := q.db.Exec(ctx, commitTokens, arg.ID, arg.TokensUsed, arg.TokensReserved)
	return err
}

const createTherapistUsageCounter = `-- name: CreateTherapistUsageCounter :one
INSERT INTO usage_counters (
    subscription_id, therapist_id, period_start, period_end,
    tokens_used, tokens_reserved, tokens_limit
) VALUES (
    $1, $2, $3, $4, 0, 0, $5
)
ON CONFLICT (subscription_id, therapist_id, period_start)
    WHERE therapist_id IS NOT NULL
    DO NOTHING
RETURNING id, subscription_id, period_start, period_end,
       tokens_used, tokens_reserved, tokens_limit, updated_at, therapist_id
`

type CreateTherapistUsageCounterParams struct {
	SubscriptionID uuid.UUID   `json:"subscription_id"`
	TherapistID    pgtype.UUID `json:"therapist_id"`
	PeriodStart    time.Time   `json:"period_start"`
	PeriodEnd      time.Time   `json:"period_end"`
	TokensLimit    int32       `json:"tokens_limit"`
}

// Per-seat counter, minted by AdminSetSeatAllocations for already-seated
// therapists and lazily by the debit path for later joiners.
//
// ON CONFLICT DO NOTHING is load-bearing, not just tidy: without it a
// duplicate insert raises 23505, which ABORTS the enclosing pgx
// transaction. Both callers "tolerate" the unique violation and keep
// going, but the next statement on the poisoned tx fails with 25P02
// ("current transaction is aborted") → codes.Internal → the caller 500s.
// This is the AdminSetSeatAllocations 500 on EDIT: an org whose seated
// therapists already have counters violates on the first insert and
// poisons the tx. DO NOTHING makes the insert a no-op on conflict — no
// error raised, tx stays healthy. On conflict RETURNING yields no row,
// so callers get pgx.ErrNoRows (meaning "already exists"); on a fresh
// insert they get the new row. The partial-index predicate is repeated
// so ON CONFLICT targets uq_usage_counters_therapist_period.
func (q *Queries) CreateTherapistUsageCounter(ctx context.Context, arg CreateTherapistUsageCounterParams) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, createTherapistUsageCounter,
		arg.SubscriptionID,
		arg.TherapistID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TokensLimit,
	)
	var i UsageCounter
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TokensUsed,
		&i.TokensReserved,
		&i.TokensLimit,
		&i.UpdatedAt,
		&i.TherapistID,
	)
	return i, err
}

const getActiveCounter = `-- name: GetActiveCounter :one
SELECT id, subscription_id, period_start, period_end,
       tokens_used, tokens_reserved, tokens_limit, updated_at, therapist_id
FROM usage_counters
WHERE subscription_id = $1
  AND therapist_id IS NULL
  AND period_start <= now()
  AND period_end > now()
LIMIT 1
`

// Pobiera bieżący usage_counters row dla subskrypcji.
// Zakładamy że istnieje dokładnie jeden aktywny okres na timestamp now()
// (gwarancja ze §9 — webhook/cron tworzy nowy row przy renewal).
// W przypadku braku row (race przy renewal) zwraca pgx.ErrNoRows i handler
// musi tworzyć fallback counter (lub fail z odpowiednim błędem).
func (q *Queries) GetActiveCounter(ctx context.Context, subscriptionID uuid.UUID) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, getActiveCounter, subscriptionID)
	var i UsageCounter
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TokensUsed,
		&i.TokensReserved,
		&i.TokensLimit,
		&i.UpdatedAt,
		&i.TherapistID,
	)
	return i, err
}

const getActiveCounterForTherapist = `-- name: GetActiveCounterForTherapist :one
SELECT id, subscription_id, period_start, period_end,
       tokens_used, tokens_reserved, tokens_limit, updated_at, therapist_id
FROM usage_counters
WHERE subscription_id = $1
  AND therapist_id = $2
  AND period_start <= now()
  AND period_end > now()
LIMIT 1
`

type GetActiveCounterForTherapistParams struct {
	SubscriptionID uuid.UUID   `json:"subscription_id"`
	TherapistID    pgtype.UUID `json:"therapist_id"`
}

// Per-therapist counter (docs/38 billing model). NULL-therapist rows
// (org-level) are matched by GetActiveCounter, not here.
func (q *Queries) GetActiveCounterForTherapist(ctx context.Context, arg GetActiveCounterForTherapistParams) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, getActiveCounterForTherapist, arg.SubscriptionID, arg.TherapistID)
	var i UsageCounter
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TokensUsed,
		&i.TokensReserved,
		&i.TokensLimit,
		&i.UpdatedAt,
		&i.TherapistID,
	)
	return i, err
}

const lockActiveCounter = `-- name: LockActiveCounter :one
SELECT id, subscription_id, period_start, period_end,
       tokens_used, tokens_reserved, tokens_limit, updated_at, therapist_id
FROM usage_counters
WHERE subscription_id = $1
  AND therapist_id IS NULL
  AND period_start <= now()
  AND period_end > now()
FOR UPDATE
`

// Wersja z FOR UPDATE — używana wewnątrz transakcji ReserveCredit / CommitUsage,
// po pg_advisory_xact_lock. SELECT FOR UPDATE chroni przed równoległym
// modyfikowaniem TEGO konkretnego row (advisory lock chroni przed równoległą
// pracą per-subscription jeszcze przed dotknięciem row).
func (q *Queries) LockActiveCounter(ctx context.Context, subscriptionID uuid.UUID) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, lockActiveCounter, subscriptionID)
	var i UsageCounter
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TokensUsed,
		&i.TokensReserved,
		&i.TokensLimit,
		&i.UpdatedAt,
		&i.TherapistID,
	)
	return i, err
}

const lockActiveCounterForTherapist = `-- name: LockActiveCounterForTherapist :one
SELECT id, subscription_id, period_start, period_end,
       tokens_used, tokens_reserved, tokens_limit, updated_at, therapist_id
FROM usage_counters
WHERE subscription_id = $1
  AND therapist_id = $2
  AND period_start <= now()
  AND period_end > now()
FOR UPDATE
`

type LockActiveCounterForTherapistParams struct {
	SubscriptionID uuid.UUID   `json:"subscription_id"`
	TherapistID    pgtype.UUID `json:"therapist_id"`
}

// FOR UPDATE wariant per-therapist — ReserveCredit/CommitUsage debit
// path. Advisory lock per subscription is still taken first.
func (q *Queries) LockActiveCounterForTherapist(ctx context.Context, arg LockActiveCounterForTherapistParams) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, lockActiveCounterForTherapist, arg.SubscriptionID, arg.TherapistID)
	var i UsageCounter
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.TokensUsed,
		&i.TokensReserved,
		&i.TokensLimit,
		&i.UpdatedAt,
		&i.TherapistID,
	)
	return i, err
}

const releaseReservedTokens = `-- name: ReleaseReservedTokens :exec
UPDATE usage_counters
SET tokens_reserved = GREATEST(0, tokens_reserved - $2),
    updated_at = now()
WHERE id = $1
`

type ReleaseReservedTokensParams struct {
	ID             uuid.UUID `json:"id"`
	TokensReserved int32     `json:"tokens_reserved"`
}

// Dekrementuje tokens_reserved (clamp do 0). Wywoływane przy ReleaseCredit
// i przy CommitUsage (transfer rezerwacja → used).
func (q *Queries) ReleaseReservedTokens(ctx context.Context, arg ReleaseReservedTokensParams) error {
	_, err := q.db.Exec(ctx, releaseReservedTokens, arg.ID, arg.TokensReserved)
	return err
}

const sumActiveCounters = `-- name: SumActiveCounters :one
SELECT COALESCE(SUM(tokens_used), 0)::int AS tokens_used,
       COALESCE(SUM(tokens_reserved), 0)::int AS tokens_reserved,
       COALESCE(SUM(tokens_limit), 0)::int AS tokens_limit,
       COUNT(*) AS counters
FROM usage_counters
WHERE subscription_id = $1
  AND period_start <= now()
  AND period_end > now()
`

type SumActiveCountersRow struct {
	TokensUsed     int32 `json:"tokens_used"`
	TokensReserved int32 `json:"tokens_reserved"`
	TokensLimit    int32 `json:"tokens_limit"`
	Counters       int64 `json:"counters"`
}

// Org-wide aggregate across org-level + per-therapist counters for the
// current period. GetSubscription fallback for allocation-managed orgs
// (which may have no org-level row).
func (q *Queries) SumActiveCounters(ctx context.Context, subscriptionID uuid.UUID) (SumActiveCountersRow, error) {
	row := q.db.QueryRow(ctx, sumActiveCounters, subscriptionID)
	var i SumActiveCountersRow
	err := row.Scan(
		&i.TokensUsed,
		&i.TokensReserved,
		&i.TokensLimit,
		&i.Counters,
	)
	return i, err
}

const updateUsageCounterOnPlanChange = `-- name: UpdateUsageCounterOnPlanChange :exec
UPDATE usage_counters
SET tokens_limit = $3,
    period_end = $4,
    updated_at = now()
WHERE subscription_id = $1 AND period_start = $2 AND therapist_id IS NULL
`

type UpdateUsageCounterOnPlanChangeParams struct {
	SubscriptionID uuid.UUID `json:"subscription_id"`
	PeriodStart    time.Time `json:"period_start"`
	TokensLimit    int32     `json:"tokens_limit"`
	PeriodEnd      time.Time `json:"period_end"`
}

// Aktualizuje tokens_limit i period_end dla istniejącego usage_counter
// przy zmianie planu (upgrade/downgrade). Nie resetuje tokens_used/reserved.
func (q *Queries) UpdateUsageCounterOnPlanChange(ctx context.Context, arg UpdateUsageCounterOnPlanChangeParams) error {
	_, err := q.db.Exec(ctx, updateUsageCounterOnPlanChange,
		arg.SubscriptionID,
		arg.PeriodStart,
		arg.TokensLimit,
		arg.PeriodEnd,
	)
	return err
}
