// Package llmcost is the single versioned price table for every Vertex AI
// model the platform calls. It exists because the same rates were, until
// 2026-08-20, hard-coded in three places and wrong in two of them:
//
//   - llm-worker's header comment quoted $0.075/$0.30 per million
//     (gemini-1.5-flash era rates) for a gemini-2.5-flash workload that
//     actually bills $0.30/$2.50 — understating by 4x on input and 8.3x
//     on output;
//   - reports.llm_total_cost_usd was computed with gemini-2.5-pro rates
//     ($1.25/$5.00) for reports generated by gemini-2.5-flash, overstating
//     every historical row.
//
// Correcting the historical rows is a separate product decision (plan §6);
// this package only makes every NEW computation correct and auditable.
//
// # Integer money
//
// Costs are computed in micro-USD (1e-6 USD) as int64, never float64.
// The chat quota (plan F6) reserves and commits in micro-USD, and float
// accumulation across hundreds of thousands of turns drifts. Rates are
// stored as micro-USD per million tokens, so a rate is itself an exact
// integer: $0.30/M == 300_000 uUSD/M.
//
// CostMicroUSD rounds UP. A reservation or a charge that is short by a
// fraction of a micro-dollar is a slow leak in the quota; rounding up
// costs at most 1 uUSD ($0.000001) per call.
//
// # Adding or changing a rate
//
// Never edit a Rate in place. Append a new Rate with a later EffectiveFrom
// and leave the old one — historical rows must stay reproducible from the
// table, which is the whole point of versioning it. Rates are published at
// https://cloud.google.com/vertex-ai/generative-ai/pricing; the Source
// field records when each row was last checked against it.
package llmcost

import (
	"fmt"
	"sort"
	"time"
)

// Model identifiers. These are the exact strings passed to Vertex AI and
// stored in chat_interactions.model_used / reports.llm_model, so they
// double as the lookup key — no translation layer to drift out of sync.
const (
	Gemini25Flash     = "gemini-2.5-flash"
	Gemini25FlashLite = "gemini-2.5-flash-lite"
	Gemini25Pro       = "gemini-2.5-pro"
	Gemini20Flash     = "gemini-2.0-flash"
	TextEmbedding005  = "text-embedding-005"
)

// MicroUSDPerUSD is the scale factor for the integer money representation.
const MicroUSDPerUSD = 1_000_000

// Rate is one model's price over one validity window.
//
// InputPerMillion / OutputPerMillion are micro-USD per 1,000,000 tokens.
// Embedding models bill input only and carry OutputPerMillion = 0.
type Rate struct {
	Model            string
	InputPerMillion  int64
	OutputPerMillion int64

	// EffectiveFrom is the UTC instant this rate became billable. The
	// zero value means "since forever" and is used for the oldest row
	// of each model, so a lookup at any timestamp always resolves.
	EffectiveFrom time.Time

	// Source records where the numbers came from and when they were
	// last verified, so a future reader can tell a stale row from a
	// current one without re-deriving the whole table.
	Source string
}

// checked is the date the whole table was last reconciled against the
// published Vertex AI price list.
const checked = "2026-08-20"

// table is the price table. Ordered by model, then by EffectiveFrom
// ascending; lookup() relies on the ascending order per model.
//
// The pre-2026 rows are NOT included. Every model in production today
// was already on its current rate when this package was written, and
// inventing historical rows we never billed against would make the table
// look authoritative about a period it cannot actually reconstruct.
var table = []Rate{
	{
		Model:            Gemini25Flash,
		InputPerMillion:  300_000,   // $0.30 / 1M
		OutputPerMillion: 2_500_000, // $2.50 / 1M
		Source:           "Vertex AI public pricing, checked " + checked,
	},
	{
		Model:            Gemini25FlashLite,
		InputPerMillion:  100_000, // $0.10 / 1M
		OutputPerMillion: 400_000, // $0.40 / 1M
		// Retirement signal seen 16.10.2026 — kept in the table because
		// existing rows reference it, but do not route new traffic here.
		Source: "Vertex AI public pricing, checked " + checked + " (model retiring)",
	},
	{
		Model:            Gemini25Pro,
		InputPerMillion:  1_250_000,  // $1.25 / 1M (<=200k context)
		OutputPerMillion: 10_000_000, // $10.00 / 1M (<=200k context)
		Source:           "Vertex AI public pricing, checked " + checked + " (<=200k context tier)",
	},
	{
		Model:            Gemini20Flash,
		InputPerMillion:  150_000, // $0.15 / 1M
		OutputPerMillion: 600_000, // $0.60 / 1M
		Source:           "Vertex AI public pricing, checked " + checked,
	},
	{
		Model:            TextEmbedding005,
		InputPerMillion:  25_000, // $0.025 / 1M
		OutputPerMillion: 0,      // embeddings bill input only
		Source:           "Vertex AI public pricing, checked " + checked,
	},
}

// ErrUnknownModel is returned when a model has no row in the table. It is
// deliberately an error rather than a silent zero: a zero cost for an
// unknown model would let an unpriced model run against the quota for
// free, which is exactly the failure this package exists to prevent.
type ErrUnknownModel struct{ Model string }

func (e ErrUnknownModel) Error() string {
	return fmt.Sprintf("llmcost: no rate for model %q — add it to prices.go", e.Model)
}

// lookup returns the rate in force for model at time at.
func lookup(model string, at time.Time) (Rate, error) {
	var found Rate
	var ok bool
	for _, r := range table {
		if r.Model != model {
			continue
		}
		if r.EffectiveFrom.After(at) {
			continue
		}
		// Ascending EffectiveFrom means the last match wins.
		found, ok = r, true
	}
	if !ok {
		return Rate{}, ErrUnknownModel{Model: model}
	}
	return found, nil
}

// CostMicroUSD returns the cost of one call in micro-USD, rounded up.
//
// at selects the rate version; pass the time the call was billed (for a
// live call, time.Now()). Negative token counts are treated as zero — a
// malformed UsageMetadata must not produce a negative charge that would
// silently refund quota.
func CostMicroUSD(model string, inputTokens, outputTokens int64, at time.Time) (int64, error) {
	r, err := lookup(model, at)
	if err != nil {
		return 0, err
	}
	return r.CostMicroUSD(inputTokens, outputTokens), nil
}

// CostMicroUSD computes the cost against this specific rate. Exposed on
// Rate so a caller that already resolved the rate (the quota reserver,
// which prices an estimate and a commit against the same version) cannot
// accidentally straddle a price change between the two.
func (r Rate) CostMicroUSD(inputTokens, outputTokens int64) int64 {
	if inputTokens < 0 {
		inputTokens = 0
	}
	if outputTokens < 0 {
		outputTokens = 0
	}
	return ceilDiv(inputTokens*r.InputPerMillion, 1_000_000) +
		ceilDiv(outputTokens*r.OutputPerMillion, 1_000_000)
}

// CostUSD returns the cost as a float64 USD amount, for display and for
// the reports.llm_total_cost_usd column (NUMERIC). Money that is going to
// be summed or compared should use CostMicroUSD instead.
func CostUSD(model string, inputTokens, outputTokens int64, at time.Time) (float64, error) {
	micro, err := CostMicroUSD(model, inputTokens, outputTokens, at)
	if err != nil {
		return 0, err
	}
	return float64(micro) / MicroUSDPerUSD, nil
}

// RateFor exposes the resolved rate — used by the quota reserver to price
// an upper-bound estimate and the eventual commit against one version.
func RateFor(model string, at time.Time) (Rate, error) { return lookup(model, at) }

// Models lists every model with a rate, sorted. Used by the admin price
// screen and by a CI check that every model constant is actually priced.
func Models() []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(table))
	for _, r := range table {
		if _, dup := seen[r.Model]; dup {
			continue
		}
		seen[r.Model] = struct{}{}
		out = append(out, r.Model)
	}
	sort.Strings(out)
	return out
}

// ceilDiv divides a by b rounding away from zero for positive a. Inputs
// are non-negative by construction at every call site.
func ceilDiv(a, b int64) int64 {
	if a <= 0 {
		return 0
	}
	return (a + b - 1) / b
}
